
CREATE TABLE erp_md_location(
  ID BIGINT NULL    COMMENT 'null',
  WAREHOUSE_ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_location primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_equipment_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '分类编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '分类名称',
  PARENT_ID BIGINT NULL    COMMENT '上级分类ID',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_equipment_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_asset(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_ast_asset primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_warehouse(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  MATERIAL_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  UOM_GROUP VARCHAR(50) NULL    COMMENT 'null',
  IS_BASE BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_uom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_category(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_material_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_equipment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '设备编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '设备名称',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  ASSET_ID BIGINT NULL    COMMENT '资产卡片(关联 assets 域)',
  WORKCENTER_ID BIGINT NULL    COMMENT '关联工作中心(关联 mfg 域)',
  LOCATION_ID BIGINT NULL    COMMENT '位置ID',
  CATEGORY_ID BIGINT NULL    COMMENT '分类ID',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  SERIAL_NO VARCHAR(100) NULL    COMMENT '序列号',
  MANUFACTURER VARCHAR(200) NULL    COMMENT '制造商',
  MODEL VARCHAR(200) NULL    COMMENT '型号',
  INSTALL_DATE DATE NULL    COMMENT '安装日期',
  WARRANTY_EXPIRY DATE NULL    COMMENT '保修到期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_equipment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_maintenance_team(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '团队编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '团队名称',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  LEADER_ID BIGINT NULL    COMMENT '负责人(职员)',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_maintenance_team primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_schedule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '计划编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '计划名称',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '设备ID',
  SCHEDULE_TYPE VARCHAR(20) NOT NULL    COMMENT '计划类型',
  FREQUENCY INTEGER NULL    COMMENT '频率',
  RECURRENCE_TYPE VARCHAR(20) NULL    COMMENT '重复类型',
  DAYS_OF_WEEK VARCHAR(50) NULL    COMMENT '星期几',
  START_DATE DATE NOT NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  NEXT_DUE_DATE DATE NULL    COMMENT '下次到期日',
  IS_ACTIVE INTEGER default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_schedule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_request(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '请求编码',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '设备ID',
  REQUEST_DATE DATE NOT NULL    COMMENT '请求日期',
  DESCRIPTION VARCHAR(2000) NOT NULL    COMMENT '问题描述',
  PRIORITY VARCHAR(20) NOT NULL    COMMENT '优先级',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REQUESTED_BY BIGINT NOT NULL    COMMENT '请求人',
  ASSIGNED_TO BIGINT NULL    COMMENT '指派人',
  ACCEPTED_BY BIGINT NULL    COMMENT '受理人',
  COMPLETED_BY BIGINT NULL    COMMENT '完成人',
  COMPLETED_AT DATETIME NULL    COMMENT '完成时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_downtime_entry(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '设备ID',
  START_TIME DATETIME NOT NULL    COMMENT '开始时间',
  END_TIME DATETIME NULL    COMMENT '结束时间',
  TOTAL_MINUTES DECIMAL(12,2) NULL    COMMENT '总分钟数',
  REASON VARCHAR(500) NULL    COMMENT '原因',
  RELATED_JOB_ORDER_ID BIGINT NULL    COMMENT '关联生产工单ID',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_downtime_entry primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_calibration(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '被校设备/量具',
  BUSINESS_DATE DATE NOT NULL    COMMENT '校准日期',
  STANDARD_REF VARCHAR(200) NULL    COMMENT '参考标准',
  MEASURED_VALUE DECIMAL(20,6) NULL    COMMENT '测量值',
  TARGET_VALUE DECIMAL(20,6) NULL    COMMENT '目标值',
  TOLERANCE DECIMAL(20,6) NULL    COMMENT '允差',
  RESULT VARCHAR(20) NOT NULL    COMMENT '校准结果',
  NEXT_CALIBRATION_DATE DATE NULL    COMMENT '下次校准日期',
  CALIBRATED_BY BIGINT NULL    COMMENT '校准人(职员)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  constraint PK_erp_mnt_calibration primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_maintenance_team_member(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TEAM_ID BIGINT NOT NULL    COMMENT '团队ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '成员(职员)',
  ROLE VARCHAR(50) NULL    COMMENT '角色',
  JOINED_AT DATETIME NULL    COMMENT '加入时间',
  LEFT_AT DATETIME NULL    COMMENT '退出时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_maintenance_team_member primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_visit(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '访问编码',
  SCHEDULE_ID BIGINT NULL    COMMENT '维护计划ID',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '设备ID',
  VISIT_DATE DATE NOT NULL    COMMENT '访问日期',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  ASSIGNED_TO BIGINT NULL    COMMENT '指派人',
  COMPLETED_BY BIGINT NULL    COMMENT '完成人',
  COMPLETED_AT DATETIME NULL    COMMENT '完成时间',
  START_TIME DATETIME NULL    COMMENT '开始时间',
  END_TIME DATETIME NULL    COMMENT '结束时间',
  TOTAL_MINUTES DECIMAL(12,2) NULL    COMMENT '总分钟数',
  VISIT_TYPE VARCHAR(20) NULL    COMMENT '维护类型',
  RESULT VARCHAR(20) NULL    COMMENT '执行结果',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NULL    COMMENT '业务日期',
  POSTED BOOLEAN default 0  NULL    COMMENT '是否已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(50) NULL    COMMENT '过账人',
  constraint PK_erp_mnt_visit primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_visit_task(
  ID BIGINT NOT NULL    COMMENT 'ID',
  VISIT_ID BIGINT NOT NULL    COMMENT '维护访问ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  TASK_DESCRIPTION VARCHAR(500) NOT NULL    COMMENT '任务描述',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  COMPLETED_BY BIGINT NULL    COMMENT '完成人',
  COMPLETED_AT DATETIME NULL    COMMENT '完成时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_visit_task primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_spare_part_usage(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  VISIT_ID BIGINT NULL    COMMENT '维护访问ID',
  REQUEST_ID BIGINT NULL    COMMENT '维护请求ID',
  EQUIPMENT_ID BIGINT NOT NULL    COMMENT '设备ID',
  BUSINESS_DATE DATE NOT NULL    COMMENT '消耗日期',
  WAREHOUSE_ID BIGINT NULL    COMMENT '领料仓库',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '金额合计',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(库存已出库)',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  constraint PK_erp_mnt_spare_part_usage primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mnt_spare_part_usage_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SPARE_PART_USAGE_ID BIGINT NOT NULL    COMMENT '备件消耗单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '备件(物料)',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '消耗数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mnt_spare_part_usage_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_location COMMENT '库位';
                
   ALTER TABLE erp_mnt_equipment_category COMMENT '设备分类';
                
   ALTER TABLE erp_ast_asset COMMENT '资产';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_employee COMMENT '职员';
                
   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_uom COMMENT '计量单位';
                
   ALTER TABLE erp_md_material_category COMMENT '物料分类';
                
   ALTER TABLE erp_mnt_equipment COMMENT '设备';
                
   ALTER TABLE erp_mnt_maintenance_team COMMENT '维护团队';
                
   ALTER TABLE erp_mnt_schedule COMMENT '维护计划';
                
   ALTER TABLE erp_mnt_request COMMENT '维护请求';
                
   ALTER TABLE erp_mnt_downtime_entry COMMENT '停机记录';
                
   ALTER TABLE erp_mnt_calibration COMMENT '校准记录';
                
   ALTER TABLE erp_mnt_maintenance_team_member COMMENT '维护团队成员';
                
   ALTER TABLE erp_mnt_visit COMMENT '维护访问';
                
   ALTER TABLE erp_mnt_visit_task COMMENT '维护任务';
                
   ALTER TABLE erp_mnt_spare_part_usage COMMENT '备件消耗';
                
   ALTER TABLE erp_mnt_spare_part_usage_line COMMENT '备件消耗行';
                
