
CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SYMBOL VARCHAR(50) NULL    COMMENT 'null',
  DECIMAL_PLACES INTEGER NULL    COMMENT 'null',
  IS_FUNCTIONAL BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_subject(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  SUBJECT_CLASS INTEGER NULL    COMMENT 'null',
  DIRECTION INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_subject primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_project_type(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '类型编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '类型名称',
  DEFAULT_SUBJECT_ID BIGINT NULL    COMMENT '默认科目',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_project_type primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_activity_type(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '类型编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '类型名称',
  COST_RATE DECIMAL(20,4) NULL    COMMENT '成本费率',
  SUBJECT_ID BIGINT NULL    COMMENT '科目',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_activity_type primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_project(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '项目编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '项目名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PROJECT_TYPE_ID BIGINT NULL    COMMENT '项目类型',
  CUSTOMER_ID BIGINT NULL    COMMENT '客户',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  BUDGET DECIMAL(20,4) default 0  NULL    COMMENT '预算总额',
  COMMITTED_COST DECIMAL(20,4) default 0  NULL    COMMENT '已承诺成本',
  ACTUAL_COST DECIMAL(20,4) default 0  NULL    COMMENT '实际成本',
  BILLED_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '已开票金额',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  MANAGER_ID BIGINT NULL    COMMENT '项目经理(职员)',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_project primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_task(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  PARENT_TASK_ID BIGINT NULL    COMMENT '父任务',
  TITLE VARCHAR(200) NOT NULL    COMMENT '任务标题',
  ASSIGNEE_ID BIGINT NULL    COMMENT '负责人',
  PLANNED_START_DATE DATE NULL    COMMENT '计划开始日期',
  PLANNED_END_DATE DATE NULL    COMMENT '计划结束日期',
  ACTUAL_START_DATE DATE NULL    COMMENT '实际开始日期',
  ACTUAL_END_DATE DATE NULL    COMMENT '实际结束日期',
  ESTIMATED_HOURS DECIMAL(10,2) NULL    COMMENT '预估工时',
  ACTUAL_HOURS DECIMAL(10,2) NULL    COMMENT '实际工时',
  DEPENDS_ON_ID BIGINT NULL    COMMENT '依赖任务',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  PRIORITY INTEGER NULL    COMMENT '优先级',
  BLOCK_REASON VARCHAR(500) NULL    COMMENT '阻塞原因',
  SORT_NUM INTEGER NULL    COMMENT '排序号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_task primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_project_user(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  USER_ID BIGINT NOT NULL    COMMENT '用户',
  ROLE VARCHAR(50) NULL    COMMENT '角色',
  START_DATE DATE NULL    COMMENT '加入日期',
  END_DATE DATE NULL    COMMENT '退出日期',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_project_user primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_budget(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '预算日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '预算总额',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_budget primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_cost_collection(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '归集日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '归集金额合计',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(已转成本凭证)',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY BIGINT NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_prj_cost_collection primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_milestone(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '里程碑名称',
  PLANNED_DATE DATE NOT NULL    COMMENT '计划完成日期',
  ACTUAL_DATE DATE NULL    COMMENT '实际完成日期',
  BILLING_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '应结算金额',
  IS_BILLING_TRIGGER BOOLEAN default 0  NULL    COMMENT '是否触发开票节点',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_milestone primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_timesheet(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  TASK_ID BIGINT NULL    COMMENT '任务',
  USER_ID BIGINT NOT NULL    COMMENT '用户(职员)',
  WORK_DATE DATE NOT NULL    COMMENT '工作日期',
  HOURS DECIMAL(10,2) NOT NULL    COMMENT '工时',
  ACTIVITY_TYPE_ID BIGINT NULL    COMMENT '活动类型',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  COST_RATE DECIMAL(20,4) NULL    COMMENT '成本费率',
  COST_AMOUNT DECIMAL(20,4) NULL    COMMENT '成本金额',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(已转成本凭证)',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY BIGINT NULL    COMMENT '过账人',
  APPROVED_BY BIGINT NULL    COMMENT '审批人',
  APPROVED_AT DATETIME NULL    COMMENT '审批时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_timesheet primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_budget_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BUDGET_ID BIGINT NOT NULL    COMMENT '预算ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  COST_CATEGORY VARCHAR(50) NOT NULL    COMMENT '成本类别(人工/材料/费用/分包)',
  SUBJECT_ID BIGINT NULL    COMMENT '科目',
  TASK_ID BIGINT NULL    COMMENT '任务',
  PLANNED_AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '预算金额',
  COMMITTED_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '已承诺金额',
  ACTUAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '实际金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_budget_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_cost_collection_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  COST_COLLECTION_ID BIGINT NOT NULL    COMMENT '归集单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  COST_CATEGORY VARCHAR(50) NOT NULL    COMMENT '成本类别(人工/材料/费用/分包)',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型(TIMESHEET/PURCHASE/EXPENSE)',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  SUBJECT_ID BIGINT NULL    COMMENT '科目',
  TASK_ID BIGINT NULL    COMMENT '任务',
  AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_cost_collection_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_billing(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  PROJECT_ID BIGINT NOT NULL    COMMENT '项目',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  MILESTONE_ID BIGINT NULL    COMMENT '关联里程碑',
  BUSINESS_DATE DATE NOT NULL    COMMENT '开票日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '开票金额',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY BIGINT NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_prj_billing primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_billing_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BILLING_ID BIGINT NOT NULL    COMMENT '开票单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  COST_CATEGORY VARCHAR(50) NULL    COMMENT '成本类别',
  TASK_ID BIGINT NULL    COMMENT '任务',
  SUBJECT_ID BIGINT NULL    COMMENT '科目',
  AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_prj_billing_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_employee COMMENT '职员';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_subject COMMENT '会计科目';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_prj_project_type COMMENT '项目类型';
                
   ALTER TABLE erp_prj_activity_type COMMENT '活动类型';
                
   ALTER TABLE erp_prj_project COMMENT '项目';
                
   ALTER TABLE erp_prj_task COMMENT '任务';
                
   ALTER TABLE erp_prj_project_user COMMENT '项目成员';
                
   ALTER TABLE erp_prj_budget COMMENT '项目预算';
                
   ALTER TABLE erp_prj_cost_collection COMMENT '项目成本归集';
                
   ALTER TABLE erp_prj_milestone COMMENT '项目里程碑';
                
   ALTER TABLE erp_prj_timesheet COMMENT '工时记录';
                
   ALTER TABLE erp_prj_budget_line COMMENT '项目预算行';
                
   ALTER TABLE erp_prj_cost_collection_line COMMENT '项目成本归集行';
                
   ALTER TABLE erp_prj_billing COMMENT '项目开票';
                
   ALTER TABLE erp_prj_billing_line COMMENT '项目开票行';
                
