
CREATE TABLE erp_md_acct_schema(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  CURRENCY_ID NUMBER(20)  ,
  NATURE INTEGER  ,
  constraint PK_erp_md_acct_schema primary key (ID)
);

CREATE TABLE erp_md_organization(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  ORG_TYPE INTEGER  ,
  PARENT_ID NUMBER(20)  ,
  STATUS INTEGER  ,
  constraint PK_erp_md_organization primary key (ID)
);

CREATE TABLE erp_md_subject(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  PARENT_ID NUMBER(20)  ,
  SUBJECT_CLASS INTEGER  ,
  DIRECTION INTEGER  ,
  constraint PK_erp_md_subject primary key (ID)
);

CREATE TABLE erp_md_currency(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  SYMBOL VARCHAR2(50)  ,
  DECIMAL_PLACES INTEGER  ,
  IS_FUNCTIONAL CHAR(1)  ,
  constraint PK_erp_md_currency primary key (ID)
);

CREATE TABLE erp_md_partner(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  PARTNER_TYPE INTEGER  ,
  STATUS INTEGER  ,
  CREDIT_LIMIT VARCHAR2(50)  ,
  constraint PK_erp_md_partner primary key (ID)
);

CREATE TABLE erp_md_warehouse(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  WAREHOUSE_TYPE INTEGER  ,
  ORG_ID NUMBER(20)  ,
  STATUS INTEGER  ,
  constraint PK_erp_md_warehouse primary key (ID)
);

CREATE TABLE erp_md_material(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  MATERIAL_TYPE INTEGER  ,
  STATUS INTEGER  ,
  constraint PK_erp_md_material primary key (ID)
);

CREATE TABLE erp_prj_project(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  CUSTOMER_ID NUMBER(20)  ,
  STATUS INTEGER  ,
  constraint PK_erp_prj_project primary key (ID)
);

CREATE TABLE erp_md_cost_center(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  ORG_ID NUMBER(20)  ,
  constraint PK_erp_md_cost_center primary key (ID)
);

CREATE TABLE erp_md_employee(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  ORG_ID NUMBER(20)  ,
  PARTNER_ID NUMBER(20)  ,
  STATUS INTEGER  ,
  constraint PK_erp_md_employee primary key (ID)
);

CREATE TABLE erp_md_material_category(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  PARENT_ID NUMBER(20)  ,
  constraint PK_erp_md_material_category primary key (ID)
);

CREATE TABLE erp_ast_asset(
  ID NUMBER(20)  ,
  CODE VARCHAR2(50)  ,
  NAME VARCHAR2(200)  ,
  ASSET_TYPE INTEGER  ,
  STATUS INTEGER  ,
  constraint PK_erp_ast_asset primary key (ID)
);

CREATE TABLE erp_fin_voucher_template(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  NAME VARCHAR2(200) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20)  ,
  BUSINESS_TYPE VARCHAR2(30) NOT NULL ,
  VOUCHER_TYPE VARCHAR2(20)  ,
  TEMPLATE_TYPE VARCHAR2(50)  ,
  IS_ACTIVE CHAR(1) default 1   ,
  VALID_FROM DATE  ,
  VALID_TO DATE  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_voucher_template primary key (ID)
);

CREATE TABLE erp_fin_accounting_period(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  NAME VARCHAR2(200) NOT NULL ,
  ORG_ID NUMBER(20)  ,
  YEAR INTEGER NOT NULL ,
  MONTH INTEGER NOT NULL ,
  START_DATE DATE NOT NULL ,
  END_DATE DATE NOT NULL ,
  QUARTER INTEGER  ,
  IS_ADJUSTMENT CHAR(1) default 0   ,
  STATUS VARCHAR2(20) NOT NULL ,
  CLOSED_BY VARCHAR2(36)  ,
  CLOSED_AT TIMESTAMP  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_accounting_period primary key (ID)
);

CREATE TABLE erp_fin_fund_account(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  NAME VARCHAR2(200) NOT NULL ,
  ORG_ID NUMBER(20)  ,
  ACCOUNT_TYPE VARCHAR2(20) NOT NULL ,
  SUBJECT_ID NUMBER(20)  ,
  BANK_NAME VARCHAR2(200)  ,
  BANK_ACCOUNT VARCHAR2(50)  ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  OPENING_BALANCE NUMBER(20,4) default 0   ,
  CURRENT_BALANCE NUMBER(20,4) default 0   ,
  STATUS VARCHAR2(20) NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_fund_account primary key (ID)
);

CREATE TABLE erp_fin_reconciliation(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  DIRECTION VARCHAR2(20) NOT NULL ,
  PARTNER_ID NUMBER(20) NOT NULL ,
  BUSINESS_DATE DATE NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  TOTAL_AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  TOTAL_AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  FX_GAIN_LOSS NUMBER(20,4) default 0   ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_reconciliation primary key (ID)
);

CREATE TABLE erp_fin_notes_receivable(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  NOTES_TYPE VARCHAR2(30) NOT NULL ,
  NOTES_NO VARCHAR2(50)  ,
  DRAWER_NAME VARCHAR2(200)  ,
  DRAWER_BANK VARCHAR2(200)  ,
  PAYEE_NAME VARCHAR2(200)  ,
  ISSUE_DATE DATE  ,
  DUE_DATE DATE  ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  PARTNER_ID NUMBER(20)  ,
  ENDORSEMENT_FROM_ID NUMBER(20)  ,
  SOURCE_BILL_TYPE VARCHAR2(50)  ,
  SOURCE_BILL_CODE VARCHAR2(50)  ,
  DISCOUNT_ID NUMBER(20)  ,
  STATUS VARCHAR2(20)  ,
  POSTED CHAR(1) default 0   ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_notes_receivable primary key (ID)
);

CREATE TABLE erp_fin_employee_advance(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  EMPLOYEE_ID NUMBER(20) NOT NULL ,
  ADVANCE_TYPE VARCHAR2(20) NOT NULL ,
  BUSINESS_DATE DATE NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  SETTLED_AMOUNT NUMBER(20,4) default 0   ,
  OUTSTANDING_AMOUNT NUMBER(20,4) default 0   ,
  PROJECT_ID NUMBER(20)  ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  APPROVE_STATUS VARCHAR2(20) NOT NULL ,
  APPROVED_BY VARCHAR2(36)  ,
  APPROVED_AT TIMESTAMP  ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED CHAR(1) default 0   ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_employee_advance primary key (ID)
);

CREATE TABLE erp_fin_gl_mapping_rule(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  NAME VARCHAR2(200) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  BUSINESS_TYPE VARCHAR2(30) NOT NULL ,
  ACCOUNT_KEY VARCHAR2(50) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20)  ,
  PARTNER_GROUP_ID NUMBER(20)  ,
  MATERIAL_CATEGORY_ID NUMBER(20)  ,
  WAREHOUSE_ID NUMBER(20)  ,
  DEPARTMENT_ID NUMBER(20)  ,
  PROJECT_ID NUMBER(20)  ,
  TARGET_SUBJECT_CODE VARCHAR2(50) NOT NULL ,
  PRIORITY INTEGER default 0  NOT NULL ,
  IS_ACTIVE CHAR(1) default 1  NOT NULL ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  constraint PK_erp_fin_gl_mapping_rule primary key (ID)
);

CREATE TABLE erp_fin_voucher_template_line(
  ID NUMBER(20) NOT NULL ,
  TEMPLATE_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  SUBJECT_CODE VARCHAR2(50) NOT NULL ,
  DC_DIRECTION VARCHAR2(20) NOT NULL ,
  AMOUNT_EXPRESSION VARCHAR2(200)  ,
  ACCOUNT_KEY VARCHAR2(50)  ,
  AMOUNT_KEY VARCHAR2(50)  ,
  MEMO_TEMPLATE VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_voucher_template_line primary key (ID)
);

CREATE TABLE erp_fin_voucher(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  VOUCHER_TYPE VARCHAR2(20) NOT NULL ,
  POSTING_TYPE VARCHAR2(20)  ,
  VOUCHER_DATE DATE NOT NULL ,
  VOUCHER_NO VARCHAR2(50)  ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  PERIOD_ID NUMBER(20) NOT NULL ,
  TOTAL_DEBIT NUMBER(20,4) default 0   ,
  TOTAL_CREDIT NUMBER(20,4) default 0   ,
  IS_REVERSED CHAR(1) default 0   ,
  REVERSAL_OF_VOUCHER_ID NUMBER(20)  ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_voucher primary key (ID)
);

CREATE TABLE erp_fin_accounting_period_status(
  ID NUMBER(20) NOT NULL ,
  PERIOD_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  TOTAL_VOUCHERS INTEGER default 0   ,
  POSTED_VOUCHERS INTEGER default 0   ,
  UNPOSTED_VOUCHERS INTEGER default 0   ,
  AR_STATUS VARCHAR2(20) NOT NULL ,
  AP_STATUS VARCHAR2(20) NOT NULL ,
  INV_STATUS VARCHAR2(20) NOT NULL ,
  GL_STATUS VARCHAR2(20) NOT NULL ,
  ASSET_STATUS VARCHAR2(20) NOT NULL ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_accounting_period_status primary key (ID)
);

CREATE TABLE erp_fin_ar_ap_item(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  DIRECTION VARCHAR2(20) NOT NULL ,
  PARTNER_ID NUMBER(20) NOT NULL ,
  SOURCE_BILL_TYPE VARCHAR2(50) NOT NULL ,
  SOURCE_BILL_CODE VARCHAR2(50) NOT NULL ,
  BUSINESS_DATE DATE NOT NULL ,
  DUE_DATE DATE  ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) NOT NULL ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) NOT NULL ,
  SETTLED_AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  SETTLED_AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  OPEN_AMOUNT_SOURCE NUMBER(20,4) NOT NULL ,
  OPEN_AMOUNT_FUNCTIONAL NUMBER(20,4) NOT NULL ,
  STATUS VARCHAR2(20) NOT NULL ,
  PERIOD_ID NUMBER(20)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_ar_ap_item primary key (ID)
);

CREATE TABLE erp_fin_gl_balance(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  PERIOD_ID NUMBER(20) NOT NULL ,
  SUBJECT_ID NUMBER(20) NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  OPENING_DEBIT NUMBER(20,4) default 0   ,
  OPENING_CREDIT NUMBER(20,4) default 0   ,
  PERIOD_DEBIT NUMBER(20,4) default 0   ,
  PERIOD_CREDIT NUMBER(20,4) default 0   ,
  CLOSING_DEBIT NUMBER(20,4) default 0   ,
  CLOSING_CREDIT NUMBER(20,4) default 0   ,
  YEAR_OPENING_DEBIT NUMBER(20,4) default 0   ,
  YEAR_OPENING_CREDIT NUMBER(20,4) default 0   ,
  PARTNER_ID NUMBER(20)  ,
  DEPARTMENT_ID NUMBER(20)  ,
  PROJECT_ID NUMBER(20)  ,
  WAREHOUSE_ID NUMBER(20)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_gl_balance primary key (ID)
);

CREATE TABLE erp_fin_trial_balance(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  PERIOD_ID NUMBER(20) NOT NULL ,
  SUBJECT_ID NUMBER(20) NOT NULL ,
  SUBJECT_CODE VARCHAR2(50) NOT NULL ,
  SUBJECT_NAME VARCHAR2(200)  ,
  OPENING_DEBIT NUMBER(20,4) default 0   ,
  OPENING_CREDIT NUMBER(20,4) default 0   ,
  PERIOD_DEBIT NUMBER(20,4) default 0   ,
  PERIOD_CREDIT NUMBER(20,4) default 0   ,
  CLOSING_DEBIT NUMBER(20,4) default 0   ,
  CLOSING_CREDIT NUMBER(20,4) default 0   ,
  GENERATED_AT TIMESTAMP NOT NULL ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_trial_balance primary key (ID)
);

CREATE TABLE erp_fin_bank_statement(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  FUND_ACCOUNT_ID NUMBER(20) NOT NULL ,
  STATEMENT_DATE DATE NOT NULL ,
  BEGINNING_BALANCE NUMBER(20,4) default 0   ,
  ENDING_BALANCE NUMBER(20,4) default 0   ,
  TOTAL_DEBIT NUMBER(20,4) default 0   ,
  TOTAL_CREDIT NUMBER(20,4) default 0   ,
  IMPORT_TIME TIMESTAMP  ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_bank_statement primary key (ID)
);

CREATE TABLE erp_fin_credit_facility(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  FUND_ACCOUNT_ID NUMBER(20)  ,
  FACILITY_TYPE VARCHAR2(20) NOT NULL ,
  TOTAL_AMOUNT NUMBER(20,4) default 0   ,
  USED_AMOUNT NUMBER(20,4) default 0   ,
  AVAILABLE_AMOUNT NUMBER(20,4) default 0   ,
  VALID_FROM DATE  ,
  VALID_TO DATE  ,
  STATUS VARCHAR2(20)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_credit_facility primary key (ID)
);

CREATE TABLE erp_fin_cash_forecast(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20)  ,
  FUND_ACCOUNT_ID NUMBER(20)  ,
  FORECAST_DATE DATE NOT NULL ,
  SOURCE_BILL_TYPE VARCHAR2(50)  ,
  SOURCE_BILL_CODE VARCHAR2(50)  ,
  DIRECTION VARCHAR2(20)  ,
  PARTNER_ID NUMBER(20)  ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_cash_forecast primary key (ID)
);

CREATE TABLE erp_fin_notes_discount(
  ID NUMBER(20) NOT NULL ,
  NOTES_RECEIVABLE_ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  DISCOUNT_DATE DATE NOT NULL ,
  BANK_ID NUMBER(20)  ,
  FACE_AMOUNT NUMBER(20,4) default 0   ,
  DISCOUNT_INTEREST NUMBER(20,4) default 0   ,
  NET_AMOUNT NUMBER(20,4) default 0   ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  EXCHANGE_GAIN_LOSS NUMBER(20,4) default 0   ,
  POSTED CHAR(1) default 0   ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_notes_discount primary key (ID)
);

CREATE TABLE erp_fin_expense_claim(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  CLAIMANT_ID NUMBER(20) NOT NULL ,
  DEPARTMENT_ID NUMBER(20)  ,
  BUSINESS_DATE DATE NOT NULL ,
  PAYMENT_MODE VARCHAR2(20) NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  AMOUNT_WITHOUT_TAX NUMBER(20,4) default 0   ,
  TAX_AMOUNT NUMBER(20,4) default 0   ,
  AMOUNT_WITH_TAX NUMBER(20,4) default 0   ,
  SETTLE_ADVANCE_ID NUMBER(20)  ,
  REASON VARCHAR2(1000)  ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  APPROVE_STATUS VARCHAR2(20) NOT NULL ,
  APPROVED_BY VARCHAR2(36)  ,
  APPROVED_AT TIMESTAMP  ,
  POSTED CHAR(1) default 0   ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_expense_claim primary key (ID)
);

CREATE TABLE erp_fin_voucher_line(
  ID NUMBER(20) NOT NULL ,
  VOUCHER_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  SUBJECT_ID NUMBER(20) NOT NULL ,
  SUBJECT_CODE VARCHAR2(50) NOT NULL ,
  SUBJECT_NAME VARCHAR2(200)  ,
  DC_DIRECTION VARCHAR2(20) NOT NULL ,
  DEBIT_AMOUNT NUMBER(20,4) default 0   ,
  CREDIT_AMOUNT NUMBER(20,4) default 0   ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4)  ,
  AMOUNT_FUNCTIONAL NUMBER(20,4)  ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20)  ,
  MEMO VARCHAR2(1000)  ,
  PARTNER_ID NUMBER(20)  ,
  DEPARTMENT_ID NUMBER(20)  ,
  PROJECT_ID NUMBER(20)  ,
  WAREHOUSE_ID NUMBER(20)  ,
  MATERIAL_ID NUMBER(20)  ,
  BUSINESS_TYPE VARCHAR2(30)  ,
  COST_CENTER_ID NUMBER(20)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_voucher_line primary key (ID)
);

CREATE TABLE erp_fin_voucher_bill_r(
  ID NUMBER(20) NOT NULL ,
  VOUCHER_ID NUMBER(20) NOT NULL ,
  BILL_TYPE VARCHAR2(50) NOT NULL ,
  BILL_CODE VARCHAR2(50) NOT NULL ,
  BILL_LINE_CODE VARCHAR2(50)  ,
  BUSINESS_TYPE VARCHAR2(30)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_voucher_bill_r primary key (ID)
);

CREATE TABLE erp_fin_posting_exception(
  ID NUMBER(20) NOT NULL ,
  TRACE_ID VARCHAR2(50)  ,
  BILL_HEAD_CODE VARCHAR2(50)  ,
  BUSINESS_TYPE VARCHAR2(30)  ,
  POSTING_TYPE VARCHAR2(20)  ,
  ERROR_CODE VARCHAR2(100) NOT NULL ,
  ERROR_MESSAGE VARCHAR2(500)  ,
  FAILED_STAGE VARCHAR2(50)  ,
  VOUCHER_DATE DATE  ,
  ORG_ID NUMBER(20)  ,
  ACCT_SCHEMA_ID NUMBER(20)  ,
  STATUS VARCHAR2(20) NOT NULL ,
  RETRY_COUNT INTEGER default 0   ,
  RESOLUTION VARCHAR2(20)  ,
  RESOLUTION_NOTE VARCHAR2(500)  ,
  RESOLVED_BY VARCHAR2(36)  ,
  RESOLVED_AT TIMESTAMP  ,
  VOUCHER_ID NUMBER(20)  ,
  OCCURRENCE_TIME TIMESTAMP NOT NULL ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  CURRENCY_ID NUMBER(20)  ,
  EXCHANGE_RATE NUMBER(20,8)  ,
  EVENT_DATA VARCHAR2(4000)  ,
  constraint PK_erp_fin_posting_exception primary key (ID)
);

CREATE TABLE erp_fin_budget_scenario(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  NAME VARCHAR2(200) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  FISCAL_YEAR INTEGER NOT NULL ,
  SCENARIO_TYPE VARCHAR2(20) NOT NULL ,
  PARENT_SCENARIO_ID NUMBER(20)  ,
  VALID_FROM DATE  ,
  VALID_TO DATE  ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  CONTROL_LEVEL VARCHAR2(20) default 'NONE'  NOT NULL ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  APPROVE_STATUS VARCHAR2(20) NOT NULL ,
  VOUCHER_ID NUMBER(20)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  BUDGET_GROUP_CODE VARCHAR2(50)  ,
  CARRY_FORWARD_RULE VARCHAR2(20)  ,
  ROLL_FORWARD_STRATEGY VARCHAR2(20)  ,
  CLOSED_AT TIMESTAMP  ,
  constraint PK_erp_fin_budget_scenario primary key (ID)
);

CREATE TABLE erp_fin_reconciliation_line(
  ID NUMBER(20) NOT NULL ,
  RECONCILIATION_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  PAYMENT_ITEM_ID NUMBER(20) NOT NULL ,
  INVOICE_ITEM_ID NUMBER(20) NOT NULL ,
  SETTLED_AMOUNT_SOURCE NUMBER(20,4) NOT NULL ,
  SETTLED_AMOUNT_FUNCTIONAL NUMBER(20,4) NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_reconciliation_line primary key (ID)
);

CREATE TABLE erp_fin_bad_debt(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  DOC_TYPE VARCHAR2(20) NOT NULL ,
  PARTNER_ID NUMBER(20) NOT NULL ,
  SOURCE_AR_AP_ITEM_ID NUMBER(20) NOT NULL ,
  AMOUNT NUMBER(20,4) NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  BUSINESS_DATE DATE NOT NULL ,
  REASON VARCHAR2(500)  ,
  APPROVAL_STATUS VARCHAR2(20) NOT NULL ,
  PERIOD_ID NUMBER(20)  ,
  VOUCHER_ID NUMBER(20)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_bad_debt primary key (ID)
);

CREATE TABLE erp_fin_bank_reconciliation(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  FUND_ACCOUNT_ID NUMBER(20) NOT NULL ,
  STATEMENT_ID NUMBER(20)  ,
  RECONCILIATION_DATE DATE NOT NULL ,
  BOOK_BALANCE NUMBER(20,4) NOT NULL ,
  STATEMENT_BALANCE NUMBER(20,4) NOT NULL ,
  UNRECONCILED_DIFF NUMBER(20,4) default 0   ,
  IS_BALANCED CHAR(1) default 0   ,
  RECONCILED_AT TIMESTAMP  ,
  RECONCILED_BY NUMBER(20)  ,
  DOC_STATUS VARCHAR2(20) NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_bank_reconciliation primary key (ID)
);

CREATE TABLE erp_fin_notes_payable(
  ID NUMBER(20) NOT NULL ,
  CODE VARCHAR2(50) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  NOTES_TYPE VARCHAR2(30) NOT NULL ,
  NOTES_NO VARCHAR2(50)  ,
  PAYEE_NAME VARCHAR2(200)  ,
  PAYEE_BANK VARCHAR2(200)  ,
  ISSUE_DATE DATE  ,
  DUE_DATE DATE  ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  PARTNER_ID NUMBER(20)  ,
  CREDIT_FACILITY_ID NUMBER(20)  ,
  SOURCE_BILL_TYPE VARCHAR2(50)  ,
  SOURCE_BILL_CODE VARCHAR2(50)  ,
  STATUS VARCHAR2(20)  ,
  POSTED CHAR(1) default 0   ,
  POSTED_BY VARCHAR2(36)  ,
  POSTED_AT TIMESTAMP  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_notes_payable primary key (ID)
);

CREATE TABLE erp_fin_expense_claim_line(
  ID NUMBER(20) NOT NULL ,
  CLAIM_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  EXPENSE_TYPE VARCHAR2(20) NOT NULL ,
  PROJECT_ID NUMBER(20)  ,
  COST_CENTER_ID NUMBER(20)  ,
  SUBJECT_ID NUMBER(20)  ,
  SUBJECT_CODE VARCHAR2(50)  ,
  AMOUNT_WITHOUT_TAX NUMBER(20,4) default 0   ,
  TAX_RATE NUMBER(20,8)  ,
  TAX_AMOUNT NUMBER(20,4) default 0   ,
  AMOUNT_WITH_TAX NUMBER(20,4) default 0   ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_expense_claim_line primary key (ID)
);

CREATE TABLE erp_fin_bank_statement_line(
  ID NUMBER(20) NOT NULL ,
  STATEMENT_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  TRANSACTION_DATE DATE NOT NULL ,
  DESCRIPTION VARCHAR2(1000)  ,
  REF_NO VARCHAR2(50)  ,
  DC_DIRECTION VARCHAR2(20) NOT NULL ,
  AMOUNT NUMBER(20,4) NOT NULL ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  BALANCE_AFTER NUMBER(20,4)  ,
  MATCH_STATUS VARCHAR2(20) NOT NULL ,
  MATCHED_LINE_ID NUMBER(20)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_bank_statement_line primary key (ID)
);

CREATE TABLE erp_fin_budget_line(
  ID NUMBER(20) NOT NULL ,
  SCENARIO_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  ACCT_SCHEMA_ID NUMBER(20) NOT NULL ,
  PERIOD_ID NUMBER(20)  ,
  SUBJECT_ID NUMBER(20) NOT NULL ,
  SUBJECT_CODE VARCHAR2(50) NOT NULL ,
  COST_CENTER_ID NUMBER(20)  ,
  DEPARTMENT_ID NUMBER(20)  ,
  PROJECT_ID NUMBER(20)  ,
  PARTNER_ID NUMBER(20)  ,
  WAREHOUSE_ID NUMBER(20)  ,
  MATERIAL_ID NUMBER(20)  ,
  BUDGET_AMOUNT_SOURCE NUMBER(20,4) default 0   ,
  BUDGET_AMOUNT_FUNCTIONAL NUMBER(20,4) default 0   ,
  CURRENCY_ID NUMBER(20) NOT NULL ,
  EXCHANGE_RATE NUMBER(20,8) default 1   ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_budget_line primary key (ID)
);

CREATE TABLE erp_fin_budget_rollforward_log(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  SCENARIO_ID NUMBER(20) NOT NULL ,
  SOURCE_SCENARIO_ID NUMBER(20) NOT NULL ,
  TARGET_SCENARIO_ID NUMBER(20) NOT NULL ,
  STRATEGY VARCHAR2(20) NOT NULL ,
  NEW_FISCAL_YEAR INTEGER NOT NULL ,
  SOURCE_AMOUNT NUMBER(20,4) default 0   ,
  TARGET_AMOUNT NUMBER(20,4) default 0   ,
  ROLLED_AT TIMESTAMP NOT NULL ,
  ROLLED_BY VARCHAR2(36)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_budget_rollforward_log primary key (ID)
);

CREATE TABLE erp_fin_budget_carry_forward_log(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  SCENARIO_ID NUMBER(20) NOT NULL ,
  SOURCE_SCENARIO_ID NUMBER(20) NOT NULL ,
  TARGET_SCENARIO_ID NUMBER(20) NOT NULL ,
  RULE VARCHAR2(20) NOT NULL ,
  SOURCE_REMAINING NUMBER(20,4) default 0   ,
  SOURCE_USED NUMBER(20,4) default 0   ,
  CARRIED_AMOUNT NUMBER(20,4) default 0   ,
  CARRIED_AT TIMESTAMP NOT NULL ,
  CARRIED_BY VARCHAR2(36)  ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_budget_carry_forward_log primary key (ID)
);

CREATE TABLE erp_fin_bank_reconciliation_line(
  ID NUMBER(20) NOT NULL ,
  RECONCILIATION_ID NUMBER(20) NOT NULL ,
  LINE_NO INTEGER NOT NULL ,
  ADJUSTMENT_TYPE VARCHAR2(50) NOT NULL ,
  DESCRIPTION VARCHAR2(1000)  ,
  DC_DIRECTION VARCHAR2(20) NOT NULL ,
  AMOUNT NUMBER(20,4) NOT NULL ,
  SIDE VARCHAR2(20) NOT NULL ,
  REMARK VARCHAR2(1000)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_bank_reconciliation_line primary key (ID)
);

CREATE TABLE erp_fin_budget_control_log(
  ID NUMBER(20) NOT NULL ,
  ORG_ID NUMBER(20) NOT NULL ,
  BUSINESS_DATE DATE NOT NULL ,
  SCENARIO_ID NUMBER(20)  ,
  BUDGET_LINE_ID NUMBER(20)  ,
  SOURCE_BILL_TYPE VARCHAR2(50) NOT NULL ,
  SOURCE_BILL_CODE VARCHAR2(50) NOT NULL ,
  SUBJECT_ID NUMBER(20)  ,
  COST_CENTER_ID NUMBER(20)  ,
  PROJECT_ID NUMBER(20)  ,
  PERIOD_ID NUMBER(20)  ,
  REQUESTED_AMOUNT NUMBER(20,4) NOT NULL ,
  COMMITTED_AMOUNT NUMBER(20,4) default 0   ,
  AVAILABLE_AMOUNT NUMBER(20,4)  ,
  ACTION_RESULT VARCHAR2(20) NOT NULL ,
  OPERATOR_ID VARCHAR2(36)  ,
  OPERATED_AT TIMESTAMP  ,
  REASON VARCHAR2(500)  ,
  DEL_VERSION NUMBER(20) default 0  NOT NULL ,
  VERSION INTEGER default 0  NOT NULL ,
  CREATED_BY VARCHAR2(50) NOT NULL ,
  CREATE_TIME TIMESTAMP NOT NULL ,
  UPDATED_BY VARCHAR2(50) NOT NULL ,
  UPDATE_TIME TIMESTAMP NOT NULL ,
  constraint PK_erp_fin_budget_control_log primary key (ID)
);


      COMMENT ON TABLE erp_md_acct_schema IS '会计核算表(账套)';
                
      COMMENT ON TABLE erp_md_organization IS '组织';
                
      COMMENT ON TABLE erp_md_subject IS '会计科目';
                
      COMMENT ON TABLE erp_md_currency IS '币种';
                
      COMMENT ON TABLE erp_md_partner IS '往来单位';
                
      COMMENT ON TABLE erp_md_warehouse IS '仓库';
                
      COMMENT ON TABLE erp_md_material IS '物料';
                
      COMMENT ON TABLE erp_prj_project IS '项目';
                
      COMMENT ON TABLE erp_md_cost_center IS '成本中心';
                
      COMMENT ON TABLE erp_md_employee IS '职员';
                
      COMMENT ON TABLE erp_md_material_category IS '物料分类';
                
      COMMENT ON TABLE erp_ast_asset IS '固定资产';
                
      COMMENT ON TABLE erp_fin_voucher_template IS '凭证模板';
                
      COMMENT ON COLUMN erp_fin_voucher_template.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.CODE IS '模板编码';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.NAME IS '模板名称';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.ACCT_SCHEMA_ID IS '账套(空表示所有账套通用)';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.BUSINESS_TYPE IS '业务类型';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.VOUCHER_TYPE IS '凭证字';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.TEMPLATE_TYPE IS '模板类型';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.IS_ACTIVE IS '是否启用';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.VALID_FROM IS '生效日期';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.VALID_TO IS '失效日期';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_voucher_template.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_accounting_period IS '会计期间';
                
      COMMENT ON COLUMN erp_fin_accounting_period.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.CODE IS '期间编码';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.NAME IS '期间名称';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.YEAR IS '年度';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.MONTH IS '月份';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.START_DATE IS '开始日期';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.END_DATE IS '结束日期';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.QUARTER IS '季度';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.IS_ADJUSTMENT IS '是否调整期';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.STATUS IS '期间状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.CLOSED_BY IS '结账人';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.CLOSED_AT IS '结账时间';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_accounting_period.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_fund_account IS '资金账户';
                
      COMMENT ON COLUMN erp_fin_fund_account.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_fund_account.CODE IS '账户编码';
                    
      COMMENT ON COLUMN erp_fin_fund_account.NAME IS '账户名称';
                    
      COMMENT ON COLUMN erp_fin_fund_account.ORG_ID IS '所属组织';
                    
      COMMENT ON COLUMN erp_fin_fund_account.ACCOUNT_TYPE IS '账户类型';
                    
      COMMENT ON COLUMN erp_fin_fund_account.SUBJECT_ID IS '对应会计科目';
                    
      COMMENT ON COLUMN erp_fin_fund_account.BANK_NAME IS '开户银行';
                    
      COMMENT ON COLUMN erp_fin_fund_account.BANK_ACCOUNT IS '银行账号';
                    
      COMMENT ON COLUMN erp_fin_fund_account.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_fund_account.OPENING_BALANCE IS '期初余额';
                    
      COMMENT ON COLUMN erp_fin_fund_account.CURRENT_BALANCE IS '当前余额';
                    
      COMMENT ON COLUMN erp_fin_fund_account.STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_fund_account.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_fund_account.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_fund_account.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_fund_account.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_fund_account.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_fund_account.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_fund_account.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_reconciliation IS '核销单';
                
      COMMENT ON COLUMN erp_fin_reconciliation.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.DIRECTION IS '应收应付';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.PARTNER_ID IS '往来单位';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.BUSINESS_DATE IS '业务日期';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.TOTAL_AMOUNT_SOURCE IS '核销总额(源币)';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.TOTAL_AMOUNT_FUNCTIONAL IS '核销总额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.FX_GAIN_LOSS IS '汇兑损益';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.DOC_STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_reconciliation.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_notes_receivable IS '应收票据';
                
      COMMENT ON COLUMN erp_fin_notes_receivable.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.NOTES_TYPE IS '票据类型';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.NOTES_NO IS '票据号';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.DRAWER_NAME IS '出票人';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.DRAWER_BANK IS '出票行';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.PAYEE_NAME IS '收款人';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.ISSUE_DATE IS '出票日';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.DUE_DATE IS '到期日';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.AMOUNT_SOURCE IS '源币种票面金额';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.AMOUNT_FUNCTIONAL IS '本位币票面金额';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.PARTNER_ID IS '出票客户往来';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.ENDORSEMENT_FROM_ID IS '背书来源票据';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.SOURCE_BILL_TYPE IS '来源单据类型';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.SOURCE_BILL_CODE IS '来源单据号';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.DISCOUNT_ID IS '贴现明细';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.STATUS IS '票据状态';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.POSTED IS '是否已过账';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_notes_receivable.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_employee_advance IS '员工借款单';
                
      COMMENT ON COLUMN erp_fin_employee_advance.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.EMPLOYEE_ID IS '借款人';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.ADVANCE_TYPE IS '借款类型';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.BUSINESS_DATE IS '借款日期';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.AMOUNT_SOURCE IS '源币种金额';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.AMOUNT_FUNCTIONAL IS '本位币金额';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.SETTLED_AMOUNT IS '已清算金额';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.OUTSTANDING_AMOUNT IS '未还金额';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.PROJECT_ID IS '关联项目';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.DOC_STATUS IS '单据状态';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.APPROVE_STATUS IS '审核状态';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.APPROVED_BY IS '审核人';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.APPROVED_AT IS '审核时间';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.POSTED IS '是否已过账';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_employee_advance.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_gl_mapping_rule IS '科目映射规则';
                
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.CODE IS '规则编码';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.NAME IS '规则名称';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.BUSINESS_TYPE IS '业务类型';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.ACCOUNT_KEY IS '科目映射键';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.ACCT_SCHEMA_ID IS '账套(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.PARTNER_GROUP_ID IS '往来单位组(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.MATERIAL_CATEGORY_ID IS '物料分类(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.WAREHOUSE_ID IS '仓库(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.DEPARTMENT_ID IS '部门(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.PROJECT_ID IS '项目(空=通配)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.TARGET_SUBJECT_CODE IS '目标科目编码';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.PRIORITY IS '优先级(0=最低default;越大越高)';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.IS_ACTIVE IS '是否启用';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON COLUMN erp_fin_gl_mapping_rule.REMARK IS '备注';
                    
      COMMENT ON TABLE erp_fin_voucher_template_line IS '凭证模板行';
                
      COMMENT ON COLUMN erp_fin_voucher_template_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.TEMPLATE_ID IS '模板ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.SUBJECT_CODE IS '科目编码(可含占位符)';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.DC_DIRECTION IS '借贷方向';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.AMOUNT_EXPRESSION IS '金额表达式';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.ACCOUNT_KEY IS '科目映射键';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.AMOUNT_KEY IS '金额占位键';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.MEMO_TEMPLATE IS '摘要模板';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_voucher_template_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_voucher IS '会计凭证';
                
      COMMENT ON COLUMN erp_fin_voucher.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_voucher.CODE IS '凭证号';
                    
      COMMENT ON COLUMN erp_fin_voucher.VOUCHER_TYPE IS '凭证字';
                    
      COMMENT ON COLUMN erp_fin_voucher.POSTING_TYPE IS '过账类型';
                    
      COMMENT ON COLUMN erp_fin_voucher.VOUCHER_DATE IS '凭证日期';
                    
      COMMENT ON COLUMN erp_fin_voucher.VOUCHER_NO IS '凭证编号';
                    
      COMMENT ON COLUMN erp_fin_voucher.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_voucher.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_voucher.PERIOD_ID IS '会计期间';
                    
      COMMENT ON COLUMN erp_fin_voucher.TOTAL_DEBIT IS '借方合计(本位币)';
                    
      COMMENT ON COLUMN erp_fin_voucher.TOTAL_CREDIT IS '贷方合计(本位币)';
                    
      COMMENT ON COLUMN erp_fin_voucher.IS_REVERSED IS '是否红字冲销凭证';
                    
      COMMENT ON COLUMN erp_fin_voucher.REVERSAL_OF_VOUCHER_ID IS '原冲销凭证ID';
                    
      COMMENT ON COLUMN erp_fin_voucher.DOC_STATUS IS '凭证状态';
                    
      COMMENT ON COLUMN erp_fin_voucher.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_voucher.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_voucher.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_voucher.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_voucher.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_voucher.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_voucher.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_voucher.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_voucher.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_accounting_period_status IS '期间结账状态';
                
      COMMENT ON COLUMN erp_fin_accounting_period_status.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.PERIOD_ID IS '期间ID';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.TOTAL_VOUCHERS IS '凭证总数';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.POSTED_VOUCHERS IS '已过账凭证数';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.UNPOSTED_VOUCHERS IS '未过账凭证数';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.AR_STATUS IS '应收模块状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.AP_STATUS IS '应付模块状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.INV_STATUS IS '存货模块状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.GL_STATUS IS '总账模块状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.ASSET_STATUS IS '资产模块状态';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_accounting_period_status.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_ar_ap_item IS '应收应付明细账';
                
      COMMENT ON COLUMN erp_fin_ar_ap_item.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.DIRECTION IS '应收应付';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.PARTNER_ID IS '往来单位';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.SOURCE_BILL_TYPE IS '来源单据类型(AP_INVOICE/AR_INVOICE/PAYMENT/RECEIPT)';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.SOURCE_BILL_CODE IS '来源单据号';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.BUSINESS_DATE IS '业务日期';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.DUE_DATE IS '到期日';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.AMOUNT_SOURCE IS '源币种金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.AMOUNT_FUNCTIONAL IS '本位币金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.SETTLED_AMOUNT_SOURCE IS '已核销源币金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.SETTLED_AMOUNT_FUNCTIONAL IS '已核销本位币金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.OPEN_AMOUNT_SOURCE IS '未核销源币金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.OPEN_AMOUNT_FUNCTIONAL IS '未核销本位币金额';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.PERIOD_ID IS '所属期间';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_ar_ap_item.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_gl_balance IS '总账余额';
                
      COMMENT ON COLUMN erp_fin_gl_balance.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.PERIOD_ID IS '期间';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.SUBJECT_ID IS '科目';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.OPENING_DEBIT IS '期初借方(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.OPENING_CREDIT IS '期初贷方(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.PERIOD_DEBIT IS '本期借方发生(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.PERIOD_CREDIT IS '本期贷方发生(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.CLOSING_DEBIT IS '期末借方(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.CLOSING_CREDIT IS '期末贷方(本位币)';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.YEAR_OPENING_DEBIT IS '年初借方';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.YEAR_OPENING_CREDIT IS '年初贷方';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.PARTNER_ID IS '辅助-往来单位';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.DEPARTMENT_ID IS '辅助-部门';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.PROJECT_ID IS '辅助-项目';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.WAREHOUSE_ID IS '辅助-仓库';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_gl_balance.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_trial_balance IS '试算平衡表';
                
      COMMENT ON COLUMN erp_fin_trial_balance.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.PERIOD_ID IS '期间';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.SUBJECT_ID IS '科目';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.SUBJECT_CODE IS '科目编码';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.SUBJECT_NAME IS '科目名称';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.OPENING_DEBIT IS '期初借方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.OPENING_CREDIT IS '期初贷方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.PERIOD_DEBIT IS '本期借方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.PERIOD_CREDIT IS '本期贷方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.CLOSING_DEBIT IS '期末借方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.CLOSING_CREDIT IS '期末贷方';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.GENERATED_AT IS '生成时间';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_trial_balance.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_bank_statement IS '银行对账单';
                
      COMMENT ON COLUMN erp_fin_bank_statement.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.FUND_ACCOUNT_ID IS '资金账户';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.STATEMENT_DATE IS '对账日期';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.BEGINNING_BALANCE IS '期初余额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.ENDING_BALANCE IS '期末余额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.TOTAL_DEBIT IS '借方发生额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.TOTAL_CREDIT IS '贷方发生额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.IMPORT_TIME IS '导入时间';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.DOC_STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_bank_statement.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_credit_facility IS '银行授信额度';
                
      COMMENT ON COLUMN erp_fin_credit_facility.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.FUND_ACCOUNT_ID IS '授信银行账户';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.FACILITY_TYPE IS '授信类型';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.TOTAL_AMOUNT IS '授信总额';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.USED_AMOUNT IS '已用额度';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.AVAILABLE_AMOUNT IS '可用额度';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.VALID_FROM IS '生效日';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.VALID_TO IS '到期日';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_credit_facility.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_cash_forecast IS '现金预测';
                
      COMMENT ON COLUMN erp_fin_cash_forecast.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.FUND_ACCOUNT_ID IS '资金账户';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.FORECAST_DATE IS '预测日期';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.SOURCE_BILL_TYPE IS '来源单据类型';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.SOURCE_BILL_CODE IS '来源单据号';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.DIRECTION IS '现金流方向';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.PARTNER_ID IS '往来单位';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.AMOUNT_SOURCE IS '源币种金额';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.AMOUNT_FUNCTIONAL IS '本位币金额';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_cash_forecast.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_notes_discount IS '票据贴现明细';
                
      COMMENT ON COLUMN erp_fin_notes_discount.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.NOTES_RECEIVABLE_ID IS '应收票据';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.DISCOUNT_DATE IS '贴现日';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.BANK_ID IS '贴现银行账户';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.FACE_AMOUNT IS '票面金额';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.DISCOUNT_INTEREST IS '贴现息';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.NET_AMOUNT IS '实得金额';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.EXCHANGE_GAIN_LOSS IS '汇兑损益';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.POSTED IS '是否已过账';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_notes_discount.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_expense_claim IS '费用报销单';
                
      COMMENT ON COLUMN erp_fin_expense_claim.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.CLAIMANT_ID IS '报销人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.DEPARTMENT_ID IS '部门';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.BUSINESS_DATE IS '业务日期';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.PAYMENT_MODE IS '付款方式';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.AMOUNT_SOURCE IS '源币种金额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.AMOUNT_FUNCTIONAL IS '本位币金额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.AMOUNT_WITHOUT_TAX IS '不含税金额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.TAX_AMOUNT IS '税额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.AMOUNT_WITH_TAX IS '价税合计';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.SETTLE_ADVANCE_ID IS '抵扣借款单';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.REASON IS '报销事由';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.DOC_STATUS IS '单据状态';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.APPROVE_STATUS IS '审核状态';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.APPROVED_BY IS '审核人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.APPROVED_AT IS '审核时间';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.POSTED IS '是否已过账';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_voucher_line IS '凭证分录行';
                
      COMMENT ON COLUMN erp_fin_voucher_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.VOUCHER_ID IS '凭证ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.SUBJECT_ID IS '科目ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.SUBJECT_CODE IS '科目编码';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.SUBJECT_NAME IS '科目名称';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.DC_DIRECTION IS '借贷方向';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.DEBIT_AMOUNT IS '借方金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.CREDIT_AMOUNT IS '贷方金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.AMOUNT_SOURCE IS '源币种金额';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.AMOUNT_FUNCTIONAL IS '本位币金额';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.MEMO IS '摘要';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.PARTNER_ID IS '辅助-往来单位';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.DEPARTMENT_ID IS '辅助-部门';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.PROJECT_ID IS '辅助-项目';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.WAREHOUSE_ID IS '辅助-仓库';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.MATERIAL_ID IS '辅助-物料';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.BUSINESS_TYPE IS '业务类型';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.COST_CENTER_ID IS '成本中心';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_voucher_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_voucher_bill_r IS '业财回链';
                
      COMMENT ON COLUMN erp_fin_voucher_bill_r.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.VOUCHER_ID IS '凭证ID';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.BILL_TYPE IS '单据类型';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.BILL_CODE IS '单据编号';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.BILL_LINE_CODE IS '单据行号';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.BUSINESS_TYPE IS '业务类型';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_voucher_bill_r.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_posting_exception IS '过账异常记录';
                
      COMMENT ON COLUMN erp_fin_posting_exception.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.TRACE_ID IS '追踪ID';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.BILL_HEAD_CODE IS '单据编号';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.BUSINESS_TYPE IS '业务类型';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.POSTING_TYPE IS '过账类型';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.ERROR_CODE IS '错误码';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.ERROR_MESSAGE IS '错误信息';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.FAILED_STAGE IS '失败阶段';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.VOUCHER_DATE IS '凭证日期';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.STATUS IS '处置状态';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.RETRY_COUNT IS '重试次数';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.RESOLUTION IS '处置动作';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.RESOLUTION_NOTE IS '处置说明';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.RESOLVED_BY IS '处置人';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.RESOLVED_AT IS '处置时间';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.VOUCHER_ID IS '关联凭证ID';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.OCCURRENCE_TIME IS '发生时间';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_posting_exception.EVENT_DATA IS '原始事件数据(JSON)';
                    
      COMMENT ON TABLE erp_fin_budget_scenario IS '预算方案';
                
      COMMENT ON COLUMN erp_fin_budget_scenario.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CODE IS '方案编码';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.NAME IS '方案名称';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.FISCAL_YEAR IS '预算年度';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.SCENARIO_TYPE IS '方案类型';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.PARENT_SCENARIO_ID IS '源方案(调整预算版本链)';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.VALID_FROM IS '生效日期';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.VALID_TO IS '失效日期';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.AMOUNT_SOURCE IS '预算金额(源币种)';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.AMOUNT_FUNCTIONAL IS '预算金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CONTROL_LEVEL IS '控制级别';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.DOC_STATUS IS '方案状态';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.APPROVE_STATUS IS '审核状态';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.VOUCHER_ID IS '关联预算凭证ID';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.BUDGET_GROUP_CODE IS '预算组编码';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CARRY_FORWARD_RULE IS '结转规则';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.ROLL_FORWARD_STRATEGY IS '滚动复制策略';
                    
      COMMENT ON COLUMN erp_fin_budget_scenario.CLOSED_AT IS '结转时间';
                    
      COMMENT ON TABLE erp_fin_reconciliation_line IS '核销单行';
                
      COMMENT ON COLUMN erp_fin_reconciliation_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.RECONCILIATION_ID IS '核销单ID';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.PAYMENT_ITEM_ID IS '付款/收款项(invoice or payment item)';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.INVOICE_ITEM_ID IS '被核销发票项';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.SETTLED_AMOUNT_SOURCE IS '核销金额(源币)';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.SETTLED_AMOUNT_FUNCTIONAL IS '核销金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_reconciliation_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_bad_debt IS '坏账单';
                
      COMMENT ON COLUMN erp_fin_bad_debt.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.DOC_TYPE IS '坏账单类型';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.PARTNER_ID IS '客户';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.SOURCE_AR_AP_ITEM_ID IS '源应收辅助账项';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.AMOUNT IS '核销/恢复金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.BUSINESS_DATE IS '业务日期';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.REASON IS '核销/恢复原因';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.APPROVAL_STATUS IS '审核状态';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.PERIOD_ID IS '所属期间';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.VOUCHER_ID IS '关联凭证ID';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_bad_debt.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_bank_reconciliation IS '银行对账(余额调节表)';
                
      COMMENT ON COLUMN erp_fin_bank_reconciliation.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.ORG_ID IS '组织';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.FUND_ACCOUNT_ID IS '资金账户';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.STATEMENT_ID IS '银行对账单';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.RECONCILIATION_DATE IS '对账日期';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.BOOK_BALANCE IS '账面余额';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.STATEMENT_BALANCE IS '对账单余额';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.UNRECONCILED_DIFF IS '未达差异';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.IS_BALANCED IS '是否平衡';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.RECONCILED_AT IS '对账完成时间';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.RECONCILED_BY IS '对账人';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.DOC_STATUS IS '状态';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_notes_payable IS '应付票据';
                
      COMMENT ON COLUMN erp_fin_notes_payable.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.CODE IS '单号';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.NOTES_TYPE IS '票据类型';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.NOTES_NO IS '票据号';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.PAYEE_NAME IS '收款人';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.PAYEE_BANK IS '收款行';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.ISSUE_DATE IS '出票日';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.DUE_DATE IS '到期日';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.AMOUNT_SOURCE IS '源币种票面金额';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.AMOUNT_FUNCTIONAL IS '本位币票面金额';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.PARTNER_ID IS '收款方往来';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.CREDIT_FACILITY_ID IS '占用授信额度';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.SOURCE_BILL_TYPE IS '来源单据类型';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.SOURCE_BILL_CODE IS '来源单据号';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.STATUS IS '票据状态';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.POSTED IS '是否已过账';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.POSTED_BY IS '过账人';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.POSTED_AT IS '过账时间';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_notes_payable.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_expense_claim_line IS '费用报销单行';
                
      COMMENT ON COLUMN erp_fin_expense_claim_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.CLAIM_ID IS '报销单ID';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.EXPENSE_TYPE IS '费用类型';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.PROJECT_ID IS '项目';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.COST_CENTER_ID IS '成本中心';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.SUBJECT_ID IS '费用科目';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.SUBJECT_CODE IS '科目编码';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.AMOUNT_WITHOUT_TAX IS '不含税金额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.TAX_RATE IS '税率';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.TAX_AMOUNT IS '税额';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.AMOUNT_WITH_TAX IS '价税合计';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_expense_claim_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_bank_statement_line IS '银行对账单行';
                
      COMMENT ON COLUMN erp_fin_bank_statement_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.STATEMENT_ID IS '对账单ID';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.TRANSACTION_DATE IS '交易日期';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.DESCRIPTION IS '摘要(银行)';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.REF_NO IS '银行参考号';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.DC_DIRECTION IS '借贷方向';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.AMOUNT IS '金额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.BALANCE_AFTER IS '交易后余额';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.MATCH_STATUS IS '匹配状态';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.MATCHED_LINE_ID IS '匹配凭证行ID';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_bank_statement_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_budget_line IS '预算明细行';
                
      COMMENT ON COLUMN erp_fin_budget_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_budget_line.SCENARIO_ID IS '预算方案';
                    
      COMMENT ON COLUMN erp_fin_budget_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_budget_line.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_budget_line.ACCT_SCHEMA_ID IS '账套';
                    
      COMMENT ON COLUMN erp_fin_budget_line.PERIOD_ID IS '会计期间';
                    
      COMMENT ON COLUMN erp_fin_budget_line.SUBJECT_ID IS '预算科目';
                    
      COMMENT ON COLUMN erp_fin_budget_line.SUBJECT_CODE IS '科目编码';
                    
      COMMENT ON COLUMN erp_fin_budget_line.COST_CENTER_ID IS '成本中心';
                    
      COMMENT ON COLUMN erp_fin_budget_line.DEPARTMENT_ID IS '辅助-部门';
                    
      COMMENT ON COLUMN erp_fin_budget_line.PROJECT_ID IS '辅助-项目';
                    
      COMMENT ON COLUMN erp_fin_budget_line.PARTNER_ID IS '辅助-往来单位';
                    
      COMMENT ON COLUMN erp_fin_budget_line.WAREHOUSE_ID IS '辅助-仓库';
                    
      COMMENT ON COLUMN erp_fin_budget_line.MATERIAL_ID IS '辅助-物料';
                    
      COMMENT ON COLUMN erp_fin_budget_line.BUDGET_AMOUNT_SOURCE IS '预算金额(源币种)';
                    
      COMMENT ON COLUMN erp_fin_budget_line.BUDGET_AMOUNT_FUNCTIONAL IS '预算金额(本位币)';
                    
      COMMENT ON COLUMN erp_fin_budget_line.CURRENCY_ID IS '币种';
                    
      COMMENT ON COLUMN erp_fin_budget_line.EXCHANGE_RATE IS '汇率';
                    
      COMMENT ON COLUMN erp_fin_budget_line.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_budget_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_budget_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_budget_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_budget_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_budget_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_budget_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_budget_rollforward_log IS '预算滚动复制日志';
                
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.SCENARIO_ID IS '预算方案';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.SOURCE_SCENARIO_ID IS '源方案';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.TARGET_SCENARIO_ID IS '目标方案';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.STRATEGY IS '复制策略';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.NEW_FISCAL_YEAR IS '目标年度';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.SOURCE_AMOUNT IS '源金额合计';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.TARGET_AMOUNT IS '目标金额合计';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.ROLLED_AT IS '复制时间';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.ROLLED_BY IS '复制人';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_budget_rollforward_log.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_budget_carry_forward_log IS '预算结转日志';
                
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.SCENARIO_ID IS '预算方案';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.SOURCE_SCENARIO_ID IS '源方案';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.TARGET_SCENARIO_ID IS '目标方案';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.RULE IS '结转规则';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.SOURCE_REMAINING IS '源方案余量';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.SOURCE_USED IS '源方案已用';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.CARRIED_AMOUNT IS '结转金额';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.CARRIED_AT IS '结转时间';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.CARRIED_BY IS '结转人';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_budget_carry_forward_log.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_bank_reconciliation_line IS '银行对账调整行';
                
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.RECONCILIATION_ID IS '对账记录ID';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.LINE_NO IS '行号';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.ADJUSTMENT_TYPE IS '调整类型';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.DESCRIPTION IS '说明';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.DC_DIRECTION IS '借贷方向';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.AMOUNT IS '金额';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.SIDE IS '调整方';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.REMARK IS '备注';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_bank_reconciliation_line.UPDATE_TIME IS '修改时间';
                    
      COMMENT ON TABLE erp_fin_budget_control_log IS '预算控制日志';
                
      COMMENT ON COLUMN erp_fin_budget_control_log.ID IS 'ID';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.ORG_ID IS '核算组织';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.BUSINESS_DATE IS '业务日期';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.SCENARIO_ID IS '预算方案';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.BUDGET_LINE_ID IS '预算明细行';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.SOURCE_BILL_TYPE IS '触发单据类型';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.SOURCE_BILL_CODE IS '触发单据号';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.SUBJECT_ID IS '命中科目';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.COST_CENTER_ID IS '命中成本中心';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.PROJECT_ID IS '命中项目';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.PERIOD_ID IS '命中期间';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.REQUESTED_AMOUNT IS '申请占用金额';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.COMMITTED_AMOUNT IS '实际占用金额';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.AVAILABLE_AMOUNT IS '检查时余量';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.ACTION_RESULT IS '控制结果';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.OPERATOR_ID IS '操作人';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.OPERATED_AT IS '操作时间';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.REASON IS '原因';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.DEL_VERSION IS '逻辑删除版本';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.VERSION IS '数据版本';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.CREATED_BY IS '创建人';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.CREATE_TIME IS '创建时间';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.UPDATED_BY IS '修改人';
                    
      COMMENT ON COLUMN erp_fin_budget_control_log.UPDATE_TIME IS '修改时间';
                    
