package app.erp.mnt.service.support;

import app.erp.mnt.biz.IErpMntEquipmentBiz;
import app.erp.mnt.biz.IErpMntTaskTemplateBiz;
import app.erp.mnt.biz.IErpMntVisitBiz;
import app.erp.mnt.biz.IErpMntVisitTaskBiz;
import app.erp.mnt.dao.ErpMntDaoConstants;
import app.erp.mnt.dao.entity.ErpMntEquipment;
import app.erp.mnt.dao.entity.ErpMntSchedule;
import app.erp.mnt.dao.entity.ErpMntTaskTemplate;
import app.erp.mnt.dao.entity.ErpMntTaskTemplateLine;
import app.erp.mnt.dao.entity.ErpMntVisit;
import app.erp.mnt.service.ErpMntConfigs;
import io.nop.api.core.beans.query.QueryBean;
import io.nop.api.core.time.CoreMetrics;
import io.nop.core.context.IServiceContext;
import io.nop.dao.api.IDaoProvider;
import io.nop.dao.api.IEntityDao;
import jakarta.inject.Inject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static io.nop.api.core.beans.FilterBeans.eq;
import static io.nop.api.core.beans.FilterBeans.isNull;
import static io.nop.api.core.beans.FilterBeans.le;
import static io.nop.api.core.beans.FilterBeans.or;

/**
 * 维护计划到期生成访问生成器。两类计划同一入口评估（RC-R1.73 / UC-MAIN-02 运行时长触发并入
 * 既有 due-visit job，无新 job）：
 * <ul>
 *   <li><b>TIME 计划</b>（triggerType null=派生 TIME 或显式 TIME）：扫描 active 计划
 *       nextDueDate ≤ asOfDate 生成 DRAFT 访问（visitType=PLANNED）+ 按 recurrenceType/frequency
 *       推进 nextDueDate（既有链路，行为零变化）。</li>
 *   <li><b>RUNTIME 计划</b>（triggerType=RUNTIME）：累计运行时长（{@link EquipmentRuntimeCalculator}
 *       查询时聚合）≥ runtimeBaselineHours + thresholdHours 时生成 DRAFT 访问（visitDate=asOfDate），
 *       同事务置 baseline=当前累计（幂等锚点，job 重跑不重复生成）；thresholdHours 缺失/非正不触发；
 *       nextDueDate 不推进（保持 null/原值，时间轴语义不适用）。</li>
 * </ul>
 * 计划性访问生成后套用维护任务模板（RC-R1.74 / UC-MAIN-01）：显式 schedule.templateId 优先，
 * 空则按 equipment.categoryId 匹配唯一 active 模板回退，零/多匹配 LOG.warn 跳过不阻断——
 * 模板行逐行复制为 {@code ErpMntVisitTask}（taskDescription=taskName，standardMinutes 透传，
 * status=PENDING；visit.totalMinutes 不预填=执行时长语义；标准备件 materialId/quantity 为模板行
 * 提示字段，不自动产生消耗单据）。RESPONSIVE 访问不套用模板（ErpMntRequestAcceptProcessor 链，
 * L1 联动断言不含任务清单）。
 * 经 {@code erp-mnt.auto-generate-due-visits} 门控。
 */
public class ScheduleDueGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(ScheduleDueGenerator.class);

    @Inject
    IDaoProvider daoProvider;

    @Inject
    IErpMntVisitBiz visitBiz;

    @Inject
    IErpMntEquipmentBiz equipmentBiz;

    @Inject
    IErpMntTaskTemplateBiz templateBiz;

    @Inject
    IErpMntVisitTaskBiz visitTaskBiz;

    @Inject
    EquipmentRuntimeCalculator runtimeCalculator;

    @Inject
    DecommissionedEquipmentGuard decommissionedGuard;

    public int generateDueVisits(LocalDate asOfDate, IServiceContext context) {
        if (!ErpMntConfigs.autoGenerateDueVisits()) {
            return 0;
        }
        int count = generateForTimeSchedules(asOfDate, context);
        count += generateForRuntimeSchedules(asOfDate, context);
        return count;
    }

    protected int generateForTimeSchedules(LocalDate asOfDate, IServiceContext context) {
        List<ErpMntSchedule> dueSchedules = findDueSchedules(asOfDate);
        int count = 0;
        for (ErpMntSchedule schedule : dueSchedules) {
            // 幂等去重（plan 2026-07-30-0841-2 R1.28 P1-MA2-086）：同 (schedule, asOfDate) 已生成访问则跳过，
            // 避免重复触发（并发 job / 重试）产生重复 VST-SCH-{schedId}-{date} 行。
            if (existsVisitForScheduleDate(schedule.getId(), asOfDate)) {
                continue;
            }
            // RC-R1.77 / UC-MAIN-08：DECOMMISSIONED 设备（资产已处置）计划查询侧排除 + warn 跳过——
            // 到期访问日批 job 循环无 per-schedule try/catch，visitBiz.save 守卫若触发将中断整批（绿基线回归，禁止）。
            if (decommissionedGuard.isDecommissioned(schedule.getEquipmentId(), context)) {
                LOG.warn("Schedule {} references DECOMMISSIONED equipment {} (asset disposed), skip due-visit generation",
                        schedule.getCode(), schedule.getEquipmentId());
                continue;
            }
            generateVisitForSchedule(schedule, asOfDate, context);
            advanceNextDueDate(schedule, asOfDate);
            daoProvider.daoFor(ErpMntSchedule.class).updateEntity(schedule);
            count++;
        }
        return count;
    }

    /**
     * RUNTIME 计划评估（RC-R1.73 D2 裁决：baseline 列锚点，否决从上次生成 visit 反推）。
     * 触发粒度 = job cron 部署节奏（对齐 L2 §5.2 单一定时任务模型）。
     */
    protected int generateForRuntimeSchedules(LocalDate asOfDate, IServiceContext context) {
        List<ErpMntSchedule> schedules = findRuntimeDueSchedules();
        int count = 0;
        for (ErpMntSchedule schedule : schedules) {
            if (schedule.getThresholdHours() == null || schedule.getThresholdHours().signum() <= 0) {
                continue; // 阈值未配置/非正 = 不可触发（语义：阈值必须显式为正）
            }
            // RC-R1.77：RUNTIME 触发扫描同口径排除 DECOMMISSIONED 设备（D2 ③）。
            if (decommissionedGuard.isDecommissioned(schedule.getEquipmentId(), context)) {
                LOG.warn("RUNTIME schedule {} references DECOMMISSIONED equipment {} (asset disposed), skip evaluation",
                        schedule.getCode(), schedule.getEquipmentId());
                continue;
            }
            if (existsVisitForScheduleDate(schedule.getId(), asOfDate)) {
                continue;
            }
            BigDecimal current = runtimeCalculator.computeRunningHours(schedule.getEquipmentId(),
                    Timestamp.valueOf(CoreMetrics.currentDateTime()));
            BigDecimal baseline = schedule.getRuntimeBaselineHours() != null
                    ? schedule.getRuntimeBaselineHours() : BigDecimal.ZERO;
            if (current.compareTo(baseline.add(schedule.getThresholdHours())) < 0) {
                continue;
            }
            generateVisit(schedule, asOfDate, asOfDate, context);
            schedule.setRuntimeBaselineHours(current);
            daoProvider.daoFor(ErpMntSchedule.class).updateEntity(schedule);
            count++;
        }
        return count;
    }

    protected boolean existsVisitForScheduleDate(Long scheduleId, LocalDate asOfDate) {
        IEntityDao<ErpMntVisit> dao = daoProvider.daoFor(ErpMntVisit.class);
        QueryBean q = new QueryBean();
        q.addFilter(eq("code", "VST-SCH-" + scheduleId + "-" + asOfDate));
        q.setLimit(1);
        return !dao.findAllByQuery(q).isEmpty();
    }

    /** TIME 计划候选：active + nextDueDate ≤ asOfDate；显式排除 RUNTIME 计划（null=派生 TIME）。 */
    protected List<ErpMntSchedule> findDueSchedules(LocalDate asOfDate) {
        IEntityDao<ErpMntSchedule> dao = daoProvider.daoFor(ErpMntSchedule.class);
        QueryBean q = new QueryBean();
        q.addFilter(eq("isActive", 1));
        q.addFilter(le("nextDueDate", asOfDate));
        q.addFilter(or(isNull("triggerType"), eq("triggerType", ErpMntDaoConstants.TRIGGER_TYPE_TIME)));
        return new ArrayList<>(dao.findAllByQuery(q));
    }

    /** RUNTIME 计划候选：active + triggerType=RUNTIME（nextDueDate 时间轴不适用，经运行时长评估）。 */
    protected List<ErpMntSchedule> findRuntimeDueSchedules() {
        IEntityDao<ErpMntSchedule> dao = daoProvider.daoFor(ErpMntSchedule.class);
        QueryBean q = new QueryBean();
        q.addFilter(eq("isActive", 1));
        q.addFilter(eq("triggerType", ErpMntDaoConstants.TRIGGER_TYPE_RUNTIME));
        return new ArrayList<>(dao.findAllByQuery(q));
    }

    protected ErpMntVisit generateVisitForSchedule(ErpMntSchedule schedule, LocalDate asOfDate,
                                                   IServiceContext context) {
        LocalDate visitDate = schedule.getNextDueDate() != null ? schedule.getNextDueDate() : asOfDate;
        return generateVisit(schedule, visitDate, asOfDate, context);
    }

    protected ErpMntVisit generateVisit(ErpMntSchedule schedule, LocalDate visitDate, LocalDate asOfDate,
                                        IServiceContext context) {
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("code", "VST-SCH-" + schedule.getId() + "-" + asOfDate);
        data.put("scheduleId", schedule.getId());
        data.put("equipmentId", schedule.getEquipmentId());
        data.put("visitDate", visitDate);
        data.put("status", ErpMntDaoConstants.VISIT_STATUS_DRAFT);
        data.put("visitType", ErpMntDaoConstants.VISIT_TYPE_PLANNED);
        ErpMntVisit visit = visitBiz.save(data, context);
        applyTaskTemplate(visit, schedule, context);
        return visit;
    }

    /**
     * RC-R1.74 / UC-MAIN-01 模板套用（D4）：模板行逐行复制为 {@code ErpMntVisitTask}
     * （taskDescription=taskName、standardMinutes 透传[行级缺失回落模板级]、status=PENDING）；
     * visit.totalMinutes 不预填（执行时长语义）；标准备件 materialId/quantity 为模板行提示字段，
     * 不自动产生消耗单据（实际消耗走既有 confirm 链）。RESPONSIVE 访问不进入本方法（模板属计划性维护语义）。
     */
    protected void applyTaskTemplate(ErpMntVisit visit, ErpMntSchedule schedule, IServiceContext context) {
        ErpMntTaskTemplate template = resolveTaskTemplate(schedule, context);
        if (template == null) {
            return;
        }
        List<ErpMntTaskTemplateLine> lines = new ArrayList<>(template.getLines());
        lines.sort(Comparator.comparing(ErpMntTaskTemplateLine::getLineNo,
                Comparator.nullsLast(Comparator.naturalOrder())));
        for (ErpMntTaskTemplateLine line : lines) {
            Map<String, Object> task = new LinkedHashMap<>();
            task.put("visitId", visit.getId());
            task.put("lineNo", line.getLineNo());
            task.put("taskDescription", line.getTaskName());
            task.put("standardMinutes", line.getStandardMinutes() != null
                    ? line.getStandardMinutes() : template.getStandardMinutes());
            task.put("status", ErpMntDaoConstants.VISIT_TASK_STATUS_PENDING);
            visitTaskBiz.save(task, context);
        }
    }

    /**
     * 模板解析（D4）：显式 schedule.templateId 优先（显式锚定不校验 isActive），
     * 空则按 equipment.categoryId 匹配唯一 active 模板回退；零/多匹配 LOG.warn 跳过不阻断访问生成。
     */
    protected ErpMntTaskTemplate resolveTaskTemplate(ErpMntSchedule schedule, IServiceContext context) {
        if (schedule.getTemplateId() != null) {
            ErpMntTaskTemplate template = templateBiz.get(String.valueOf(schedule.getTemplateId()), false, context);
            if (template == null) {
                LOG.warn("Schedule {} references missing task template {}, skip template application",
                        schedule.getCode(), schedule.getTemplateId());
            }
            return template;
        }
        ErpMntEquipment equipment = equipmentBiz.get(String.valueOf(schedule.getEquipmentId()), false, context);
        if (equipment == null || equipment.getCategoryId() == null) {
            return null;
        }
        QueryBean q = new QueryBean();
        q.addFilter(eq("equipmentCategoryId", equipment.getCategoryId()));
        q.addFilter(eq("isActive", 1));
        List<ErpMntTaskTemplate> matches = templateBiz.findList(q, null, context);
        if (matches.size() != 1) {
            LOG.warn("Equipment category {} matches {} active task templates (expect exactly 1), skip template application",
                    equipment.getCategoryId(), matches.size());
            return null;
        }
        return matches.get(0);
    }

    protected void advanceNextDueDate(ErpMntSchedule schedule, LocalDate asOfDate) {
        LocalDate base = schedule.getNextDueDate() != null ? schedule.getNextDueDate() : asOfDate;
        int frequency = schedule.getFrequency() != null && schedule.getFrequency() > 0
                ? schedule.getFrequency() : 1;
        String recurrenceType = schedule.getRecurrenceType() != null
                ? schedule.getRecurrenceType() : ErpMntDaoConstants.RECURRENCE_TYPE_MONTHLY;
        LocalDate next;
        switch (recurrenceType) {
            case ErpMntDaoConstants.RECURRENCE_TYPE_DAILY:
                next = base.plusDays(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_WEEKLY:
                next = base.plusWeeks(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_YEARLY:
                next = base.plusYears(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_MONTHLY:
            default:
                next = base.plusMonths(frequency);
                break;
        }
        schedule.setNextDueDate(next);
    }
}
