package app.erp.mnt.service.support;

import app.erp.mnt.biz.IErpMntVisitBiz;
import app.erp.mnt.dao.ErpMntDaoConstants;
import app.erp.mnt.dao.entity.ErpMntSchedule;
import app.erp.mnt.dao.entity.ErpMntVisit;
import app.erp.mnt.service.ErpMntConfigs;
import io.nop.api.core.beans.query.QueryBean;
import io.nop.core.context.IServiceContext;
import io.nop.dao.api.IDaoProvider;
import io.nop.dao.api.IEntityDao;
import jakarta.inject.Inject;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static io.nop.api.core.beans.FilterBeans.eq;
import static io.nop.api.core.beans.FilterBeans.le;

/**
 * 维护计划到期生成访问生成器。扫描 active 计划 nextDueDate ≤ asOfDate 生成 DRAFT 访问（visitType=PLANNED）
 * + 按 recurrenceType/frequency 推进 nextDueDate；经 {@code erp-mnt.auto-generate-due-visits} 门控。
 */
public class ScheduleDueGenerator {

    @Inject
    IDaoProvider daoProvider;

    @Inject
    IErpMntVisitBiz visitBiz;

    public int generateDueVisits(LocalDate asOfDate, IServiceContext context) {
        if (!ErpMntConfigs.autoGenerateDueVisits()) {
            return 0;
        }
        List<ErpMntSchedule> dueSchedules = findDueSchedules(asOfDate);
        int count = 0;
        for (ErpMntSchedule schedule : dueSchedules) {
            generateVisitForSchedule(schedule, asOfDate, context);
            advanceNextDueDate(schedule, asOfDate);
            daoProvider.daoFor(ErpMntSchedule.class).updateEntity(schedule);
            count++;
        }
        return count;
    }

    protected List<ErpMntSchedule> findDueSchedules(LocalDate asOfDate) {
        IEntityDao<ErpMntSchedule> dao = daoProvider.daoFor(ErpMntSchedule.class);
        QueryBean q = new QueryBean();
        q.addFilter(eq("isActive", 1));
        q.addFilter(le("nextDueDate", asOfDate));
        return new ArrayList<>(dao.findAllByQuery(q));
    }

    protected ErpMntVisit generateVisitForSchedule(ErpMntSchedule schedule, LocalDate asOfDate,
                                                   IServiceContext context) {
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("code", "VST-SCH-" + schedule.getId() + "-" + asOfDate);
        data.put("scheduleId", schedule.getId());
        data.put("equipmentId", schedule.getEquipmentId());
        data.put("visitDate", schedule.getNextDueDate() != null ? schedule.getNextDueDate() : asOfDate);
        data.put("status", ErpMntDaoConstants.VISIT_STATUS_DRAFT);
        data.put("visitType", ErpMntDaoConstants.VISIT_TYPE_PLANNED);
        return visitBiz.save(data, context);
    }

    protected void advanceNextDueDate(ErpMntSchedule schedule, LocalDate asOfDate) {
        LocalDate base = schedule.getNextDueDate() != null ? schedule.getNextDueDate() : asOfDate;
        int frequency = schedule.getFrequency() != null && schedule.getFrequency() > 0
                ? schedule.getFrequency() : 1;
        int recurrenceType = schedule.getRecurrenceType() != null
                ? schedule.getRecurrenceType() : ErpMntDaoConstants.RECURRENCE_TYPE_MONTHLY;
        LocalDate next;
        switch (recurrenceType) {
            case ErpMntDaoConstants.RECURRENCE_TYPE_DAILY:
                next = base.plusDays(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_WEEKLY:
                next = base.plusWeeks(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_YEARLY:
                next = base.plusYears(frequency);
                break;
            case ErpMntDaoConstants.RECURRENCE_TYPE_MONTHLY:
            default:
                next = base.plusMonths(frequency);
                break;
        }
        schedule.setNextDueDate(next);
    }
}
