
CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  MATERIAL_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_sku(
  ID BIGINT NULL    COMMENT 'null',
  MATERIAL_ID BIGINT NULL    COMMENT 'null',
  SKU_CODE VARCHAR(50) NULL    COMMENT 'null',
  BARCODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_material_sku primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  UOM_GROUP VARCHAR(50) NULL    COMMENT 'null',
  IS_BASE BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_uom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_warehouse(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_workcenter(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工作中心编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '工作中心名称',
  CAPACITY DECIMAL(16,4) NULL    COMMENT '产能',
  CAPACITY_UNIT VARCHAR(20) NULL    COMMENT '产能单位',
  HOURLY_RATE DECIMAL(16,4) NULL    COMMENT '小时费率',
  WORK_HOURS_PER_DAY DECIMAL(8,2) NULL    COMMENT '日工时',
  IS_EXTERNAL BOOLEAN default 0  NULL    COMMENT '是否外协',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_workcenter primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_routing(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工艺路线编码',
  NAME VARCHAR(200) NULL    COMMENT '工艺路线名称',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否有效',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_routing primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SYMBOL VARCHAR(50) NULL    COMMENT 'null',
  DECIMAL_PLACES INTEGER NULL    COMMENT 'null',
  IS_FUNCTIONAL BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_location(
  ID BIGINT NULL    COMMENT 'null',
  WAREHOUSE_ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_location primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_batch(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_inv_batch primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_bom(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT 'BOM编码',
  PRODUCT_ID BIGINT NOT NULL    COMMENT '产品',
  BOM_TYPE VARCHAR(20) NOT NULL    COMMENT 'BOM类型',
  CONSUMPTION VARCHAR(20) NULL    COMMENT '消耗控制',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否有效',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  USE_MULTI_LEVEL_BOM BOOLEAN default 0  NULL    COMMENT '展开多层BOM',
  INSPECTION_REQUIRED BOOLEAN default 0  NULL    COMMENT '需要质检',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  VERSION_LABEL VARCHAR(50) NULL    COMMENT '版本号',
  QTY DECIMAL(20,4) default 1  NULL    COMMENT 'BOM数量',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_bom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_routing_operation(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ROUTING_ID BIGINT NOT NULL    COMMENT '工艺路线ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  OPERATION_CODE VARCHAR(50) NULL    COMMENT '工序编码',
  OPERATION_NAME VARCHAR(200) NULL    COMMENT '工序名称',
  WORKCENTER_ID BIGINT NULL    COMMENT '工作中心',
  STANDARD_TIME DECIMAL(12,2) NULL    COMMENT '标准工时',
  TIME_UNIT VARCHAR(20) NULL    COMMENT '时间单位',
  SETUP_TIME DECIMAL(12,2) NULL    COMMENT '准备时间',
  RUN_TIME DECIMAL(12,2) NULL    COMMENT '加工时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_routing_operation primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_workcenter_calendar(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORKCENTER_ID BIGINT NOT NULL    COMMENT '工作中心',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CALENDAR_NAME VARCHAR(200) NOT NULL    COMMENT '日历名称',
  SHIFT_TYPE VARCHAR(20) NOT NULL    COMMENT '班次类型',
  WORK_DATE_PATTERN VARCHAR(20) NULL    COMMENT '工作日模式',
  START_TIME VARCHAR(8) NULL    COMMENT '班次开始时间',
  END_TIME VARCHAR(8) NULL    COMMENT '班次结束时间',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效起始日期',
  EFFECTIVE_TO DATE NULL    COMMENT '生效结束日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否有效',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_workcenter_calendar primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_workcenter_capacity(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORKCENTER_ID BIGINT NOT NULL    COMMENT '工作中心',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '关联物料',
  CAPACITY_PER_HOUR DECIMAL(16,4) NOT NULL    COMMENT '每小时产能',
  SETUP_TIME DECIMAL(12,2) default 0  NULL    COMMENT '换模时间(分钟)',
  CLEANUP_TIME DECIMAL(12,2) default 0  NULL    COMMENT '清理时间(分钟)',
  EFFICIENCY_FACTOR DECIMAL(10,4) default 1  NULL    COMMENT '效率系数',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否有效',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_workcenter_capacity primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_mrp_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '计划号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '计划日期',
  PLANNING_HORIZON_DAYS INTEGER NULL    COMMENT '计划区间(天)',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_mrp_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_forecast(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PLAN_NAME VARCHAR(200) NOT NULL    COMMENT '预测名称',
  PERIOD_FROM DATE NOT NULL    COMMENT '预测区间起',
  PERIOD_TO DATE NOT NULL    COMMENT '预测区间止',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_forecast primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_cost_rollup(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '计算日期',
  COSTING_VERSION VARCHAR(50) NULL    COMMENT '成本核算版本',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_cost_rollup primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_bom_byproduct(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BOM_ID BIGINT NOT NULL    COMMENT 'BOM ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  BYPRODUCT_TYPE VARCHAR(20) NULL    COMMENT '联副产品类型',
  YIELD_RATE DECIMAL(10,4) default 100  NULL    COMMENT '产出率(%)',
  COST_ALLOCATION_PERCENT DECIMAL(10,4) default 0  NULL    COMMENT '成本分摊比例(%)',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_bom_byproduct primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_production_version(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '版本编码',
  PRODUCT_ID BIGINT NOT NULL    COMMENT '产品',
  BOM_ID BIGINT NOT NULL    COMMENT 'BOM',
  ROUTING_ID BIGINT NOT NULL    COMMENT '工艺路线',
  VALID_FROM DATE NULL    COMMENT '生效日期',
  VALID_TO DATE NULL    COMMENT '失效日期',
  LOT_SIZE_FROM DECIMAL(20,4) NULL    COMMENT '批量下限',
  LOT_SIZE_TO DECIMAL(20,4) NULL    COMMENT '批量上限',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认版本',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否有效',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_production_version primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_bom_operation(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BOM_ID BIGINT NOT NULL    COMMENT 'BOM ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  OPERATION_ID BIGINT NOT NULL    COMMENT '工序ID',
  WORKCENTER_ID BIGINT NULL    COMMENT '工作中心',
  STANDARD_TIME DECIMAL(12,2) NULL    COMMENT '标准工时',
  TIME_UNIT VARCHAR(20) NULL    COMMENT '时间单位',
  RATE DECIMAL(10,4) default 1  NULL    COMMENT '效率系数',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_bom_operation primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_mrp_plan_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MRP_PLAN_ID BIGINT NOT NULL    COMMENT 'MRP计划ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  ORDER_TYPE VARCHAR(20) NOT NULL    COMMENT '建议类型',
  GROSS_REQUIREMENT DECIMAL(20,4) NOT NULL    COMMENT '毛需求',
  SCHEDULED_RECEIPT DECIMAL(20,4) default 0  NULL    COMMENT '预计入库',
  ON_HAND DECIMAL(20,4) default 0  NULL    COMMENT '现有库存',
  NET_REQUIREMENT DECIMAL(20,4) NOT NULL    COMMENT '净需求',
  PLANNED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '计划数量',
  PLANNED_DATE DATE NOT NULL    COMMENT '计划到货/开工日期',
  PARENT_LINE_ID BIGINT NULL    COMMENT '父需求行(多级 BOM 展开)',
  IS_FIRMED BOOLEAN default 0  NULL    COMMENT '是否已转正式单据',
  CONVERTED_BILL_CODE VARCHAR(50) NULL    COMMENT '转换后单据号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_mrp_plan_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_mrp_demand(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MRP_PLAN_ID BIGINT NOT NULL    COMMENT 'MRP计划ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  DEMAND_SOURCE VARCHAR(20) NOT NULL    COMMENT '需求来源',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '需求数量',
  REQUIREMENT_DATE DATE NOT NULL    COMMENT '需求日期',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_mrp_demand primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_forecast_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  FORECAST_ID BIGINT NOT NULL    COMMENT '需求预测ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  WAREHOUSE_ID BIGINT NULL    COMMENT '仓库（可选，空=产品级 MRP 消费，填=仓级 DRP 消费）',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  PERIOD_START DATE NOT NULL    COMMENT '桶起始日期',
  PERIOD_END DATE NOT NULL    COMMENT '桶结束日期',
  FORECAST_QTY DECIMAL(20,4) NOT NULL    COMMENT '预测数量',
  SOURCED_FLAG VARCHAR(50) NULL    COMMENT '来源标记',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_forecast_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_cost_rollup_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  COST_ROLLUP_ID BIGINT NOT NULL    COMMENT '滚算单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '产品',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  MATERIAL_COST DECIMAL(20,4) default 0  NULL    COMMENT '材料成本',
  LABOR_COST DECIMAL(20,4) default 0  NULL    COMMENT '人工成本',
  OVERHEAD_COST DECIMAL(20,4) default 0  NULL    COMMENT '制造费用',
  SUBCONTRACT_COST DECIMAL(20,4) default 0  NULL    COMMENT '委外成本',
  TOTAL_COST DECIMAL(20,4) default 0  NULL    COMMENT '总成本',
  UNIT_COST DECIMAL(20,4) default 0  NULL    COMMENT '单位标准成本',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_cost_rollup_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_work_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BOM_ID BIGINT NULL    COMMENT 'BOM',
  ROUTING_ID BIGINT NULL    COMMENT '工艺路线',
  PRODUCTION_VERSION_ID BIGINT NULL    COMMENT '生产版本',
  SOURCE_MRP_PLAN_ID BIGINT NULL    COMMENT '来源 MRP 计划',
  SOURCE_ORDER_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_ORDER_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  PRODUCT_ID BIGINT NOT NULL    COMMENT '产品(主产出)',
  PLANNED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '计划数量',
  COMPLETED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '完工数量',
  SCRAPPED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '报废数量',
  BUSINESS_DATE DATE NOT NULL    COMMENT '工单日期',
  PLANNED_START_DATE DATE NULL    COMMENT '计划开工日期',
  PLANNED_END_DATE DATE NULL    COMMENT '计划完工日期',
  ACTUAL_START_DATE DATE NULL    COMMENT '实际开工日期',
  ACTUAL_END_DATE DATE NULL    COMMENT '实际完工日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  MATERIAL_COST DECIMAL(20,4) default 0  NULL    COMMENT '材料成本',
  LABOR_COST DECIMAL(20,4) default 0  NULL    COMMENT '人工成本',
  OVERHEAD_COST DECIMAL(20,4) default 0  NULL    COMMENT '制造费用',
  SUBCONTRACT_COST DECIMAL(20,4) default 0  NULL    COMMENT '委外成本',
  TOTAL_COST DECIMAL(20,4) default 0  NULL    COMMENT '总成本',
  UNIT_COST DECIMAL(20,4) default 0  NULL    COMMENT '单位成本',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NULL    COMMENT '审核状态',
  PRIORITY VARCHAR(20) NULL    COMMENT '优先级',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  SOURCE_SCHEDULE_ID BIGINT NULL    COMMENT 'APS排程来源(弱参照)',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_mfg_work_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_bom_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BOM_ID BIGINT NOT NULL    COMMENT 'BOM ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  OPERATION_ID BIGINT NULL    COMMENT '工序ID',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  SCRAP_RATE DECIMAL(10,4) default 0  NULL    COMMENT '损耗率(%)',
  WAREHOUSE_ID BIGINT NULL    COMMENT '发货仓库',
  ALTERNATIVE_MATERIAL_ID BIGINT NULL    COMMENT '替代物料',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_bom_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_crp_load(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORKCENTER_ID BIGINT NOT NULL    COMMENT '工作中心',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  WORK_ORDER_ID BIGINT NULL    COMMENT '工单(弱指针)',
  LOAD_DATE DATE NOT NULL    COMMENT '负荷日期',
  LOAD_HOURS DECIMAL(12,2) default 0  NULL    COMMENT '占用工时',
  SETUP_HOURS DECIMAL(12,2) default 0  NULL    COMMENT '换模工时',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_crp_load primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_work_order_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  LINE_TYPE VARCHAR(20) NOT NULL    COMMENT '行类型(OUTPUT 产出/INPUT 投入/BYPRODUCT 联副)',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  PLANNED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '计划数量',
  ACTUAL_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '实际数量(完工/领用)',
  SCRAPPED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '报废数量',
  SOURCE_WAREHOUSE_ID BIGINT NULL    COMMENT '领料仓库(投入用)',
  DEST_WAREHOUSE_ID BIGINT NULL    COMMENT '入库仓库(产出用)',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_work_order_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_subcontract_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  WORK_ORDER_ID BIGINT NULL    COMMENT '来源工单',
  SUPPLIER_ID BIGINT NOT NULL    COMMENT '委外供应商',
  WORKCENTER_ID BIGINT NULL    COMMENT '外协工作中心',
  ROUTING_ID BIGINT NULL    COMMENT '工艺路线',
  PRODUCTION_VERSION_ID BIGINT NULL    COMMENT '生产版本',
  PRODUCT_ID BIGINT NOT NULL    COMMENT '产品',
  BUSINESS_DATE DATE NOT NULL    COMMENT '委外日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NOT NULL    COMMENT '汇率',
  PROCESSING_FEE DECIMAL(20,4) default 0  NULL    COMMENT '加工费',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_STATUS VARCHAR(20) NOT NULL    COMMENT '过账状态',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  constraint PK_erp_mfg_subcontract_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_job_card(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单ID',
  OPERATION_ID BIGINT NULL    COMMENT '工序ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  PLANNED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '计划数量',
  COMPLETED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '完工数量',
  SCRAPPED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '报废数量',
  STATUS VARCHAR(30) NOT NULL    COMMENT '状态',
  WORKCENTER_ID BIGINT NULL    COMMENT '工作中心',
  ACTUAL_START_TIME DATETIME(3) NULL    COMMENT '实际开始时间',
  ACTUAL_END_TIME DATETIME(3) NULL    COMMENT '实际结束时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  CODE VARCHAR(50) NULL    COMMENT '作业卡编号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  SOURCE_SCHEDULE_ID BIGINT NULL    COMMENT 'APS排程来源(弱参照)',
  constraint PK_erp_mfg_job_card primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_cost_variance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  VARIANCE_TYPE VARCHAR(50) NOT NULL    COMMENT '差异类型',
  COST_ELEMENT VARCHAR(50) NOT NULL    COMMENT '成本要素',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  OPERATION_ID BIGINT NULL    COMMENT '工序',
  STANDARD_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '标准金额',
  ACTUAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '实际金额',
  VARIANCE_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '差异金额',
  VARIANCE_PERCENT DECIMAL(10,4) default 0  NULL    COMMENT '差异百分比',
  STANDARD_QTY DECIMAL(20,4) default 0  NULL    COMMENT '标准数量',
  ACTUAL_QTY DECIMAL(20,4) default 0  NULL    COMMENT '实际数量',
  STANDARD_PRICE DECIMAL(20,4) default 0  NULL    COMMENT '标准单价',
  ACTUAL_PRICE DECIMAL(20,4) default 0  NULL    COMMENT '实际单价',
  WORKCENTER_ID BIGINT NULL    COMMENT '工作中心',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_cost_variance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_subcontract_order_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SUBCONTRACT_ORDER_ID BIGINT NOT NULL    COMMENT '委外单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '委外数量',
  UNIT_PROCESSING_FEE DECIMAL(20,4) NULL    COMMENT '单位加工费',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_subcontract_order_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_material_issue(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单',
  JOB_CARD_ID BIGINT NULL    COMMENT '作业卡',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '发料仓库',
  BUSINESS_DATE DATE NOT NULL    COMMENT '领料日期',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_mfg_material_issue primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_job_card_time_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  JOB_CARD_ID BIGINT NOT NULL    COMMENT '作业卡ID',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单ID',
  OPERATOR_ID VARCHAR(36) NOT NULL    COMMENT '操作员(职员)',
  WORK_DATE DATE NOT NULL    COMMENT '作业日期',
  START_TIME DATETIME(3) NULL    COMMENT '开始时间',
  END_TIME DATETIME(3) NULL    COMMENT '结束时间',
  DURATION_MINS DECIMAL(12,2) NOT NULL    COMMENT '工时(分钟)',
  SETUP_MINS DECIMAL(12,2) default 0  NULL    COMMENT '准备时间(分钟)',
  RUN_MINS DECIMAL(12,2) default 0  NULL    COMMENT '加工时间(分钟)',
  COMPLETED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '本班完工数量',
  SCRAPPED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '本班报废数量',
  HOURLY_RATE DECIMAL(16,4) NULL    COMMENT '小时费率',
  LABOR_COST DECIMAL(20,4) default 0  NULL    COMMENT '人工成本',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_job_card_time_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_batch_genealogy(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '工单',
  JOB_CARD_ID BIGINT NULL    COMMENT '作业卡',
  OPERATION_ID BIGINT NULL    COMMENT '工序',
  INPUT_LOT_ID BIGINT NOT NULL    COMMENT '输入批次',
  INPUT_MATERIAL_ID BIGINT NOT NULL    COMMENT '输入物料',
  INPUT_QTY DECIMAL(20,4) NOT NULL    COMMENT '投入数量',
  INPUT_UO_M_ID BIGINT NOT NULL    COMMENT '投入计量单位',
  OUTPUT_LOT_ID BIGINT NOT NULL    COMMENT '产出批次',
  OUTPUT_MATERIAL_ID BIGINT NOT NULL    COMMENT '产出物料',
  OUTPUT_QTY DECIMAL(20,4) NOT NULL    COMMENT '产出数量',
  OUTPUT_UO_M_ID BIGINT NOT NULL    COMMENT '产出计量单位',
  PRODUCTION_DATE DATE NOT NULL    COMMENT '生产日期',
  PRODUCTION_TIME DATETIME(3) NULL    COMMENT '生产时间',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  LOT_STATUS VARCHAR(50) NULL    COMMENT '批次状态',
  IS_INPUT_CONSUMED BOOLEAN default 0  NULL    COMMENT '输入是否已消耗',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_batch_genealogy primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_mfg_material_issue_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ISSUE_ID BIGINT NOT NULL    COMMENT '领料单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  WORK_ORDER_LINE_ID BIGINT NULL    COMMENT '对应工单投入行',
  REQUIRED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '应领数量',
  ISSUED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '实领数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  TOTAL_COST DECIMAL(20,4) NULL    COMMENT '总成本',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  LOCATION_ID BIGINT NULL    COMMENT '库位',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_mfg_material_issue_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_material_sku COMMENT '物料SKU';
                
   ALTER TABLE erp_md_uom COMMENT '计量单位';
                
   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_mfg_workcenter COMMENT '工作中心';
                
   ALTER TABLE erp_mfg_routing COMMENT '工艺路线';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_location COMMENT '库位';
                
   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_employee COMMENT '员工';
                
   ALTER TABLE erp_inv_batch COMMENT '批次';
                
   ALTER TABLE erp_mfg_bom COMMENT 'BOM';
                
   ALTER TABLE erp_mfg_routing_operation COMMENT '工艺路线工序';
                
   ALTER TABLE erp_mfg_workcenter_calendar COMMENT '工作中心日历';
                
   ALTER TABLE erp_mfg_workcenter_capacity COMMENT '工作中心产能';
                
   ALTER TABLE erp_mfg_mrp_plan COMMENT 'MRP计划';
                
   ALTER TABLE erp_mfg_forecast COMMENT '需求预测';
                
   ALTER TABLE erp_mfg_cost_rollup COMMENT '标准成本滚算';
                
   ALTER TABLE erp_mfg_bom_byproduct COMMENT 'BOM联副产品';
                
   ALTER TABLE erp_mfg_production_version COMMENT '生产版本';
                
   ALTER TABLE erp_mfg_bom_operation COMMENT 'BOM工艺';
                
   ALTER TABLE erp_mfg_mrp_plan_line COMMENT 'MRP计划行';
                
   ALTER TABLE erp_mfg_mrp_demand COMMENT 'MRP独立需求';
                
   ALTER TABLE erp_mfg_forecast_line COMMENT '需求预测行';
                
   ALTER TABLE erp_mfg_cost_rollup_line COMMENT '标准成本滚算行';
                
   ALTER TABLE erp_mfg_work_order COMMENT '工单';
                
   ALTER TABLE erp_mfg_bom_line COMMENT 'BOM行';
                
   ALTER TABLE erp_mfg_crp_load COMMENT 'CRP负荷';
                
   ALTER TABLE erp_mfg_work_order_line COMMENT '工单行';
                
   ALTER TABLE erp_mfg_subcontract_order COMMENT '委外加工单';
                
   ALTER TABLE erp_mfg_job_card COMMENT '作业卡';
                
   ALTER TABLE erp_mfg_cost_variance COMMENT '成本差异记录';
                
   ALTER TABLE erp_mfg_subcontract_order_line COMMENT '委外加工单行';
                
   ALTER TABLE erp_mfg_material_issue COMMENT '领料单';
                
   ALTER TABLE erp_mfg_job_card_time_log COMMENT '作业工时记录';
                
   ALTER TABLE erp_mfg_batch_genealogy COMMENT '批次追溯';
                
   ALTER TABLE erp_mfg_material_issue_line COMMENT '领料单行';
                
