-- app-erp-manufacturing indexes generated from model/app-erp-manufacturing.orm.xml
-- Dialect: postgresql.
-- This file is maintained separately from _create_erp-manufacturing.sql because the
-- platform _create.sql.xgen template (ddl.xlib CreateTables) does not emit CREATE INDEX.
-- Runtime: ddl.xlib AddIndex also applies these at app startup from the ORM model.
-- Run AFTER _create_erp-manufacturing.sql during manual production deployment.
-- Source of truth: model <indexes> definitions (106 indexes).
-- Regenerate: node scripts/add-orm-indexes.js
CREATE INDEX IDX_MFG_BOM_PRODUCT_ID ON erp_mfg_bom (product_id);
CREATE INDEX IDX_MFG_BOM_LINE_BOM_ID ON erp_mfg_bom_line (bom_id);
CREATE INDEX IDX_MFG_BOM_LINE_MATERIAL_ID ON erp_mfg_bom_line (material_id);
CREATE INDEX IDX_MFG_BOM_LINE_SKU_ID ON erp_mfg_bom_line (sku_id);
CREATE INDEX IDX_MFG_BOM_LINE_UO_M_ID ON erp_mfg_bom_line (uo_m_id);
CREATE INDEX IDX_MFG_BOM_LINE_OPERATION_ID ON erp_mfg_bom_line (operation_id);
CREATE INDEX IDX_MFG_BOM_LINE_WAREHOUSE_ID ON erp_mfg_bom_line (warehouse_id);
CREATE INDEX IDX_MFG_BOM_LINE_ALTERNATIVE_MATERIAL_ID ON erp_mfg_bom_line (alternative_material_id);
CREATE INDEX IDX_MFG_BOM_OPERATION_BOM_ID ON erp_mfg_bom_operation (bom_id);
CREATE INDEX IDX_MFG_BOM_OPERATION_OPERATION_ID ON erp_mfg_bom_operation (operation_id);
CREATE INDEX IDX_MFG_BOM_OPERATION_WORKCENTER_ID ON erp_mfg_bom_operation (workcenter_id);
CREATE INDEX IDX_MFG_BOM_BYPRODUCT_BOM_ID ON erp_mfg_bom_byproduct (bom_id);
CREATE INDEX IDX_MFG_BOM_BYPRODUCT_MATERIAL_ID ON erp_mfg_bom_byproduct (material_id);
CREATE INDEX IDX_MFG_BOM_BYPRODUCT_SKU_ID ON erp_mfg_bom_byproduct (sku_id);
CREATE INDEX IDX_MFG_BOM_BYPRODUCT_UO_M_ID ON erp_mfg_bom_byproduct (uo_m_id);
CREATE INDEX IDX_MFG_ROUTING_OPERATION_ROUTING_ID ON erp_mfg_routing_operation (routing_id);
CREATE INDEX IDX_MFG_ROUTING_OPERATION_WORKCENTER_ID ON erp_mfg_routing_operation (workcenter_id);
CREATE INDEX IDX_MFG_WORKCENTER_CALENDAR_WORKCENTER_ID ON erp_mfg_workcenter_calendar (workcenter_id);
CREATE INDEX IDX_MFG_WORKCENTER_CAPACITY_WORKCENTER_ID ON erp_mfg_workcenter_capacity (workcenter_id);
CREATE INDEX IDX_MFG_WORKCENTER_CAPACITY_MATERIAL_ID ON erp_mfg_workcenter_capacity (material_id);
CREATE INDEX IDX_MFG_CRP_LOAD_WORKCENTER_ID ON erp_mfg_crp_load (workcenter_id);
CREATE INDEX IDX_MFG_CRP_LOAD_WORK_ORDER_ID ON erp_mfg_crp_load (work_order_id);
CREATE INDEX IDX_MFG_WORK_ORDER_ORG_DOC_STATUS ON erp_mfg_work_order (org_id, doc_status);
CREATE INDEX IDX_MFG_WORK_ORDER_ORG_BUSINESS_DATE ON erp_mfg_work_order (org_id, business_date);
CREATE INDEX IDX_MFG_WORK_ORDER_BOM_ID ON erp_mfg_work_order (bom_id);
CREATE INDEX IDX_MFG_WORK_ORDER_ROUTING_ID ON erp_mfg_work_order (routing_id);
CREATE INDEX IDX_MFG_WORK_ORDER_PRODUCTION_VERSION_ID ON erp_mfg_work_order (production_version_id);
CREATE INDEX IDX_MFG_WORK_ORDER_SOURCE_MRP_PLAN_ID ON erp_mfg_work_order (source_mrp_plan_id);
CREATE INDEX IDX_MFG_WORK_ORDER_PRODUCT_ID ON erp_mfg_work_order (product_id);
CREATE INDEX IDX_MFG_WORK_ORDER_CURRENCY_ID ON erp_mfg_work_order (currency_id);
CREATE INDEX IDX_MFG_WORK_ORDER_SOURCE_SCHEDULE_ID ON erp_mfg_work_order (source_schedule_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_WORK_ORDER_ID ON erp_mfg_work_order_line (work_order_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_MATERIAL_ID ON erp_mfg_work_order_line (material_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_SKU_ID ON erp_mfg_work_order_line (sku_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_UO_M_ID ON erp_mfg_work_order_line (uo_m_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_SOURCE_WAREHOUSE_ID ON erp_mfg_work_order_line (source_warehouse_id);
CREATE INDEX IDX_MFG_WORK_ORDER_LINE_DEST_WAREHOUSE_ID ON erp_mfg_work_order_line (dest_warehouse_id);
CREATE INDEX IDX_MFG_PRODUCTION_VERSION_PRODUCT_ID ON erp_mfg_production_version (product_id);
CREATE INDEX IDX_MFG_PRODUCTION_VERSION_BOM_ID ON erp_mfg_production_version (bom_id);
CREATE INDEX IDX_MFG_PRODUCTION_VERSION_ROUTING_ID ON erp_mfg_production_version (routing_id);
CREATE INDEX IDX_MFG_MRP_PLAN_ORG_STATUS ON erp_mfg_mrp_plan (org_id, status);
CREATE INDEX IDX_MFG_MRP_PLAN_ORG_BUSINESS_DATE ON erp_mfg_mrp_plan (org_id, business_date);
CREATE INDEX IDX_MFG_MRP_PLAN_LINE_MRP_PLAN_ID ON erp_mfg_mrp_plan_line (mrp_plan_id);
CREATE INDEX IDX_MFG_MRP_PLAN_LINE_MATERIAL_ID ON erp_mfg_mrp_plan_line (material_id);
CREATE INDEX IDX_MFG_MRP_PLAN_LINE_UO_M_ID ON erp_mfg_mrp_plan_line (uo_m_id);
CREATE INDEX IDX_MFG_MRP_PLAN_LINE_PARENT_LINE_ID ON erp_mfg_mrp_plan_line (parent_line_id);
CREATE INDEX IDX_MFG_MRP_DEMAND_MRP_PLAN_ID ON erp_mfg_mrp_demand (mrp_plan_id);
CREATE INDEX IDX_MFG_MRP_DEMAND_MATERIAL_ID ON erp_mfg_mrp_demand (material_id);
CREATE INDEX IDX_MFG_MRP_DEMAND_UO_M_ID ON erp_mfg_mrp_demand (uo_m_id);
CREATE INDEX IDX_MFG_FORECAST_ORG_STATUS ON erp_mfg_forecast (org_id, status);
CREATE INDEX IDX_MFG_FORECAST_LINE_FORECAST_ID ON erp_mfg_forecast_line (forecast_id);
CREATE INDEX IDX_MFG_FORECAST_LINE_MATERIAL_ID ON erp_mfg_forecast_line (material_id);
CREATE INDEX IDX_MFG_FORECAST_LINE_WAREHOUSE_ID ON erp_mfg_forecast_line (warehouse_id);
CREATE INDEX IDX_MFG_FORECAST_LINE_UO_M_ID ON erp_mfg_forecast_line (uo_m_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_ORG_DOC_STATUS ON erp_mfg_material_issue (org_id, doc_status);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_ORG_BUSINESS_DATE ON erp_mfg_material_issue (org_id, business_date);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_WORK_ORDER_ID ON erp_mfg_material_issue (work_order_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_JOB_CARD_ID ON erp_mfg_material_issue (job_card_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_WAREHOUSE_ID ON erp_mfg_material_issue (warehouse_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_CURRENCY_ID ON erp_mfg_material_issue (currency_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_ISSUE_ID ON erp_mfg_material_issue_line (issue_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_MATERIAL_ID ON erp_mfg_material_issue_line (material_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_SKU_ID ON erp_mfg_material_issue_line (sku_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_UO_M_ID ON erp_mfg_material_issue_line (uo_m_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_WORK_ORDER_LINE_ID ON erp_mfg_material_issue_line (work_order_line_id);
CREATE INDEX IDX_MFG_MATERIAL_ISSUE_LINE_LOCATION_ID ON erp_mfg_material_issue_line (location_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_ORG_DOC_STATUS ON erp_mfg_subcontract_order (org_id, doc_status);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_ORG_BUSINESS_DATE ON erp_mfg_subcontract_order (org_id, business_date);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_WORK_ORDER_ID ON erp_mfg_subcontract_order (work_order_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_SUPPLIER_ID ON erp_mfg_subcontract_order (supplier_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_WORKCENTER_ID ON erp_mfg_subcontract_order (workcenter_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_ROUTING_ID ON erp_mfg_subcontract_order (routing_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_PRODUCTION_VERSION_ID ON erp_mfg_subcontract_order (production_version_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_PRODUCT_ID ON erp_mfg_subcontract_order (product_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_CURRENCY_ID ON erp_mfg_subcontract_order (currency_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_LINE_SUBCONTRACT_ORDER_ID ON erp_mfg_subcontract_order_line (subcontract_order_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_LINE_MATERIAL_ID ON erp_mfg_subcontract_order_line (material_id);
CREATE INDEX IDX_MFG_SUBCONTRACT_ORDER_LINE_UO_M_ID ON erp_mfg_subcontract_order_line (uo_m_id);
CREATE INDEX IDX_MFG_COST_ROLLUP_ORG_STATUS ON erp_mfg_cost_rollup (org_id, status);
CREATE INDEX IDX_MFG_COST_ROLLUP_ORG_BUSINESS_DATE ON erp_mfg_cost_rollup (org_id, business_date);
CREATE INDEX IDX_MFG_COST_ROLLUP_LINE_COST_ROLLUP_ID ON erp_mfg_cost_rollup_line (cost_rollup_id);
CREATE INDEX IDX_MFG_COST_ROLLUP_LINE_MATERIAL_ID ON erp_mfg_cost_rollup_line (material_id);
CREATE INDEX IDX_MFG_COST_ROLLUP_LINE_UO_M_ID ON erp_mfg_cost_rollup_line (uo_m_id);
CREATE INDEX IDX_MFG_COST_ROLLUP_LINE_CURRENCY_ID ON erp_mfg_cost_rollup_line (currency_id);
CREATE INDEX IDX_MFG_JOB_CARD_STATUS ON erp_mfg_job_card (status);
CREATE INDEX IDX_MFG_JOB_CARD_WORK_ORDER_ID ON erp_mfg_job_card (work_order_id);
CREATE INDEX IDX_MFG_JOB_CARD_OPERATION_ID ON erp_mfg_job_card (operation_id);
CREATE INDEX IDX_MFG_JOB_CARD_WORKCENTER_ID ON erp_mfg_job_card (workcenter_id);
CREATE INDEX IDX_MFG_JOB_CARD_SOURCE_SCHEDULE_ID ON erp_mfg_job_card (source_schedule_id);
CREATE INDEX IDX_MFG_JOB_CARD_TIME_LOG_JOB_CARD_ID ON erp_mfg_job_card_time_log (job_card_id);
CREATE INDEX IDX_MFG_JOB_CARD_TIME_LOG_WORK_ORDER_ID ON erp_mfg_job_card_time_log (work_order_id);
CREATE INDEX IDX_MFG_JOB_CARD_TIME_LOG_OPERATOR_ID ON erp_mfg_job_card_time_log (operator_id);
CREATE INDEX IDX_MFG_COST_VARIANCE_BUSINESS_DATE ON erp_mfg_cost_variance (business_date);
CREATE INDEX IDX_MFG_COST_VARIANCE_WORK_ORDER_ID ON erp_mfg_cost_variance (work_order_id);
CREATE INDEX IDX_MFG_COST_VARIANCE_MATERIAL_ID ON erp_mfg_cost_variance (material_id);
CREATE INDEX IDX_MFG_COST_VARIANCE_OPERATION_ID ON erp_mfg_cost_variance (operation_id);
CREATE INDEX IDX_MFG_COST_VARIANCE_WORKCENTER_ID ON erp_mfg_cost_variance (workcenter_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_WORK_ORDER_ID ON erp_mfg_batch_genealogy (work_order_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_JOB_CARD_ID ON erp_mfg_batch_genealogy (job_card_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_OPERATION_ID ON erp_mfg_batch_genealogy (operation_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_INPUT_LOT_ID ON erp_mfg_batch_genealogy (input_lot_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_INPUT_MATERIAL_ID ON erp_mfg_batch_genealogy (input_material_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_INPUT_UO_M_ID ON erp_mfg_batch_genealogy (input_uo_m_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_OUTPUT_LOT_ID ON erp_mfg_batch_genealogy (output_lot_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_OUTPUT_MATERIAL_ID ON erp_mfg_batch_genealogy (output_material_id);
CREATE INDEX IDX_MFG_BATCH_GENEALOGY_OUTPUT_UO_M_ID ON erp_mfg_batch_genealogy (output_uo_m_id);
