package app.erp.mnt.service;

/**
 * 维护域配置默认值集中入口。所有 {@code erp-mnt.*} 配置键经 {@link io.nop.api.core.config.AppConfig#var}
 * 读取时，统一经本接口提供默认值，避免散落在业务代码中。
 */
public interface ErpMntConfigs {

    static boolean autoGenerateDueVisits() {
        Boolean flag = io.nop.api.core.config.AppConfig.var(
                ErpMntConstants.CONFIG_AUTO_GENERATE_DUE_VISITS, ErpMntConstants.DEFAULT_AUTO_GENERATE_DUE_VISITS);
        return flag == null || flag;
    }

    static boolean equipmentStatusLinkEnabled() {
        Boolean flag = io.nop.api.core.config.AppConfig.var(
                ErpMntConstants.CONFIG_EQUIPMENT_STATUS_LINK_ENABLED, ErpMntConstants.DEFAULT_EQUIPMENT_STATUS_LINK_ENABLED);
        return flag == null || flag;
    }
}
