
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_auth_user(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_auth_user primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_department(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARENT_ID BIGINT NULL    COMMENT '上级部门',
  MANAGER_ID BIGINT NULL    COMMENT '部门负责人',
  COST_CENTER_ID BIGINT NULL    COMMENT '成本中心',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_department primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_position(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DEPARTMENT_ID BIGINT NULL    COMMENT '所属部门',
  JOB_GRADE VARCHAR(50) NULL    COMMENT '职级',
  JOB_CATEGORY VARCHAR(100) NULL    COMMENT '职位类别',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_position primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_employee(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工号',
  FIRST_NAME VARCHAR(100) NOT NULL    COMMENT '姓',
  LAST_NAME VARCHAR(100) NOT NULL    COMMENT '名',
  FULL_NAME VARCHAR(200) NULL    COMMENT '全名',
  GENDER INTEGER NOT NULL    COMMENT '性别',
  BIRTH_DATE DATE NULL    COMMENT '出生日期',
  ID_CARD_TYPE VARCHAR(50) NULL    COMMENT '证件类型',
  ID_CARD_NO VARCHAR(50) NULL    COMMENT '证件号码',
  EMAIL VARCHAR(200) NULL    COMMENT '电子邮箱',
  MOBILE_PHONE VARCHAR(20) NULL    COMMENT '手机号',
  MARITAL_STATUS INTEGER NULL    COMMENT '婚姻状况',
  NATIONALITY VARCHAR(50) NULL    COMMENT '国籍',
  EMERGENCY_CONTACT VARCHAR(100) NULL    COMMENT '紧急联系人',
  EMERGENCY_PHONE VARCHAR(20) NULL    COMMENT '紧急联系电话',
  DEPARTMENT_ID BIGINT NULL    COMMENT '部门',
  POSITION_ID BIGINT NULL    COMMENT '职位',
  JOB_TITLE VARCHAR(200) NULL    COMMENT '岗位名称',
  SUPERIOR_ID BIGINT NULL    COMMENT '直接上级',
  COST_CENTER_ID BIGINT NULL    COMMENT '默认成本中心',
  HIRE_DATE DATE NOT NULL    COMMENT '入职日期',
  PROBATION_END_DATE DATE NULL    COMMENT '试用期截止',
  REGULAR_DATE DATE NULL    COMMENT '转正日期',
  RESIGNATION_DATE DATE NULL    COMMENT '离职日期',
  RESIGNATION_REASON VARCHAR(500) NULL    COMMENT '离职原因',
  EMPLOYMENT_STATUS INTEGER NOT NULL    COMMENT '雇佣状态',
  EMPLOYEE_TYPE INTEGER NOT NULL    COMMENT '员工类型',
  BANK_ACCOUNT_ID BIGINT NULL    COMMENT '工资卡账户',
  SOCIAL_SECURITY_NO VARCHAR(50) NULL    COMMENT '社保号',
  TAX_FILE_NO VARCHAR(50) NULL    COMMENT '个税档案号',
  USER_ACCOUNT_ID BIGINT NULL    COMMENT '系统用户ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_employment_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '合同编号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  CONTRACT_TYPE INTEGER NOT NULL    COMMENT '合同类型',
  SIGN_DATE DATE NOT NULL    COMMENT '签订日期',
  START_DATE DATE NOT NULL    COMMENT '生效日期',
  END_DATE DATE NULL    COMMENT '到期日期',
  PROBATION_MONTHS INTEGER NULL    COMMENT '试用期月数',
  WORKING_HOURS_PER_WEEK DECIMAL(5,1) NULL    COMMENT '每周工时',
  ANNUAL_SALARY DECIMAL(20,4) NULL    COMMENT '年薪(税前)',
  MONTHLY_SALARY DECIMAL(20,4) NULL    COMMENT '月薪(税前)',
  SALARY_CURRENCY_ID BIGINT NULL    COMMENT '薪资币种',
  SALARY_PAY_METHOD VARCHAR(50) NULL    COMMENT '发薪方式',
  SOCIAL_INSURANCE_BASE DECIMAL(20,4) NULL    COMMENT '社保基数',
  HOUSING_FUND_BASE DECIMAL(20,4) NULL    COMMENT '公积金基数',
  STATUS INTEGER NOT NULL    COMMENT '合同状态',
  ATTACHMENT_ID BIGINT NULL    COMMENT '合同文件',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_employment_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_leave_request(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  LEAVE_TYPE INTEGER NOT NULL    COMMENT '休假类型',
  START_DATE DATE NOT NULL    COMMENT '开始日期',
  END_DATE DATE NOT NULL    COMMENT '结束日期',
  DURATION_DAYS DECIMAL(10,2) NULL    COMMENT '天数',
  REASON VARCHAR(500) NULL    COMMENT '请假原因',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  APPROVER_ID BIGINT NULL    COMMENT '审批人',
  APPROVED_AT DATETIME NULL    COMMENT '审批时间',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_leave_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_timesheet(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  PERIOD_FROM DATE NOT NULL    COMMENT '周期开始',
  PERIOD_TO DATE NOT NULL    COMMENT '周期结束',
  TOTAL_HOURS DECIMAL(10,2) NULL    COMMENT '总工时',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_timesheet primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_salary(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  YEAR INTEGER NOT NULL    COMMENT '年份',
  MONTH INTEGER NOT NULL    COMMENT '月份',
  BASIC_SALARY DECIMAL(20,4) NULL    COMMENT '基本工资',
  POSITION_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '岗位津贴',
  PERFORMANCE_BONUS DECIMAL(20,4) NULL    COMMENT '绩效奖金',
  OVERTIME_PAY DECIMAL(20,4) NULL    COMMENT '加班费',
  MEAL_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '餐补',
  TRANSPORT_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '交通补贴',
  OTHER_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '其他补贴',
  GROSS_SALARY DECIMAL(20,4) NULL    COMMENT '应发合计',
  SOCIAL_INSURANCE DECIMAL(20,4) NULL    COMMENT '社保个人部分',
  HOUSING_FUND DECIMAL(20,4) NULL    COMMENT '公积金个人部分',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '个税',
  OTHER_DEDUCTIONS DECIMAL(20,4) NULL    COMMENT '其他扣款',
  NET_SALARY DECIMAL(20,4) NULL    COMMENT '实发合计',
  PAYMENT_STATUS INTEGER NOT NULL    COMMENT '支付状态',
  PAYMENT_DATE DATE NULL    COMMENT '实发日期',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_salary primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_recruitment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  POSITION_ID BIGINT NULL    COMMENT '招聘职位',
  DEPARTMENT_ID BIGINT NULL    COMMENT '招聘部门',
  HEADCOUNT INTEGER default 1  NULL    COMMENT '招聘人数',
  CANDIDATE_NAME VARCHAR(200) NOT NULL    COMMENT '应聘者姓名',
  CANDIDATE_PHONE VARCHAR(20) NULL    COMMENT '联系电话',
  CANDIDATE_EMAIL VARCHAR(200) NULL    COMMENT '电子邮箱',
  SOURCE INTEGER NULL    COMMENT '来源',
  RESUME_ATTACHMENT_ID BIGINT NULL    COMMENT '简历附件',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  INTERVIEWER_ID BIGINT NULL    COMMENT '面试官',
  INTERVIEW_DATE DATE NULL    COMMENT '面试日期',
  OFFER_SALARY DECIMAL(20,4) NULL    COMMENT 'Offer薪资',
  HIRED_DATE DATE NULL    COMMENT '入职日期',
  EMPLOYEE_ID BIGINT NULL    COMMENT '关联员工',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_recruitment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_attendance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  DATE DATE NOT NULL    COMMENT '考勤日期',
  CLOCK_IN DATETIME NULL    COMMENT '签到时间',
  CLOCK_OUT DATETIME NULL    COMMENT '签退时间',
  WORK_HOURS DECIMAL(10,2) NULL    COMMENT '出勤时长',
  LATE_MINUTES INTEGER default 0  NULL    COMMENT '迟到分钟数',
  EARLY_LEAVE_MINUTES INTEGER default 0  NULL    COMMENT '早退分钟数',
  IS_ABSENT BOOLEAN default 0  NULL    COMMENT '是否旷工',
  SOURCE INTEGER NULL    COMMENT '来源',
  LEAVE_REQUEST_ID BIGINT NULL    COMMENT '关联休假',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_attendance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_timesheet_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TIMESHEET_ID BIGINT NOT NULL    COMMENT '工时表ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  WORK_DATE DATE NOT NULL    COMMENT '工作日期',
  PROJECT_ID BIGINT NULL    COMMENT '项目',
  TASK_ID BIGINT NULL    COMMENT '任务',
  ACTIVITY_TYPE VARCHAR(100) NULL    COMMENT '活动类型',
  HOURS DECIMAL(10,2) NOT NULL    COMMENT '小时数',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '工作内容',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_timesheet_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_auth_user COMMENT 'NopAuthUser';
                
   ALTER TABLE erp_hr_department COMMENT '部门';
                
   ALTER TABLE erp_hr_position COMMENT '职位';
                
   ALTER TABLE erp_hr_employee COMMENT '员工';
                
   ALTER TABLE erp_hr_employment_contract COMMENT '劳动合同';
                
   ALTER TABLE erp_hr_leave_request COMMENT '休假申请';
                
   ALTER TABLE erp_hr_timesheet COMMENT '工时表';
                
   ALTER TABLE erp_hr_salary COMMENT '薪酬记录';
                
   ALTER TABLE erp_hr_recruitment COMMENT '招聘记录';
                
   ALTER TABLE erp_hr_attendance COMMENT '考勤记录';
                
   ALTER TABLE erp_hr_timesheet_line COMMENT '工时表明细';
                
