
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_auth_user(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_auth_user primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_department(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARENT_ID BIGINT NULL    COMMENT '上级部门',
  MANAGER_ID BIGINT NULL    COMMENT '部门负责人',
  COST_CENTER_ID BIGINT NULL    COMMENT '成本中心',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_department primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_salary_simulation(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SOURCE_SALARY_ID BIGINT NULL    COMMENT '源薪酬记录',
  SIMULATION_PERIOD_YEAR INTEGER NOT NULL    COMMENT '模拟年份',
  SIMULATION_PERIOD_MONTH INTEGER NOT NULL    COMMENT '模拟月份',
  SIMULATION_NAME VARCHAR(200) NULL    COMMENT '模拟名称',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REVIEWER_ID BIGINT NULL    COMMENT '审批人',
  REVIEWED_AT DATETIME NULL    COMMENT '审批时间',
  CONVERTED_AT DATETIME NULL    COMMENT '转正式时间',
  CONVERTED_SALARY_ID BIGINT NULL    COMMENT '转正式薪酬ID',
  NOTES VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_salary_simulation primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_shift(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  NAME VARCHAR(200) NOT NULL    COMMENT '班次名称',
  SHIFT_TYPE INTEGER NOT NULL    COMMENT '班次类型',
  START_TIME VARCHAR(8) NOT NULL    COMMENT '上班时间',
  END_TIME VARCHAR(8) NOT NULL    COMMENT '下班时间',
  GRACE_LATE_MINUTES INTEGER default 15  NULL    COMMENT '迟到宽容分钟数',
  GRACE_EARLY_LEAVE_MINUTES INTEGER default 15  NULL    COMMENT '早退宽容分钟数',
  REQUIRE_CLOCK_IN BOOLEAN default 1  NULL    COMMENT '需签到',
  REQUIRE_CLOCK_OUT BOOLEAN default 1  NULL    COMMENT '需签退',
  REST_START_TIME VARCHAR(8) NULL    COMMENT '休息开始',
  REST_END_TIME VARCHAR(8) NULL    COMMENT '休息结束',
  TOTAL_WORK_MINUTES INTEGER NULL    COMMENT '标准工时(分钟)',
  ALLOW_OVERTIME BOOLEAN default 1  NULL    COMMENT '允许加班',
  COLOR_HEX VARCHAR(10) NULL    COMMENT '显示颜色',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '说明',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_shift primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_shift_rotation_pattern(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PATTERN_TYPE VARCHAR(50) NULL    COMMENT '轮换类型',
  PATTERN_DATA VARCHAR(2000) NULL    COMMENT '轮换序列',
  ROTATE_INTERVAL INTEGER NULL    COMMENT '轮换间隔(天)',
  START_DATE DATE NULL    COMMENT '起始日期',
  GROUP_ID BIGINT NULL    COMMENT '轮换组',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_shift_rotation_pattern primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_survey(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  TITLE VARCHAR(200) NOT NULL    COMMENT '问卷标题',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '问卷说明',
  SURVEY_TYPE INTEGER NOT NULL    COMMENT '调研类型',
  IS_ANONYMOUS BOOLEAN default 1  NULL    COMMENT '是否匿名',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '截止日期',
  TARGET_DEPARTMENT_ID BIGINT NULL    COMMENT '目标部门',
  INCLUDE_ENPS BOOLEAN default 0  NULL    COMMENT '包含eNPS',
  ENPS_QUESTION VARCHAR(500) NULL    COMMENT 'eNPS题面',
  REMINDER_DAYS INTEGER default 3  NULL    COMMENT '催填间隔天数',
  TOTAL_QUESTIONS INTEGER default 0  NULL    COMMENT '总题数',
  TOTAL_RESPONSES INTEGER default 0  NULL    COMMENT '总答卷数',
  COMPLETION_RATE DECIMAL(5,2) NULL    COMMENT '完成率',
  AVG_SCORE DECIMAL(5,2) NULL    COMMENT '平均分',
  ENPS_SCORE INTEGER NULL    COMMENT 'eNPS得分',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_survey primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_competency(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  CATEGORY INTEGER NOT NULL    COMMENT '分类',
  COMPETENCY_GROUP VARCHAR(100) NULL    COMMENT '能力组',
  IS_TECHNICAL BOOLEAN default 0  NULL    COMMENT '是否技术能力',
  PARENT_ID BIGINT NULL    COMMENT '上级胜任力',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_competency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_position(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DEPARTMENT_ID BIGINT NULL    COMMENT '所属部门',
  JOB_GRADE VARCHAR(50) NULL    COMMENT '职级',
  JOB_CATEGORY VARCHAR(100) NULL    COMMENT '职位类别',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_position primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_survey_question(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SURVEY_ID BIGINT NOT NULL    COMMENT '所属问卷',
  SORT_ORDER INTEGER NULL    COMMENT '排序号',
  QUESTION_TEXT VARCHAR(2000) NOT NULL    COMMENT '题目内容',
  QUESTION_TYPE INTEGER NOT NULL    COMMENT '题型',
  RATING_SCALE_MIN INTEGER default 1  NULL    COMMENT '评分最低分',
  RATING_SCALE_MAX INTEGER default 5  NULL    COMMENT '评分最高分',
  RATING_LABEL_MIN VARCHAR(100) NULL    COMMENT '最低分标签',
  RATING_LABEL_MAX VARCHAR(100) NULL    COMMENT '最高分标签',
  OPTIONS VARCHAR(2000) NULL    COMMENT '选项列表',
  DRIVER_CATEGORY INTEGER NULL    COMMENT '驱动因子分类',
  IS_REQUIRED BOOLEAN default 1  NULL    COMMENT '是否必填',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_survey_question primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_survey_result(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SURVEY_ID BIGINT NOT NULL    COMMENT '所属问卷',
  DEPARTMENT_ID BIGINT NULL    COMMENT '部门',
  TOTAL_RESPONSES INTEGER default 0  NULL    COMMENT '答卷数',
  AVG_SCORE DECIMAL(5,2) NULL    COMMENT '平均分',
  ENPS_SCORE INTEGER NULL    COMMENT 'eNPS得分',
  DRIVER_SCORES VARCHAR(2000) NULL    COMMENT '驱动因子得分',
  QUESTION_BREAKDOWN VARCHAR(4000) NULL    COMMENT '每题得分',
  TREND_DATA VARCHAR(4000) NULL    COMMENT '历史趋势',
  LAST_CALCULATED_AT DATETIME NULL    COMMENT '最后计算时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_survey_result primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_competency_level(
  ID BIGINT NOT NULL    COMMENT 'ID',
  COMPETENCY_ID BIGINT NOT NULL    COMMENT '胜任力',
  LEVEL_NUMBER INTEGER NOT NULL    COMMENT '等级编号',
  LEVEL_NAME VARCHAR(100) NULL    COMMENT '等级名称',
  BEHAVIORAL_ANCHOR VARCHAR(1000) NULL    COMMENT '行为锚定',
  SORT_ORDER INTEGER NULL    COMMENT '排序号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_competency_level primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_employee(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工号',
  FIRST_NAME VARCHAR(100) NOT NULL    COMMENT '姓',
  LAST_NAME VARCHAR(100) NOT NULL    COMMENT '名',
  FULL_NAME VARCHAR(200) NULL    COMMENT '全名',
  GENDER INTEGER NOT NULL    COMMENT '性别',
  BIRTH_DATE DATE NULL    COMMENT '出生日期',
  ID_CARD_TYPE VARCHAR(50) NULL    COMMENT '证件类型',
  ID_CARD_NO VARCHAR(50) NULL    COMMENT '证件号码',
  EMAIL VARCHAR(200) NULL    COMMENT '电子邮箱',
  MOBILE_PHONE VARCHAR(20) NULL    COMMENT '手机号',
  MARITAL_STATUS INTEGER NULL    COMMENT '婚姻状况',
  NATIONALITY VARCHAR(50) NULL    COMMENT '国籍',
  EMERGENCY_CONTACT VARCHAR(100) NULL    COMMENT '紧急联系人',
  EMERGENCY_PHONE VARCHAR(20) NULL    COMMENT '紧急联系电话',
  DEPARTMENT_ID BIGINT NULL    COMMENT '部门',
  POSITION_ID BIGINT NULL    COMMENT '职位',
  JOB_TITLE VARCHAR(200) NULL    COMMENT '岗位名称',
  SUPERIOR_ID BIGINT NULL    COMMENT '直接上级',
  COST_CENTER_ID BIGINT NULL    COMMENT '默认成本中心',
  HIRE_DATE DATE NOT NULL    COMMENT '入职日期',
  PROBATION_END_DATE DATE NULL    COMMENT '试用期截止',
  REGULAR_DATE DATE NULL    COMMENT '转正日期',
  RESIGNATION_DATE DATE NULL    COMMENT '离职日期',
  RESIGNATION_REASON VARCHAR(500) NULL    COMMENT '离职原因',
  EMPLOYMENT_STATUS INTEGER NOT NULL    COMMENT '雇佣状态',
  EMPLOYEE_TYPE INTEGER NOT NULL    COMMENT '员工类型',
  BANK_ACCOUNT_ID BIGINT NULL    COMMENT '工资卡账户',
  SOCIAL_SECURITY_NO VARCHAR(50) NULL    COMMENT '社保号',
  TAX_FILE_NO VARCHAR(50) NULL    COMMENT '个税档案号',
  USER_ACCOUNT_ID BIGINT NULL    COMMENT '系统用户ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_role_competency(
  ID BIGINT NOT NULL    COMMENT 'ID',
  POSITION_ID BIGINT NOT NULL    COMMENT '岗位',
  COMPETENCY_ID BIGINT NOT NULL    COMMENT '胜任力',
  REQUIRED_LEVEL INTEGER NOT NULL    COMMENT '要求等级',
  WEIGHT DECIMAL(5,2) default 1.0  NULL    COMMENT '权重',
  IS_CRITICAL BOOLEAN default 0  NULL    COMMENT '是否关键',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_role_competency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_employment_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '合同编号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  CONTRACT_TYPE INTEGER NOT NULL    COMMENT '合同类型',
  SIGN_DATE DATE NOT NULL    COMMENT '签订日期',
  START_DATE DATE NOT NULL    COMMENT '生效日期',
  END_DATE DATE NULL    COMMENT '到期日期',
  PROBATION_MONTHS INTEGER NULL    COMMENT '试用期月数',
  WORKING_HOURS_PER_WEEK DECIMAL(5,1) NULL    COMMENT '每周工时',
  ANNUAL_SALARY DECIMAL(20,4) NULL    COMMENT '年薪(税前)',
  MONTHLY_SALARY DECIMAL(20,4) NULL    COMMENT '月薪(税前)',
  SALARY_CURRENCY_ID BIGINT NULL    COMMENT '薪资币种',
  SALARY_PAY_METHOD VARCHAR(50) NULL    COMMENT '发薪方式',
  SOCIAL_INSURANCE_BASE DECIMAL(20,4) NULL    COMMENT '社保基数',
  HOUSING_FUND_BASE DECIMAL(20,4) NULL    COMMENT '公积金基数',
  STATUS INTEGER NOT NULL    COMMENT '合同状态',
  ATTACHMENT_ID BIGINT NULL    COMMENT '合同文件',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_employment_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_leave_request(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  LEAVE_TYPE INTEGER NOT NULL    COMMENT '休假类型',
  START_DATE DATE NOT NULL    COMMENT '开始日期',
  END_DATE DATE NOT NULL    COMMENT '结束日期',
  DURATION_DAYS DECIMAL(10,2) NULL    COMMENT '天数',
  REASON VARCHAR(500) NULL    COMMENT '请假原因',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  APPROVER_ID BIGINT NULL    COMMENT '审批人',
  APPROVED_AT DATETIME NULL    COMMENT '审批时间',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_leave_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_timesheet(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  PERIOD_FROM DATE NOT NULL    COMMENT '周期开始',
  PERIOD_TO DATE NOT NULL    COMMENT '周期结束',
  TOTAL_HOURS DECIMAL(10,2) NULL    COMMENT '总工时',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_timesheet primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_salary(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  YEAR INTEGER NOT NULL    COMMENT '年份',
  MONTH INTEGER NOT NULL    COMMENT '月份',
  BASIC_SALARY DECIMAL(20,4) NULL    COMMENT '基本工资',
  POSITION_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '岗位津贴',
  PERFORMANCE_BONUS DECIMAL(20,4) NULL    COMMENT '绩效奖金',
  OVERTIME_PAY DECIMAL(20,4) NULL    COMMENT '加班费',
  MEAL_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '餐补',
  TRANSPORT_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '交通补贴',
  OTHER_ALLOWANCE DECIMAL(20,4) NULL    COMMENT '其他补贴',
  GROSS_SALARY DECIMAL(20,4) NULL    COMMENT '应发合计',
  SOCIAL_INSURANCE DECIMAL(20,4) NULL    COMMENT '社保个人部分',
  HOUSING_FUND DECIMAL(20,4) NULL    COMMENT '公积金个人部分',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '个税',
  OTHER_DEDUCTIONS DECIMAL(20,4) NULL    COMMENT '其他扣款',
  NET_SALARY DECIMAL(20,4) NULL    COMMENT '实发合计',
  PAYMENT_STATUS INTEGER NOT NULL    COMMENT '支付状态',
  PAYMENT_DATE DATE NULL    COMMENT '实发日期',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_salary primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_recruitment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  POSITION_ID BIGINT NULL    COMMENT '招聘职位',
  DEPARTMENT_ID BIGINT NULL    COMMENT '招聘部门',
  HEADCOUNT INTEGER default 1  NULL    COMMENT '招聘人数',
  CANDIDATE_NAME VARCHAR(200) NOT NULL    COMMENT '应聘者姓名',
  CANDIDATE_PHONE VARCHAR(20) NULL    COMMENT '联系电话',
  CANDIDATE_EMAIL VARCHAR(200) NULL    COMMENT '电子邮箱',
  SOURCE INTEGER NULL    COMMENT '来源',
  RESUME_ATTACHMENT_ID BIGINT NULL    COMMENT '简历附件',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  INTERVIEWER_ID BIGINT NULL    COMMENT '面试官',
  INTERVIEW_DATE DATE NULL    COMMENT '面试日期',
  OFFER_SALARY DECIMAL(20,4) NULL    COMMENT 'Offer薪资',
  HIRED_DATE DATE NULL    COMMENT '入职日期',
  EMPLOYEE_ID BIGINT NULL    COMMENT '关联员工',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_recruitment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_shift_assignment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  SHIFT_ID BIGINT NOT NULL    COMMENT '班次',
  ASSIGNMENT_DATE DATE NOT NULL    COMMENT '排班日期',
  ACTUAL_START_TIME DATETIME NULL    COMMENT '实际签到时间',
  ACTUAL_END_TIME DATETIME NULL    COMMENT '实际签退时间',
  IS_ABSENT BOOLEAN default 0  NULL    COMMENT '是否缺勤',
  ABSENCE_REASON VARCHAR(50) NULL    COMMENT '缺勤原因',
  LEAVE_REQUEST_ID BIGINT NULL    COMMENT '关联休假',
  SWAP_REQUEST_ID BIGINT NULL    COMMENT '关联调换',
  REPLACED_BY_ASSIGNMENT_ID BIGINT NULL    COMMENT '被替换排班',
  STATUS VARCHAR(50) NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_shift_assignment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_shift_swap_request(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REQUESTER_ID BIGINT NOT NULL    COMMENT '申请人',
  TARGET_EMPLOYEE_ID BIGINT NULL    COMMENT '目标员工',
  SOURCE_ASSIGNMENT_ID BIGINT NOT NULL    COMMENT '原排班',
  TARGET_ASSIGNMENT_ID BIGINT NULL    COMMENT '目标排班',
  SWAP_DATE DATE NOT NULL    COMMENT '调换日期',
  REASON VARCHAR(500) NULL    COMMENT '调换原因',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  APPROVED_BY_ID BIGINT NULL    COMMENT '审批人',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_shift_swap_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_survey_response(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SURVEY_ID BIGINT NOT NULL    COMMENT '所属问卷',
  EMPLOYEE_ID BIGINT NULL    COMMENT '填写员工',
  RESPONDENT_HASH VARCHAR(100) NULL    COMMENT '匿名哈希',
  SUBMITTED_AT DATETIME NULL    COMMENT '提交时间',
  TIME_SPENT_SECONDS INTEGER NULL    COMMENT '填写耗时',
  IS_COMPLETE BOOLEAN default 0  NULL    COMMENT '是否完整',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_survey_response primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_employee_assessment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '被评估员工',
  ASSESSMENT_TYPE INTEGER NOT NULL    COMMENT '评估类型',
  ASSESSOR_ID BIGINT NULL    COMMENT '评估人',
  ASSESSMENT_DATE DATE NULL    COMMENT '评估日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  OVERALL_SCORE DECIMAL(5,2) NULL    COMMENT '综合评分',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_employee_assessment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_gap_analysis(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  COMPETENCY_ID BIGINT NOT NULL    COMMENT '胜任力',
  REQUIRED_LEVEL INTEGER NULL    COMMENT '要求等级',
  ACTUAL_LEVEL INTEGER NULL    COMMENT '实际等级',
  GAP_VALUE INTEGER NULL    COMMENT '差距值',
  GAP_SEVERITY INTEGER NULL    COMMENT '差距严重程度',
  ASSESSMENT_DATE DATE NULL    COMMENT '评估日期',
  ANALYSIS_DATE DATETIME NULL    COMMENT '分析日期',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_gap_analysis primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_development_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  PLAN_NAME VARCHAR(200) NULL    COMMENT '计划名称',
  TARGET_DATE DATE NULL    COMMENT '目标完成日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_development_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_attendance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  DATE DATE NOT NULL    COMMENT '考勤日期',
  CLOCK_IN DATETIME NULL    COMMENT '签到时间',
  CLOCK_OUT DATETIME NULL    COMMENT '签退时间',
  WORK_HOURS DECIMAL(10,2) NULL    COMMENT '出勤时长',
  LATE_MINUTES INTEGER default 0  NULL    COMMENT '迟到分钟数',
  EARLY_LEAVE_MINUTES INTEGER default 0  NULL    COMMENT '早退分钟数',
  IS_ABSENT BOOLEAN default 0  NULL    COMMENT '是否旷工',
  SOURCE INTEGER NULL    COMMENT '来源',
  LEAVE_REQUEST_ID BIGINT NULL    COMMENT '关联休假',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_attendance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_timesheet_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TIMESHEET_ID BIGINT NOT NULL    COMMENT '工时表ID',
  EMPLOYEE_ID BIGINT NOT NULL    COMMENT '员工',
  WORK_DATE DATE NOT NULL    COMMENT '工作日期',
  PROJECT_ID BIGINT NULL    COMMENT '项目',
  TASK_ID BIGINT NULL    COMMENT '任务',
  ACTIVITY_TYPE VARCHAR(100) NULL    COMMENT '活动类型',
  HOURS DECIMAL(10,2) NOT NULL    COMMENT '小时数',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '工作内容',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_timesheet_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_survey_answer(
  ID BIGINT NOT NULL    COMMENT 'ID',
  RESPONSE_ID BIGINT NOT NULL    COMMENT '答卷',
  QUESTION_ID BIGINT NOT NULL    COMMENT '题目',
  RATING_VALUE INTEGER NULL    COMMENT '评分值',
  SELECTED_OPTION VARCHAR(500) NULL    COMMENT '选项',
  OPEN_TEXT VARCHAR(4000) NULL    COMMENT '文本回答',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_survey_answer primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_assessment_detail(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ASSESSMENT_ID BIGINT NOT NULL    COMMENT '评估',
  COMPETENCY_ID BIGINT NOT NULL    COMMENT '胜任力',
  ACTUAL_LEVEL INTEGER NULL    COMMENT '实际等级',
  COMMENT VARCHAR(1000) NULL    COMMENT '评语',
  SOURCE_TYPE INTEGER NULL    COMMENT '来源类型',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_assessment_detail primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_hr_development_plan_item(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PLAN_ID BIGINT NOT NULL    COMMENT '发展计划',
  COMPETENCY_ID BIGINT NOT NULL    COMMENT '目标胜任力',
  GAP_ID BIGINT NULL    COMMENT '关联差距分析',
  TARGET_LEVEL INTEGER NOT NULL    COMMENT '目标等级',
  DEVELOPMENT_ACTION VARCHAR(500) NULL    COMMENT '发展行动',
  MENTOR_ID BIGINT NULL    COMMENT '导师',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '预计完成日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  PROGRESS_NOTE VARCHAR(1000) NULL    COMMENT '进度说明',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_hr_development_plan_item primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_auth_user COMMENT 'NopAuthUser';
                
   ALTER TABLE erp_hr_department COMMENT '部门';
                
   ALTER TABLE erp_hr_salary_simulation COMMENT '薪酬模拟';
                
   ALTER TABLE erp_hr_shift COMMENT '班次模板';
                
   ALTER TABLE erp_hr_shift_rotation_pattern COMMENT '轮换排班模板';
                
   ALTER TABLE erp_hr_survey COMMENT '问卷模板';
                
   ALTER TABLE erp_hr_competency COMMENT '胜任力字典';
                
   ALTER TABLE erp_hr_position COMMENT '职位';
                
   ALTER TABLE erp_hr_survey_question COMMENT '问卷题目';
                
   ALTER TABLE erp_hr_survey_result COMMENT '调研结果';
                
   ALTER TABLE erp_hr_competency_level COMMENT '胜任力等级';
                
   ALTER TABLE erp_hr_employee COMMENT '员工';
                
   ALTER TABLE erp_hr_role_competency COMMENT '岗位胜任力要求';
                
   ALTER TABLE erp_hr_employment_contract COMMENT '劳动合同';
                
   ALTER TABLE erp_hr_leave_request COMMENT '休假申请';
                
   ALTER TABLE erp_hr_timesheet COMMENT '工时表';
                
   ALTER TABLE erp_hr_salary COMMENT '薪酬记录';
                
   ALTER TABLE erp_hr_recruitment COMMENT '招聘记录';
                
   ALTER TABLE erp_hr_shift_assignment COMMENT '排班分配';
                
   ALTER TABLE erp_hr_shift_swap_request COMMENT '排班调换申请';
                
   ALTER TABLE erp_hr_survey_response COMMENT '答卷';
                
   ALTER TABLE erp_hr_employee_assessment COMMENT '员工评估';
                
   ALTER TABLE erp_hr_gap_analysis COMMENT '差距分析';
                
   ALTER TABLE erp_hr_development_plan COMMENT '发展计划';
                
   ALTER TABLE erp_hr_attendance COMMENT '考勤记录';
                
   ALTER TABLE erp_hr_timesheet_line COMMENT '工时表明细';
                
   ALTER TABLE erp_hr_survey_answer COMMENT '回答明细';
                
   ALTER TABLE erp_hr_assessment_detail COMMENT '评估明细';
                
   ALTER TABLE erp_hr_development_plan_item COMMENT '发展计划项';
                
