
CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  MATERIAL_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_warehouse(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_risk_register(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  RISK_DATE DATE NOT NULL    COMMENT '登记日期',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '风险描述',
  CATEGORY VARCHAR(100) NULL    COMMENT '风险类别',
  LIKELIHOOD INTEGER NOT NULL    COMMENT '发生可能性',
  SEVERITY INTEGER NOT NULL    COMMENT '影响严重性',
  RISK_SCORE INTEGER NULL    COMMENT '风险评分',
  MITIGATION VARCHAR(2000) NULL    COMMENT '缓解措施',
  OWNER_ID VARCHAR(36) NULL    COMMENT '责任人',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_risk_register primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_sampling_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  AQL_LEVEL VARCHAR(20) NOT NULL    COMMENT 'AQL 检验水平(如 II)',
  LOT_SIZE_FROM DECIMAL(20,4) NULL    COMMENT '批量下限',
  LOT_SIZE_TO DECIMAL(20,4) NULL    COMMENT '批量上限',
  SAMPLE_SIZE DECIMAL(20,4) NOT NULL    COMMENT '样本量',
  ACCEPT_NUMBER INTEGER NOT NULL    COMMENT '合格判定数(Ac)',
  REJECT_NUMBER INTEGER NOT NULL    COMMENT '不合格判定数(Re)',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_sampling_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  INSPECTION_TYPE VARCHAR(20) NOT NULL    COMMENT '检验类型',
  MATERIAL_ID BIGINT NULL    COMMENT '适用物料',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_quality_goal(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  TARGET_VALUE DECIMAL(20,4) NULL    COMMENT '目标值',
  CURRENT_VALUE DECIMAL(20,4) NULL    COMMENT '当前值',
  UNIT VARCHAR(50) NULL    COMMENT '单位',
  RESPONSIBLE_PERSON_ID BIGINT NULL    COMMENT '责任人',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_quality_goal primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_review(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REVIEW_DATE DATE NOT NULL    COMMENT '评审日期',
  REVIEW_TYPE VARCHAR(20) NOT NULL    COMMENT '评审类型',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  PARTICIPANTS VARCHAR(500) NULL    COMMENT '参与人员',
  CONCLUSION VARCHAR(2000) NULL    COMMENT '评审结论',
  ACTION_REQUIRED INTEGER default 0  NULL    COMMENT '是否需要措施',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  constraint PK_erp_qa_review primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_calibration(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  INSTRUMENT_NAME VARCHAR(200) NOT NULL    COMMENT '量具/设备名称',
  INSTRUMENT_CODE VARCHAR(100) NULL    COMMENT '量具编号',
  BUSINESS_DATE DATE NOT NULL    COMMENT '校准日期',
  STANDARD_REF VARCHAR(200) NULL    COMMENT '参考标准',
  MEASURED_VALUE VARCHAR(100) NULL    COMMENT '测量值',
  TARGET_VALUE VARCHAR(20) NULL    COMMENT '目标值',
  TOLERANCE VARCHAR(20) NULL    COMMENT '允差',
  RESULT VARCHAR(20) NOT NULL    COMMENT '校准结果',
  NEXT_CALIBRATION_DATE DATE NULL    COMMENT '下次校准日期',
  CALIBRATED_BY BIGINT NULL    COMMENT '校准人(职员)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  constraint PK_erp_qa_calibration primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  INSPECTION_TYPE VARCHAR(20) NOT NULL    COMMENT '检验类型',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  RELATED_LINE_CODE VARCHAR(50) NULL    COMMENT '关联单据行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  TEMPLATE_ID BIGINT NULL    COMMENT '质检模板',
  SUPPLIER_ID BIGINT NULL    COMMENT '供应商',
  WAREHOUSE_ID BIGINT NULL    COMMENT '仓库',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  INSPECTION_DATE DATE NOT NULL    COMMENT '检验日期',
  LOT_QUANTITY DECIMAL(20,4) NULL    COMMENT '批量',
  SAMPLE_QUANTITY DECIMAL(20,4) NULL    COMMENT '抽样数量',
  INSPECTOR_ID BIGINT NULL    COMMENT '检验员(职员)',
  RESULT VARCHAR(20) NOT NULL    COMMENT '质检结果',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(质量结论已回写业务单据)',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  constraint PK_erp_qa_inspection primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_template_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TEMPLATE_ID BIGINT NOT NULL    COMMENT '模板ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  PARAMETER_NAME VARCHAR(200) NOT NULL    COMMENT '检验参数名称',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  UNIT VARCHAR(50) NULL    COMMENT '计量单位',
  IS_REQUIRED INTEGER default 1  NOT NULL    COMMENT '是否必检',
  INSPECTION_METHOD VARCHAR(200) NULL    COMMENT '检验方法',
  SORT_NUM INTEGER default 0  NULL    COMMENT '排序',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_template_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_spc_chart(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CHART_TYPE VARCHAR(20) NOT NULL    COMMENT '图类型',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  INSPECTION_TYPE_ID BIGINT NULL    COMMENT '质检模板',
  PARAMETER_ID BIGINT NOT NULL    COMMENT '关键检验参数',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  SUBGROUP_SIZE INTEGER default 5  NULL    COMMENT '子组样本量 n',
  SAMPLING_FREQUENCY VARCHAR(100) NULL    COMMENT '采样频率',
  CL_CENTER_TYPE VARCHAR(20) default 'AUTO_FROM_DATA'  NOT NULL    COMMENT '中心线计算方式',
  RULE_SET VARCHAR(100) default '1,2,3,4'  NULL    COMMENT '判异规则集(逗号分隔)',
  ALARM_THRESHOLD INTEGER default 1  NULL    COMMENT '预警阈值(违规次数)',
  UCL DECIMAL(20,6) NULL    COMMENT '控制上限(UCL)',
  LCL DECIMAL(20,6) NULL    COMMENT '控制下限(LCL)',
  CL DECIMAL(20,6) NULL    COMMENT '中心线(CL)',
  CALC_STATUS VARCHAR(20) default 'PENDING'  NOT NULL    COMMENT '计算状态',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_spc_chart primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  INSPECTION_ID BIGINT NOT NULL    COMMENT '质检单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  PARAMETER_ID BIGINT NULL    COMMENT '检验参数',
  PARAMETER_NAME VARCHAR(200) NULL    COMMENT '检验参数名称',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  MEASURED_VALUE VARCHAR(100) NULL    COMMENT '实测值',
  UNIT VARCHAR(50) NULL    COMMENT '计量单位',
  RESULT VARCHAR(20) NOT NULL    COMMENT '行结果',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_non_conformance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  NCR_DATE DATE NOT NULL    COMMENT '报告日期',
  SOURCE_TYPE VARCHAR(50) NULL    COMMENT '来源类型',
  SOURCE_CODE VARCHAR(50) NULL    COMMENT '来源单号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  INSPECTION_ID BIGINT NULL    COMMENT '质检单ID',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '不合格数量',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '问题描述',
  SEVERITY VARCHAR(20) NOT NULL    COMMENT '严重程度',
  DISPOSITION_TYPE VARCHAR(20) NULL    COMMENT '处理决定',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  SUPPLIER_ID BIGINT NULL    COMMENT '供应商',
  PARAMETER_NAME VARCHAR(200) NULL    COMMENT '不合格参数',
  MEASURED_VALUE VARCHAR(100) NULL    COMMENT '实测值',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  ASSIGNED_TO BIGINT NULL    COMMENT '责任人',
  RESOLVED_BY BIGINT NULL    COMMENT '解决人',
  RESOLVED_AT DATETIME(3) NULL    COMMENT '解决时间',
  RESOLUTION VARCHAR(2000) NULL    COMMENT '解决措施',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(报废处置已生成凭证)',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  RETURN_CODE VARCHAR(50) NULL    COMMENT '关联退货单号(RETURN 处置编排退货域后登记)',
  constraint PK_erp_qa_non_conformance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_spc_sample(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CHART_ID BIGINT NOT NULL    COMMENT '控制图ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SUBGROUP_NO INTEGER NOT NULL    COMMENT '子组序号',
  SAMPLE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '采样时间',
  MEASURED_VALUES VARCHAR(2000) NULL    COMMENT '子组实测值(JSON 数组)',
  MEAN DECIMAL(20,6) NULL    COMMENT '子组均值 X̄',
  `RANGE` DECIMAL(20,6) NULL    COMMENT '子组极差 R',
  STD_DEV DECIMAL(20,6) NULL    COMMENT '子组标准差 s',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '数据来源单据类型',
  SOURCE_CODE VARCHAR(50) NULL    COMMENT '数据来源单号',
  SOURCE_LINE_CODE VARCHAR(50) NULL    COMMENT '数据来源行号',
  INSPECTOR_ID BIGINT NULL    COMMENT '检验员',
  VIOLATED_RULES VARCHAR(100) NULL    COMMENT '违反的判异规则(逗号分隔)',
  IS_OUT_OF_CONTROL BOOLEAN default 0  NULL    COMMENT '是否失控',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  DEFECT_COUNT INTEGER NULL    COMMENT '缺陷数(计数型 P/NP/C/U)',
  INSPECTED_COUNT INTEGER NULL    COMMENT '检验数(计数型 P/NP/C/U)',
  constraint PK_erp_qa_spc_sample primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_spc_capability(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CHART_ID BIGINT NOT NULL    COMMENT '控制图ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PERIOD_FROM DATE NOT NULL    COMMENT '分析周期起',
  PERIOD_TO DATE NOT NULL    COMMENT '分析周期止',
  SAMPLE_COUNT INTEGER NULL    COMMENT '样本数(子组数)',
  TOTAL_OBSERVATIONS INTEGER NULL    COMMENT '总观测点数',
  GRAND_MEAN DECIMAL(20,6) NULL    COMMENT '总均值 X̄̄',
  OVERALL_STD_DEV DECIMAL(20,6) NULL    COMMENT '总体标准差(用于 Pp/Ppk)',
  WITHIN_STD_DEV DECIMAL(20,6) NULL    COMMENT '组内标准差 σ̂=R̄/d2(用于 Cp/Cpk)',
  CP DECIMAL(20,6) NULL    COMMENT '过程能力指数 Cp',
  CPK DECIMAL(20,6) NULL    COMMENT '过程能力指数 Cpk',
  PP DECIMAL(20,6) NULL    COMMENT '过程性能指数 Pp',
  PPK DECIMAL(20,6) NULL    COMMENT '过程性能指数 Ppk',
  CPM DECIMAL(20,6) NULL    COMMENT '偏度修正 Cpm',
  CAPABILITY_LEVEL VARCHAR(20) NULL    COMMENT '能力等级评定',
  IS_STABLE BOOLEAN NULL    COMMENT '过程是否统计受控',
  CALCULATED_BY VARCHAR(36) NULL    COMMENT '计算人',
  CALCULATED_AT DATETIME(3) NULL    COMMENT '计算时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_spc_capability primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_action(
  ID BIGINT NOT NULL    COMMENT 'ID',
  NCR_ID BIGINT NOT NULL    COMMENT '不合格品报告ID',
  ACTION_TYPE VARCHAR(20) NOT NULL    COMMENT '措施类型',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '措施描述',
  RESPONSIBLE_PERSON BIGINT NULL    COMMENT '负责人',
  DUE_DATE DATE NULL    COMMENT '计划完成日期',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  COMPLETED_BY BIGINT NULL    COMMENT '完成人',
  COMPLETED_AT DATETIME(3) NULL    COMMENT '完成时间',
  VERIFICATION_PERSON BIGINT NULL    COMMENT '验证人',
  VERIFICATION_DATE DATE NULL    COMMENT '验证日期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_action primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_recall(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  RECALL_NAME VARCHAR(200) NOT NULL    COMMENT '召回名称',
  TRIGGER_TYPE VARCHAR(20) NOT NULL    COMMENT '触发类型',
  SOURCE_NCR_ID BIGINT NULL    COMMENT '来源NCR(弱指针)',
  MATERIAL_ID BIGINT NULL    COMMENT '召回物料',
  BATCH_ID BIGINT NULL    COMMENT '召回批次(弱指针→ErpInvBatch)',
  SERIAL_NO VARCHAR(50) NULL    COMMENT '召回序列号',
  ROOT_CAUSE VARCHAR(2000) NULL    COMMENT '根本原因',
  SEVERITY_LEVEL VARCHAR(20) NOT NULL    COMMENT '严重程度',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  NOTIFY_CUSTOMER BOOLEAN default 0  NULL    COMMENT '已通知客户',
  STATUS VARCHAR(20) NOT NULL    COMMENT '召回状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审批人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审批时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_recall primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_recall_target(
  ID BIGINT NOT NULL    COMMENT 'ID',
  RECALL_ID BIGINT NOT NULL    COMMENT '召回事件',
  PARTNER_ID BIGINT NULL    COMMENT '受影响客户',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  SERIAL_NO VARCHAR(50) NULL    COMMENT '序列号',
  SALES_DELIVERY_ID BIGINT NULL    COMMENT '销售出库单(弱指针)',
  SHIPPED_QTY DECIMAL(20,4) NULL    COMMENT '发货数量',
  NOTIFIED_AT DATETIME(3) NULL    COMMENT '通知时间',
  NOTIFIED_BY VARCHAR(36) NULL    COMMENT '通知人',
  RETURN_STATUS VARCHAR(20) NOT NULL    COMMENT '退货状态',
  GENERATED_RETURN_ID BIGINT NULL    COMMENT '已生成退货单(弱指针)',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_recall_target primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_md_employee COMMENT '职员';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_qa_risk_register COMMENT '风险登记';
                
   ALTER TABLE erp_qa_sampling_plan COMMENT '抽样方案';
                
   ALTER TABLE erp_qa_inspection_template COMMENT '质检模板';
                
   ALTER TABLE erp_qa_quality_goal COMMENT '质量目标';
                
   ALTER TABLE erp_qa_review COMMENT '质量评审';
                
   ALTER TABLE erp_qa_calibration COMMENT '量具校准';
                
   ALTER TABLE erp_qa_inspection COMMENT '质检单';
                
   ALTER TABLE erp_qa_inspection_template_line COMMENT '质检模板行';
                
   ALTER TABLE erp_qa_spc_chart COMMENT 'SPC 控制图配置';
                
   ALTER TABLE erp_qa_inspection_line COMMENT '质检单行';
                
   ALTER TABLE erp_qa_non_conformance COMMENT '不合格品报告';
                
   ALTER TABLE erp_qa_spc_sample COMMENT 'SPC 样本数据';
                
   ALTER TABLE erp_qa_spc_capability COMMENT 'SPC 过程能力分析';
                
   ALTER TABLE erp_qa_action COMMENT '纠正预防措施';
                
   ALTER TABLE erp_qa_recall COMMENT '召回事件';
                
   ALTER TABLE erp_qa_recall_target COMMENT '召回目标';
                
