
CREATE TABLE erp_qa_inspection(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  INSPECTION_TYPE INTEGER NOT NULL    COMMENT '检验类型',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  RELATED_LINE_CODE VARCHAR(50) NULL    COMMENT '关联单据行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SUPPLIER_ID BIGINT NULL    COMMENT '供应商',
  WAREHOUSE_ID BIGINT NULL    COMMENT '仓库',
  INSPECTION_DATE DATE NOT NULL    COMMENT '检验日期',
  LOT_QUANTITY DECIMAL(20,4) NULL    COMMENT '批量',
  SAMPLE_QUANTITY DECIMAL(20,4) NULL    COMMENT '抽样数量',
  INSPECTOR_ID BIGINT NULL    COMMENT '检验员(职员)',
  RESULT INTEGER NOT NULL    COMMENT '质检结果',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账(质量结论已回写业务单据)',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY BIGINT NULL    COMMENT '过账人',
  APPROVED_BY BIGINT NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  INSPECTION_TYPE INTEGER NOT NULL    COMMENT '检验类型',
  MATERIAL_ID BIGINT NULL    COMMENT '适用物料',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_non_conformance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  NCR_DATE DATE NOT NULL    COMMENT '报告日期',
  SOURCE_TYPE VARCHAR(50) NULL    COMMENT '来源类型',
  SOURCE_CODE VARCHAR(50) NULL    COMMENT '来源单号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '不合格数量',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '问题描述',
  SEVERITY INTEGER NOT NULL    COMMENT '严重程度',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ASSIGNED_TO BIGINT NULL    COMMENT '责任人',
  RESOLVED_BY BIGINT NULL    COMMENT '解决人',
  RESOLVED_AT DATETIME NULL    COMMENT '解决时间',
  RESOLUTION VARCHAR(2000) NULL    COMMENT '解决措施',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_non_conformance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_risk_register(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  RISK_DATE DATE NOT NULL    COMMENT '登记日期',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '风险描述',
  CATEGORY VARCHAR(100) NULL    COMMENT '风险类别',
  LIKELIHOOD INTEGER NOT NULL    COMMENT '发生可能性',
  SEVERITY INTEGER NOT NULL    COMMENT '影响严重性',
  RISK_SCORE INTEGER NULL    COMMENT '风险评分',
  MITIGATION VARCHAR(2000) NULL    COMMENT '缓解措施',
  OWNER_ID BIGINT NULL    COMMENT '责任人',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_risk_register primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_quality_goal(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  TARGET_VALUE DECIMAL(20,4) NULL    COMMENT '目标值',
  CURRENT_VALUE DECIMAL(20,4) NULL    COMMENT '当前值',
  UNIT VARCHAR(50) NULL    COMMENT '单位',
  RESPONSIBLE_PERSON_ID BIGINT NULL    COMMENT '责任人',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_quality_goal primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_review(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REVIEW_DATE DATE NOT NULL    COMMENT '评审日期',
  REVIEW_TYPE INTEGER NOT NULL    COMMENT '评审类型',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  PARTICIPANTS VARCHAR(500) NULL    COMMENT '参与人员',
  CONCLUSION VARCHAR(2000) NULL    COMMENT '评审结论',
  ACTION_REQUIRED INTEGER default 0  NULL    COMMENT '是否需要措施',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_review primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_sampling_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  AQL_LEVEL VARCHAR(20) NOT NULL    COMMENT 'AQL 检验水平(如 II)',
  LOT_SIZE_FROM DECIMAL(20,4) NULL    COMMENT '批量下限',
  LOT_SIZE_TO DECIMAL(20,4) NULL    COMMENT '批量上限',
  SAMPLE_SIZE DECIMAL(20,4) NOT NULL    COMMENT '样本量',
  ACCEPT_NUMBER INTEGER NOT NULL    COMMENT '合格判定数(Ac)',
  REJECT_NUMBER INTEGER NOT NULL    COMMENT '不合格判定数(Re)',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_sampling_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_calibration(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  INSTRUMENT_NAME VARCHAR(200) NOT NULL    COMMENT '量具/设备名称',
  INSTRUMENT_CODE VARCHAR(100) NULL    COMMENT '量具编号',
  BUSINESS_DATE DATE NOT NULL    COMMENT '校准日期',
  STANDARD_REF VARCHAR(200) NULL    COMMENT '参考标准',
  MEASURED_VALUE DECIMAL(20,6) NULL    COMMENT '测量值',
  TARGET_VALUE DECIMAL(20,6) NULL    COMMENT '目标值',
  TOLERANCE DECIMAL(20,6) NULL    COMMENT '允差',
  RESULT INTEGER NOT NULL    COMMENT '校准结果',
  NEXT_CALIBRATION_DATE DATE NULL    COMMENT '下次校准日期',
  CALIBRATED_BY BIGINT NULL    COMMENT '校准人(职员)',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_calibration primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  INSPECTION_ID BIGINT NOT NULL    COMMENT '质检单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  PARAMETER_ID BIGINT NULL    COMMENT '检验参数',
  PARAMETER_NAME VARCHAR(200) NULL    COMMENT '检验参数名称',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  MEASURED_VALUE DECIMAL(20,6) NULL    COMMENT '实测值',
  UNIT VARCHAR(50) NULL    COMMENT '计量单位',
  RESULT INTEGER NOT NULL    COMMENT '行结果',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_inspection_template_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TEMPLATE_ID BIGINT NOT NULL    COMMENT '模板ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  PARAMETER_NAME VARCHAR(200) NOT NULL    COMMENT '检验参数名称',
  SPEC_MIN DECIMAL(20,6) NULL    COMMENT '规格下限',
  SPEC_MAX DECIMAL(20,6) NULL    COMMENT '规格上限',
  UNIT VARCHAR(50) NULL    COMMENT '计量单位',
  IS_REQUIRED INTEGER default 1  NOT NULL    COMMENT '是否必检',
  SORT_NUM INTEGER default 0  NULL    COMMENT '排序',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_inspection_template_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_qa_action(
  ID BIGINT NOT NULL    COMMENT 'ID',
  NCR_ID BIGINT NOT NULL    COMMENT '不合格品报告ID',
  ACTION_TYPE INTEGER NOT NULL    COMMENT '措施类型',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '措施描述',
  RESPONSIBLE_PERSON BIGINT NULL    COMMENT '负责人',
  DUE_DATE DATE NULL    COMMENT '计划完成日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  COMPLETED_BY BIGINT NULL    COMMENT '完成人',
  COMPLETED_AT DATETIME NULL    COMMENT '完成时间',
  VERIFICATION_PERSON BIGINT NULL    COMMENT '验证人',
  VERIFICATION_DATE DATE NULL    COMMENT '验证日期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_qa_action primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_qa_inspection COMMENT '质检单';
                
   ALTER TABLE erp_qa_inspection_template COMMENT '质检模板';
                
   ALTER TABLE erp_qa_non_conformance COMMENT '不合格品报告';
                
   ALTER TABLE erp_qa_risk_register COMMENT '风险登记';
                
   ALTER TABLE erp_qa_quality_goal COMMENT '质量目标';
                
   ALTER TABLE erp_qa_review COMMENT '质量评审';
                
   ALTER TABLE erp_qa_sampling_plan COMMENT '抽样方案';
                
   ALTER TABLE erp_qa_calibration COMMENT '量具校准';
                
   ALTER TABLE erp_qa_inspection_line COMMENT '质检单行';
                
   ALTER TABLE erp_qa_inspection_template_line COMMENT '质检模板行';
                
   ALTER TABLE erp_qa_action COMMENT '纠正预防措施';
                
