
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_material(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_format(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FORMAT_NAME VARCHAR(200) NOT NULL    COMMENT '格式名称',
  FORMAT_STANDARD INTEGER NOT NULL    COMMENT 'EDI 标准',
  DIRECTION INTEGER NOT NULL    COMMENT '方向',
  NEEDS_WEB_SERVICE INTEGER default 0  NOT NULL    COMMENT '需要 WebService',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_format primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_code_mapping(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MAPPING_TYPE INTEGER NOT NULL    COMMENT '映射类型',
  INTERNAL_CODE VARCHAR(100) NOT NULL    COMMENT '内部代码',
  EXTERNAL_CODE VARCHAR(100) NOT NULL    COMMENT '外部代码',
  PARTNER_ID BIGINT NULL    COMMENT 'Trading Partner',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_code_mapping primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_doc(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '事务编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FORMAT_ID BIGINT NULL    COMMENT 'EDI 格式',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  STATE INTEGER NOT NULL    COMMENT '状态',
  BLOCKING_LEVEL INTEGER default 10  NOT NULL    COMMENT '阻断级别',
  ERROR VARCHAR(2000) NULL    COMMENT '错误信息',
  RETRY_COUNT INTEGER default 0  NOT NULL    COMMENT '重试次数',
  ATTACHMENT_ID BIGINT NULL    COMMENT '附件（EDI 报文文件）',
  SENT_AT DATETIME NULL    COMMENT '发送时间',
  ACKNOWLEDGED_AT DATETIME NULL    COMMENT '确认时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_doc primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_asn(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT 'ASN 编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SOURCE_EDI_DOC_ID BIGINT NULL    COMMENT '来源 EDI 文档',
  PARTNER_ID BIGINT NULL    COMMENT '发货方（供应商）',
  SHIPMENT_DATE DATE NULL    COMMENT '发货日期',
  ESTIMATED_ARRIVAL_DATE DATE NULL    COMMENT '预计到货日期',
  TRACKING_NO VARCHAR(100) NULL    COMMENT '物流单号',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联采购订单类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联采购订单号',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_asn primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EDI_DOC_ID BIGINT NULL    COMMENT 'EDI 事务 ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  DIRECTION INTEGER NOT NULL    COMMENT '方向',
  REQUEST_PAYLOAD LONGTEXT NULL    COMMENT '请求报文',
  RESPONSE_PAYLOAD LONGTEXT NULL    COMMENT '响应报文',
  RESULT_CODE VARCHAR(50) NULL    COMMENT '结果码',
  RESULT_MSG VARCHAR(500) NULL    COMMENT '结果消息',
  LOG_TIME DATETIME NOT NULL    COMMENT '日志时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_asn_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ASN_ID BIGINT NOT NULL    COMMENT 'ASN ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  SUPPLIER_PART_NO VARCHAR(100) NULL    COMMENT '供应商料号',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '订单数量',
  SHIPPED_QTY DECIMAL(20,4) NULL    COMMENT '发货数量',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_asn_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_md_md_material COMMENT 'ErpMdMaterial';
                
   ALTER TABLE erp_b2b_edi_format COMMENT 'EDI 格式配置';
                
   ALTER TABLE erp_b2b_code_mapping COMMENT '内外代码映射';
                
   ALTER TABLE erp_b2b_edi_doc COMMENT 'EDI 事务';
                
   ALTER TABLE erp_b2b_asn COMMENT '提前发货通知';
                
   ALTER TABLE erp_b2b_edi_log COMMENT 'EDI 交互日志';
                
   ALTER TABLE erp_b2b_asn_line COMMENT 'ASN 明细行';
                
