
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_material(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_format(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FORMAT_NAME VARCHAR(200) NOT NULL    COMMENT '格式名称',
  FORMAT_STANDARD INTEGER NOT NULL    COMMENT 'EDI 标准',
  DIRECTION INTEGER NOT NULL    COMMENT '方向',
  NEEDS_WEB_SERVICE INTEGER default 0  NOT NULL    COMMENT '需要 WebService',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_format primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_code_mapping(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MAPPING_TYPE INTEGER NOT NULL    COMMENT '映射类型',
  INTERNAL_CODE VARCHAR(100) NOT NULL    COMMENT '内部代码',
  EXTERNAL_CODE VARCHAR(100) NOT NULL    COMMENT '外部代码',
  PARTNER_ID BIGINT NULL    COMMENT 'Trading Partner',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_code_mapping primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_partner_profile(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARTNER_ID BIGINT NULL    COMMENT '关联伙伴',
  PARTNER_NAME VARCHAR(200) NOT NULL    COMMENT '伙伴名称',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  PROTOCOL INTEGER NOT NULL    COMMENT '传输协议',
  TRANSPORT_ENDPOINT VARCHAR(500) NULL    COMMENT '传输端点',
  AUTH_METHOD INTEGER NOT NULL    COMMENT '认证方式',
  WEBHOOK_SECRET VARCHAR(500) NULL    COMMENT 'Webhook密钥',
  CERT_EXPIRY DATE NULL    COMMENT '证书过期日期',
  CERT_FINGERPRINT VARCHAR(200) NULL    COMMENT '证书指纹',
  ALLOWED_FORMATS VARCHAR(500) NULL    COMMENT '支持格式(JSON)',
  TIMEZONE VARCHAR(50) NULL    COMMENT '时区',
  CONTACT_NAME VARCHAR(100) NULL    COMMENT '联系人姓名',
  CONTACT_EMAIL VARCHAR(200) NULL    COMMENT '联系邮箱',
  CONTACT_PHONE VARCHAR(50) NULL    COMMENT '联系电话',
  NOTES VARCHAR(1000) NULL    COMMENT '备注',
  GO_LIVE_DATE DATE NULL    COMMENT '上线日期',
  ARCHIVED_AT DATETIME NULL    COMMENT '归档日期',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_partner_profile primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_mft_certificate(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARTNER_ID BIGINT NULL    COMMENT '合作伙伴',
  CERT_NAME VARCHAR(200) NOT NULL    COMMENT '证书名称',
  CERT_TYPE VARCHAR(50) NOT NULL    COMMENT '证书类型',
  ALGORITHM VARCHAR(50) NOT NULL    COMMENT '算法',
  KEY_SIZE INTEGER default 2048  NULL    COMMENT '密钥长度',
  ISSUER_NAME VARCHAR(200) NULL    COMMENT '颁发者',
  SUBJECT_NAME VARCHAR(200) NULL    COMMENT '主题',
  SERIAL_NO VARCHAR(100) NULL    COMMENT '序列号',
  FINGERPRINT_SHA256 VARCHAR(100) NULL    COMMENT 'SHA-256指纹',
  ISSUED_AT DATE NULL    COMMENT '颁发日期',
  EXPIRES_AT DATE NOT NULL    COMMENT '过期日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_mft_certificate primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_doc(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '事务编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FORMAT_ID BIGINT NULL    COMMENT 'EDI 格式',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  STATE INTEGER NOT NULL    COMMENT '状态',
  BLOCKING_LEVEL INTEGER default 10  NOT NULL    COMMENT '阻断级别',
  ERROR VARCHAR(2000) NULL    COMMENT '错误信息',
  RETRY_COUNT INTEGER default 0  NOT NULL    COMMENT '重试次数',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '附件（EDI 报文文件）',
  SENT_AT DATETIME NULL    COMMENT '发送时间',
  ACKNOWLEDGED_AT DATETIME NULL    COMMENT '确认时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_doc primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_partner_credential(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_PROFILE_ID BIGINT NOT NULL    COMMENT '伙伴档案',
  CREDENTIAL_TYPE INTEGER NOT NULL    COMMENT '凭证类型',
  CREDENTIAL_KEY VARCHAR(200) NULL    COMMENT '凭证标识',
  CREDENTIAL_VALUE VARCHAR(2000) NULL    COMMENT '凭证值',
  ISSUED_AT DATE NULL    COMMENT '颁发日期',
  EXPIRES_AT DATE NULL    COMMENT '过期日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_partner_credential primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_test_exchange(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_PROFILE_ID BIGINT NOT NULL    COMMENT '伙伴档案',
  DIRECTION INTEGER NOT NULL    COMMENT '方向',
  FORMAT_CODE VARCHAR(50) NOT NULL    COMMENT 'EDI格式',
  TEST_CASE_CODE VARCHAR(50) NULL    COMMENT '测试用例编号',
  SENT_PAYLOAD LONGTEXT NULL    COMMENT '发送报文',
  RECEIVED_PAYLOAD LONGTEXT NULL    COMMENT '接收报文',
  EXPECTED_RESULT VARCHAR(500) NULL    COMMENT '预期结果',
  ACTUAL_RESULT VARCHAR(500) NULL    COMMENT '实际结果',
  PASSED BOOLEAN NULL    COMMENT '测试通过',
  TESTED_BY VARCHAR(50) NULL    COMMENT '测试人',
  TESTED_AT DATETIME NULL    COMMENT '测试时间',
  NOTES VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_test_exchange primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_certification_checklist(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_PROFILE_ID BIGINT NOT NULL    COMMENT '伙伴档案',
  CHECKLIST_ITEM VARCHAR(500) NOT NULL    COMMENT '检查项',
  REQUIRED_DOC_TYPE VARCHAR(100) NULL    COMMENT '对应文档类型',
  IS_MANDATORY BOOLEAN default 1  NULL    COMMENT '必检',
  IS_PASSED BOOLEAN NULL    COMMENT '通过',
  CHECKED_BY VARCHAR(50) NULL    COMMENT '检查人',
  CHECKED_AT DATETIME NULL    COMMENT '检查时间',
  EVIDENCE VARCHAR(1000) NULL    COMMENT '检查证据',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_certification_checklist primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_mft_config(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARTNER_ID BIGINT NOT NULL    COMMENT '合作伙伴',
  PROTOCOL VARCHAR(50) NOT NULL    COMMENT '传输协议',
  TRANSPORT_ENDPOINT VARCHAR(500) NOT NULL    COMMENT '传输端点',
  LOCAL_AS2_ID VARCHAR(100) NULL    COMMENT '本地AS2 ID',
  REMOTE_AS2_ID VARCHAR(100) NULL    COMMENT '对方AS2 ID',
  SFTP_USERNAME VARCHAR(100) NULL    COMMENT 'SFTP用户名',
  SFTP_PORT INTEGER default 22  NULL    COMMENT 'SFTP端口',
  FTPS_PORT INTEGER default 990  NULL    COMMENT 'FTPS端口',
  FTPS_IMPLICIT_TLS BOOLEAN default 1  NULL    COMMENT '隐式TLS',
  COMPRESSION BOOLEAN default 0  NULL    COMMENT '启用压缩',
  ENCRYPTION BOOLEAN default 0  NULL    COMMENT '启用加密',
  ENCRYPTION_ALGO VARCHAR(50) NULL    COMMENT '加密算法',
  SIGNATURE BOOLEAN default 0  NULL    COMMENT '启用签名',
  SIGNATURE_ALGO VARCHAR(50) NULL    COMMENT '签名算法',
  CERT_ID BIGINT NULL    COMMENT '关联证书',
  ACTIVE BOOLEAN default 1  NULL    COMMENT '启用',
  MAX_RETRIES INTEGER default 3  NULL    COMMENT '最大重试次数',
  RETRY_INTERVAL_MIN INTEGER default 15  NULL    COMMENT '重试间隔(分钟)',
  DEAD_LETTER_ENABLED BOOLEAN default 1  NULL    COMMENT '启用死信队列',
  MONITOR_DIRECTORY VARCHAR(500) NULL    COMMENT '监控目录',
  MONITOR_INTERVAL_SEC INTEGER default 60  NULL    COMMENT '监控间隔(秒)',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_mft_config primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_asn(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT 'ASN 编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SOURCE_EDI_DOC_ID BIGINT NULL    COMMENT '来源 EDI 文档',
  PARTNER_ID BIGINT NULL    COMMENT '发货方（供应商）',
  SHIPMENT_DATE DATE NULL    COMMENT '发货日期',
  ESTIMATED_ARRIVAL_DATE DATE NULL    COMMENT '预计到货日期',
  TRACKING_NO VARCHAR(100) NULL    COMMENT '物流单号',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联采购订单类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联采购订单号',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_asn primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_edi_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  EDI_DOC_ID BIGINT NULL    COMMENT 'EDI 事务 ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  DIRECTION INTEGER NOT NULL    COMMENT '方向',
  REQUEST_PAYLOAD LONGTEXT NULL    COMMENT '请求报文',
  RESPONSE_PAYLOAD LONGTEXT NULL    COMMENT '响应报文',
  RESULT_CODE VARCHAR(50) NULL    COMMENT '结果码',
  RESULT_MSG VARCHAR(500) NULL    COMMENT '结果消息',
  LOG_TIME DATETIME NOT NULL    COMMENT '日志时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_edi_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_mft_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONFIG_ID BIGINT NOT NULL    COMMENT 'MFT配置',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  DIRECTION VARCHAR(50) NOT NULL    COMMENT '方向',
  FILE_NAME VARCHAR(500) NULL    COMMENT '文件名',
  FILE_SIZE BIGINT NULL    COMMENT '文件大小(字节)',
  FILE_HASH VARCHAR(100) NULL    COMMENT '文件哈希',
  MESSAGE_ID VARCHAR(200) NULL    COMMENT 'AS2 Message-ID',
  MDN_STATUS VARCHAR(50) NULL    COMMENT 'MDN状态',
  PROTOCOL VARCHAR(50) NOT NULL    COMMENT '传输协议',
  STATUS VARCHAR(50) NOT NULL    COMMENT '传输状态',
  START_TIME DATETIME NULL    COMMENT '开始时间',
  END_TIME DATETIME NULL    COMMENT '结束时间',
  DURATION_MS BIGINT NULL    COMMENT '耗时(毫秒)',
  ERROR_CODE VARCHAR(50) NULL    COMMENT '错误码',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误消息',
  RETRY_COUNT INTEGER default 0  NULL    COMMENT '重试次数',
  IS_COMPRESSED BOOLEAN default 0  NULL    COMMENT '压缩',
  IS_ENCRYPTED BOOLEAN default 0  NULL    COMMENT '加密',
  IS_SIGNED BOOLEAN default 0  NULL    COMMENT '签名',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_mft_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_b2b_asn_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ASN_ID BIGINT NOT NULL    COMMENT 'ASN ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  SUPPLIER_PART_NO VARCHAR(100) NULL    COMMENT '供应商料号',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '订单数量',
  SHIPPED_QTY DECIMAL(20,4) NULL    COMMENT '发货数量',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_b2b_asn_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_md_md_material COMMENT 'ErpMdMaterial';
                
   ALTER TABLE erp_b2b_edi_format COMMENT 'EDI 格式配置';
                
   ALTER TABLE erp_b2b_code_mapping COMMENT '内外代码映射';
                
   ALTER TABLE erp_b2b_partner_profile COMMENT '合作伙伴档案';
                
   ALTER TABLE erp_b2b_mft_certificate COMMENT 'MFT 证书';
                
   ALTER TABLE erp_b2b_edi_doc COMMENT 'EDI 事务';
                
   ALTER TABLE erp_b2b_partner_credential COMMENT '伙伴凭证';
                
   ALTER TABLE erp_b2b_test_exchange COMMENT '测试消息交换';
                
   ALTER TABLE erp_b2b_certification_checklist COMMENT '认证检查清单';
                
   ALTER TABLE erp_b2b_mft_config COMMENT 'MFT 配置';
                
   ALTER TABLE erp_b2b_asn COMMENT '提前发货通知';
                
   ALTER TABLE erp_b2b_edi_log COMMENT 'EDI 交互日志';
                
   ALTER TABLE erp_b2b_mft_log COMMENT 'MFT 传输日志';
                
   ALTER TABLE erp_b2b_asn_line COMMENT 'ASN 明细行';
                
