
drop table erp_pur_requisition;
drop table erp_md_material;
drop table erp_md_uom;
drop table erp_md_partner;
drop table erp_md_currency;
drop table erp_md_warehouse;
drop table erp_md_settlement_method;
drop table erp_md_organization;
drop table erp_md_material_sku;
drop table erp_md_tax_rate;
drop table erp_md_bank_account;
drop table erp_pur_rfq;
drop table erp_pur_requisition_line;
drop table erp_pur_supplier_price_list;
drop table erp_pur_invoice;
drop table erp_pur_payment;
drop table erp_pur_order;
drop table erp_pur_rfq_line;
drop table erp_pur_quotation;
drop table erp_pur_invoice_line;
drop table erp_pur_payment_line;
drop table erp_pur_order_line;
drop table erp_pur_receive;
drop table erp_pur_quotation_line;
drop table erp_pur_receive_line;
drop table erp_pur_return;
drop table erp_pur_return_line;

