
CREATE TABLE erp_md_warehouse(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_location(
  ID BIGINT NULL    COMMENT 'null',
  WAREHOUSE_ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_location primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  MATERIAL_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_sku(
  ID BIGINT NULL    COMMENT 'null',
  MATERIAL_ID BIGINT NULL    COMMENT 'null',
  SKU_CODE VARCHAR(50) NULL    COMMENT 'null',
  BARCODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_material_sku primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  UOM_GROUP VARCHAR(50) NULL    COMMENT 'null',
  IS_BASE BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_uom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SYMBOL VARCHAR(50) NULL    COMMENT 'null',
  DECIMAL_PLACES INTEGER NULL    COMMENT 'null',
  IS_FUNCTIONAL BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_acct_schema(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  CURRENCY_ID BIGINT NULL    COMMENT 'null',
  NATURE INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_acct_schema primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_transfer_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  FROM_WAREHOUSE_ID BIGINT NOT NULL    COMMENT '调出仓库',
  TO_WAREHOUSE_ID BIGINT NOT NULL    COMMENT '调入仓库',
  IN_TRANSIT_WAREHOUSE_ID BIGINT NULL    COMMENT '在途仓库',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_transfer_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_take(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '盘点日期',
  TAKE_TYPE VARCHAR(20) NULL    COMMENT '盘点类型',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '盘点仓库',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_stock_take primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_move(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  MOVE_TYPE VARCHAR(20) NOT NULL    COMMENT '作业类型',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  SOURCE_WAREHOUSE_ID BIGINT NULL    COMMENT '源仓库',
  SOURCE_LOCATION_ID BIGINT NULL    COMMENT '源库位',
  DEST_WAREHOUSE_ID BIGINT NULL    COMMENT '目标仓库',
  DEST_LOCATION_ID BIGINT NULL    COMMENT '目标库位',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  ORIGIN_MOVE_ID BIGINT NULL    COMMENT '上游移动单',
  ORIGIN_RETURNED_MOVE_ID BIGINT NULL    COMMENT '原退货移动单',
  constraint PK_erp_inv_stock_move primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_batch(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BATCH_NO VARCHAR(50) NOT NULL    COMMENT '批号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  TOTAL_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '总数量',
  AVAILABLE_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '可用数量',
  PRODUCTION_DATE DATE NULL    COMMENT '生产日期',
  EXPIRY_DATE DATE NULL    COMMENT '有效期至',
  SHELF_LIFE_DAYS INTEGER NULL    COMMENT '保质期(天)',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_batch primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_serial_number(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SERIAL_NO VARCHAR(50) NOT NULL    COMMENT '序列号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NULL    COMMENT '当前仓库',
  LOCATION_ID BIGINT NULL    COMMENT '当前库位',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  IN_BILL_TYPE VARCHAR(50) NULL    COMMENT '入库单类型',
  IN_BILL_CODE VARCHAR(50) NULL    COMMENT '入库单号',
  OUT_BILL_TYPE VARCHAR(50) NULL    COMMENT '出库单类型',
  OUT_BILL_CODE VARCHAR(50) NULL    COMMENT '出库单号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_serial_number primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_cost_adjust(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  ADJUST_TYPE VARCHAR(30) NOT NULL    COMMENT '调整类型',
  REASON VARCHAR(500) NULL    COMMENT '调整原因',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_cost_adjust primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_balance(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  LOCATION_ID BIGINT NULL    COMMENT '库位',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  TOTAL_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '总数量',
  RESERVED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '预留数量',
  LOCKED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '冻结数量',
  AVAILABLE_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '可用数量',
  COST_METHOD VARCHAR(20) NULL    COMMENT '计价方法',
  AVG_COST DECIMAL(20,4) NULL    COMMENT '平均成本',
  TOTAL_COST DECIMAL(20,4) NULL    COMMENT '总成本',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  OWNER_ID BIGINT NULL    COMMENT '所有权往来单位',
  OWNERSHIP_TYPE VARCHAR(20) default 'OWNED'  NULL    COMMENT '所有权类型',
  constraint PK_erp_inv_stock_balance primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_reservation(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  SOURCE_BILL_TYPE VARCHAR(50) NOT NULL    COMMENT '来源单据类型(如 SALES_ORDER/WORK_ORDER)',
  SOURCE_BILL_CODE VARCHAR(50) NOT NULL    COMMENT '来源单据号',
  RESERVED_FOR_PARTNER_ID BIGINT NULL    COMMENT '为谁预留(往来单位)',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  VALID_UNTIL DATETIME(3) NULL    COMMENT '预留有效期至',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_reservation primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_ownership_transfer(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TRANSFER_TYPE VARCHAR(30) NOT NULL    COMMENT '转移类型',
  PARTNER_ID BIGINT NOT NULL    COMMENT '所有权对方(往来单位)',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  SOURCE_LOC_ID BIGINT NOT NULL    COMMENT '源库位(=目的库位)',
  DEST_LOC_ID BIGINT NOT NULL    COMMENT '目的库位(=源库位)',
  FROM_OWNERSHIP_TYPE VARCHAR(20) NOT NULL    COMMENT '转前所有权类型',
  TO_OWNERSHIP_TYPE VARCHAR(20) NOT NULL    COMMENT '转后所有权类型',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_ownership_transfer primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_landed_cost(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  RECEIVE_ID BIGINT NOT NULL    COMMENT '采购入库单',
  SUPPLIER_ID BIGINT NULL    COMMENT '采购供应商',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,6) NULL    COMMENT '汇率',
  TOTAL_COST_AMOUNT DECIMAL(20,4) NULL    COMMENT '到岸成本合计',
  ALLOCATION_METHOD VARCHAR(20) NOT NULL    COMMENT '分摊方法',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME(3) NULL    COMMENT '审核时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_landed_cost primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_picking_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '拣货仓库',
  PICKER_ID BIGINT NULL    COMMENT '拣货人(职员)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型(SALES_DELIVERY/WORK_ORDER_ISSUE)',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_picking_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_transfer_order_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TRANSFER_ID BIGINT NOT NULL    COMMENT '调拨单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_transfer_order_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_take_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TAKE_ID BIGINT NOT NULL    COMMENT '盘点单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  LOCATION_ID BIGINT NULL    COMMENT '库位',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  BOOK_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '账面数量',
  ACTUAL_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '实盘数量',
  DIFFERENCE_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '差异数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  DIFFERENCE_AMOUNT DECIMAL(20,4) NULL    COMMENT '差异金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_stock_take_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_move_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MOVE_ID BIGINT NOT NULL    COMMENT '移动单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  TOTAL_COST DECIMAL(20,4) NULL    COMMENT '总成本',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  SERIAL_NO VARCHAR(50) NULL    COMMENT '序列号',
  SOURCE_LOCATION_ID BIGINT NULL    COMMENT '源库位',
  DEST_LOCATION_ID BIGINT NULL    COMMENT '目标库位',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_stock_move_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_cost_layer(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  COST_METHOD VARCHAR(20) NOT NULL    COMMENT '计价方法',
  INCOMING_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '入库数量',
  REMAINING_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '剩余数量',
  UNIT_COST DECIMAL(20,4) NOT NULL    COMMENT '单位成本',
  TOTAL_COST DECIMAL(20,4) NOT NULL    COMMENT '总成本',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  INCOMING_DATE DATE NULL    COMMENT '入库日期',
  INCOMING_MOVE_ID BIGINT NULL    COMMENT '入库移动单',
  ACCT_SCHEMA_ID BIGINT NULL    COMMENT '账套',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_cost_layer primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_cost_adjust_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ADJUST_ID BIGINT NOT NULL    COMMENT '成本调整单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  OLD_UNIT_COST DECIMAL(20,4) NULL    COMMENT '原单位成本',
  NEW_UNIT_COST DECIMAL(20,4) NOT NULL    COMMENT '新单位成本',
  ADJUST_QTY DECIMAL(20,4) NULL    COMMENT '调整数量',
  ADJUST_AMOUNT DECIMAL(20,4) NULL    COMMENT '调整金额',
  ADJUST_REASON VARCHAR(200) NULL    COMMENT '行调整原因',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_cost_adjust_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_reservation_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  RESERVATION_ID BIGINT NOT NULL    COMMENT '预留单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  LOCATION_ID BIGINT NULL    COMMENT '库位',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  RESERVED_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '预留数量',
  CONSUMED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '已消耗数量',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  SOURCE_LINE_CODE VARCHAR(50) NULL    COMMENT '来源行号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_reservation_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_ownership_transfer_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TRANSFER_ID BIGINT NOT NULL    COMMENT '转移单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  TOTAL_COST DECIMAL(20,4) NULL    COMMENT '总成本',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_ownership_transfer_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_landed_cost_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LANDED_COST_ID BIGINT NOT NULL    COMMENT '到岸成本单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  COST_ELEMENT VARCHAR(30) NOT NULL    COMMENT '费用要素',
  AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '金额',
  AP_PARTNER_ID BIGINT NULL    COMMENT '应付对象',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_landed_cost_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_picking_order_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PICKING_ID BIGINT NOT NULL    COMMENT '拣货单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UO_M_ID BIGINT NOT NULL    COMMENT '计量单位',
  SOURCE_LOCATION_ID BIGINT NULL    COMMENT '拣货库位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '应拣数量',
  PICKED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '已拣数量',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_inv_picking_order_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_inv_stock_ledger(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '流水号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MOVE_ID BIGINT NOT NULL    COMMENT '移动单ID',
  MOVE_LINE_ID BIGINT NOT NULL    COMMENT '移动单行ID',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  LOCATION_ID BIGINT NULL    COMMENT '库位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  UNIT_COST DECIMAL(20,4) NULL    COMMENT '单位成本',
  TOTAL_COST DECIMAL(20,4) NULL    COMMENT '总成本',
  BALANCE_QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '结存数量',
  BALANCE_TOTAL_COST DECIMAL(20,4) NOT NULL    COMMENT '结存总成本',
  COST_METHOD VARCHAR(20) NULL    COMMENT '计价方法',
  ACCT_SCHEMA_ID BIGINT NULL    COMMENT '账套',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  BUSINESS_DATE DATE NULL    COMMENT '业务日期',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  SERIAL_NO VARCHAR(50) NULL    COMMENT '序列号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  OWNER_ID BIGINT NULL    COMMENT '所有权往来单位',
  OWNERSHIP_TYPE VARCHAR(20) default 'OWNED'  NULL    COMMENT '所有权类型',
  constraint PK_erp_inv_stock_ledger primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_location COMMENT '库位';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_material_sku COMMENT '物料SKU';
                
   ALTER TABLE erp_md_uom COMMENT '计量单位';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_acct_schema COMMENT '会计核算表(账套)';
                
   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_employee COMMENT '员工';
                
   ALTER TABLE erp_inv_transfer_order COMMENT '调拨单';
                
   ALTER TABLE erp_inv_stock_take COMMENT '盘点单';
                
   ALTER TABLE erp_inv_stock_move COMMENT '库存移动单';
                
   ALTER TABLE erp_inv_batch COMMENT '批次台账';
                
   ALTER TABLE erp_inv_serial_number COMMENT '序列号台账';
                
   ALTER TABLE erp_inv_cost_adjust COMMENT '成本调整单';
                
   ALTER TABLE erp_inv_stock_balance COMMENT '库存余额';
                
   ALTER TABLE erp_inv_reservation COMMENT '库存预留单';
                
   ALTER TABLE erp_inv_ownership_transfer COMMENT '所有权转移单';
                
   ALTER TABLE erp_inv_landed_cost COMMENT '到岸成本单';
                
   ALTER TABLE erp_inv_picking_order COMMENT '拣货单';
                
   ALTER TABLE erp_inv_transfer_order_line COMMENT '调拨单行';
                
   ALTER TABLE erp_inv_stock_take_line COMMENT '盘点单行';
                
   ALTER TABLE erp_inv_stock_move_line COMMENT '库存移动单行';
                
   ALTER TABLE erp_inv_cost_layer COMMENT '成本层';
                
   ALTER TABLE erp_inv_cost_adjust_line COMMENT '成本调整单行';
                
   ALTER TABLE erp_inv_reservation_line COMMENT '库存预留单行';
                
   ALTER TABLE erp_inv_ownership_transfer_line COMMENT '所有权转移单行';
                
   ALTER TABLE erp_inv_landed_cost_line COMMENT '到岸成本行';
                
   ALTER TABLE erp_inv_picking_order_line COMMENT '拣货单行';
                
   ALTER TABLE erp_inv_stock_ledger COMMENT '库存流水';
                
