
CREATE TABLE erp_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_team(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TEAM_LEADER_ID VARCHAR(36) NULL    COMMENT '团队负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_team primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_canned_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARENT_ID BIGINT NULL    COMMENT '父分类',
  ICON VARCHAR(100) NULL    COMMENT '图标',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_canned_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_agent_rate(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  AGENT_ID BIGINT NOT NULL    COMMENT '客服',
  SERVICE_TYPE VARCHAR(20) NULL    COMMENT '服务类型',
  RATE DECIMAL(18,2) NULL    COMMENT '费率(元/小时)',
  EFFECTIVE_DATE DATE NULL    COMMENT '生效日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_agent_rate primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARTNER_ID BIGINT NULL    COMMENT '签约客户',
  CONTRACT_TYPE VARCHAR(20) NULL    COMMENT '合同类型',
  START_DATE DATE NULL    COMMENT '生效日期',
  END_DATE DATE NULL    COMMENT '到期日期',
  TOTAL_AMOUNT DECIMAL(18,2) NULL    COMMENT '合同总金额',
  BILLING_CYCLE VARCHAR(20) NULL    COMMENT '计费周期',
  STATUS VARCHAR(20) NULL    COMMENT '合同状态',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '合同附件',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  constraint PK_erp_cs_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_catalog_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARENT_ID BIGINT NULL    COMMENT '父分类',
  ICON VARCHAR(100) NULL    COMMENT '图标',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_catalog_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_sla_policy(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TICKET_TYPE_ID BIGINT NULL    COMMENT '适用工单类型',
  MIN_PRIORITY VARCHAR(20) NULL    COMMENT '最低触发优先级',
  TEAM_ID BIGINT NULL    COMMENT '适用团队',
  RESOLVE_HOURS INTEGER NULL    COMMENT '解决时限(小时)',
  RESOLVE_DAYS INTEGER NULL    COMMENT '解决时限(天)',
  IS_WORKING_DAYS BOOLEAN default 1  NULL    COMMENT '仅计算工作日',
  ESCALATION_USER_ID BIGINT NULL    COMMENT '升级通知人',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '说明',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_sla_policy primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_knowledge_base(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NULL    COMMENT '编码',
  TITLE VARCHAR(200) NOT NULL    COMMENT '标题',
  CONTENT VARCHAR(4000) NULL    COMMENT '正文',
  CATEGORY_ID BIGINT NULL    COMMENT '分类',
  IS_PUBLISHED BOOLEAN default 0  NULL    COMMENT '是否发布',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_knowledge_base primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket_type(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DEFAULT_PRIORITY VARCHAR(20) NULL    COMMENT '默认优先级',
  DEFAULT_SLA_POLICY_ID BIGINT NULL    COMMENT '默认 SLA 策略',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_ticket_type primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_entitlement(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARTNER_ID BIGINT NOT NULL    COMMENT '客户',
  CONTRACT_ID BIGINT NULL    COMMENT '支持合同',
  SLA_POLICY_ID BIGINT NULL    COMMENT 'SLA策略',
  SERVICE_TYPE VARCHAR(20) NOT NULL    COMMENT '服务类型',
  START_DATE DATE NULL    COMMENT '生效日期',
  END_DATE DATE NULL    COMMENT '失效日期',
  MAX_TICKETS INTEGER NULL    COMMENT '最大工单数',
  USED_TICKETS INTEGER default 0  NULL    COMMENT '已用工单数',
  MAX_RESPONSE_TIME INTEGER NULL    COMMENT '承诺响应时限(分钟)',
  MAX_RESOLUTION_TIME INTEGER NULL    COMMENT '承诺解决时限(分钟)',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  NOTES VARCHAR(4000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_entitlement primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_canned_response(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TITLE VARCHAR(200) NOT NULL    COMMENT '模板标题',
  CONTENT VARCHAR(4000) NOT NULL    COMMENT '模板正文',
  CATEGORY_ID BIGINT NULL    COMMENT '应答分类',
  VARIABLE_DEFS VARCHAR(4000) NULL    COMMENT '变量定义',
  MACRO_TICKET_TYPE_ID BIGINT NULL    COMMENT '自动匹配工单类型',
  MACRO_PRIORITY VARCHAR(20) NULL    COMMENT '自动匹配优先级',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  USAGE_COUNT INTEGER default 0  NULL    COMMENT '使用次数',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_canned_response primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_service_catalog_item(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CATEGORY_ID BIGINT NULL    COMMENT '目录分类',
  PARENT_ID BIGINT NULL    COMMENT '父项',
  SHORT_DESCRIPTION VARCHAR(500) NULL    COMMENT '简短描述',
  FULL_DESCRIPTION VARCHAR(4000) NULL    COMMENT '详细说明',
  TICKET_TYPE_ID BIGINT NULL    COMMENT '关联工单类型',
  SLA_POLICY_ID BIGINT NULL    COMMENT '默认SLA策略',
  FULFILLMENT_PROCESS_ID VARCHAR(100) NULL    COMMENT '履行流程标识',
  REQUEST_FORM_CONFIG VARCHAR(4000) NULL    COMMENT '请求表单配置',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否上架',
  IS_PUBLIC BOOLEAN default 0  NULL    COMMENT '是否客户可见',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  ESTIMATED_RESOLUTION VARCHAR(200) NULL    COMMENT '预计解决时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_service_catalog_item primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SUBJECT VARCHAR(200) NOT NULL    COMMENT '工单主题',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '问题描述',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  CONTACT_ID BIGINT NULL    COMMENT '联系人',
  TICKET_TYPE_ID BIGINT NOT NULL    COMMENT '工单类型',
  PRIORITY VARCHAR(20) NOT NULL    COMMENT '优先级',
  SOURCE VARCHAR(20) NULL    COMMENT '来源',
  ASSIGNED_TO_ID VARCHAR(36) NULL    COMMENT '分配处理人',
  SLA_POLICY_ID BIGINT NULL    COMMENT 'SLA 策略',
  DEADLINE_DATE_TIME DATETIME NULL    COMMENT 'SLA 截止时间',
  IS_SLA_COMPLETED BOOLEAN default 0  NULL    COMMENT 'SLA 是否完成',
  START_DATE_TIME DATETIME NULL    COMMENT '开始处理时间',
  END_DATE_TIME DATETIME NULL    COMMENT '关闭时间',
  DURATION INTEGER NULL    COMMENT '处理时长(分钟)',
  PROGRESS INTEGER default 0  NULL    COMMENT '进度(%)',
  STATUS VARCHAR(20) NOT NULL    COMMENT '工单状态',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  CATALOG_ITEM_ID BIGINT NULL    COMMENT '服务目录项',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  constraint PK_erp_cs_ticket primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_catalog_fulfillment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CATALOG_ITEM_ID BIGINT NOT NULL    COMMENT '目录项',
  SEQUENCE INTEGER NULL    COMMENT '执行顺序',
  ACTION_TYPE VARCHAR(20) NOT NULL    COMMENT '动作类型',
  ACTION_CONFIG VARCHAR(4000) NULL    COMMENT '动作配置',
  ASSIGN_TO_ROLE VARCHAR(100) NULL    COMMENT '执行角色',
  ESTIMATED_DURATION INTEGER NULL    COMMENT '预估时长(分钟)',
  IS_MANDATORY BOOLEAN default 1  NULL    COMMENT '是否必须执行',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_catalog_fulfillment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket_action(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TICKET_ID BIGINT NOT NULL    COMMENT '工单ID',
  ACTION_TYPE VARCHAR(20) NOT NULL    COMMENT '操作类型',
  FROM_STATUS VARCHAR(20) NULL    COMMENT '起始状态',
  TO_STATUS VARCHAR(20) NULL    COMMENT '目标状态',
  OPERATOR_ID VARCHAR(36) NULL    COMMENT '操作人',
  CONTENT VARCHAR(4000) NULL    COMMENT '操作内容',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_ticket_action primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_survey(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TICKET_ID BIGINT NOT NULL    COMMENT '关联工单',
  SURVEY_TOKEN VARCHAR(50) NULL    COMMENT '调查令牌',
  CSAT_SCORE INTEGER NULL    COMMENT 'CSAT评分',
  NPS_SCORE INTEGER NULL    COMMENT 'NPS评分',
  CES_SCORE INTEGER NULL    COMMENT 'CES评分',
  COMMENT VARCHAR(4000) NULL    COMMENT '文字反馈',
  RESPONDED_AT DATETIME NULL    COMMENT '响应时间',
  SURVEY_SENT_AT DATETIME NULL    COMMENT '调查发送时间',
  SURVEY_CHANNEL VARCHAR(20) NULL    COMMENT '发送渠道',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_survey primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_time_entry(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TICKET_ID BIGINT NOT NULL    COMMENT '关联工单',
  AGENT_ID BIGINT NOT NULL    COMMENT '处理人',
  START_TIME DATETIME NULL    COMMENT '开始时间',
  END_TIME DATETIME NULL    COMMENT '结束时间',
  DURATION INTEGER NULL    COMMENT '时长(分钟)',
  IS_BILLABLE BOOLEAN default 1  NULL    COMMENT '是否可计费',
  BILLING_RATE DECIMAL(18,2) NULL    COMMENT '计费费率',
  BILLABLE_AMOUNT DECIMAL(18,2) NULL    COMMENT '计费金额',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '工作内容描述',
  APPROVAL_STATUS VARCHAR(20) NULL    COMMENT '审批状态',
  APPROVED_BY_ID VARCHAR(36) NULL    COMMENT '审批人',
  APPROVED_AT DATETIME NULL    COMMENT '审批时间',
  PROJECT_ID BIGINT NULL    COMMENT '关联项目',
  TASK_ID BIGINT NULL    COMMENT '关联任务',
  SOURCE VARCHAR(20) NULL    COMMENT '来源',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_time_entry primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_cs_team COMMENT '客服团队';
                
   ALTER TABLE erp_cs_canned_category COMMENT '预设应答分类';
                
   ALTER TABLE erp_cs_agent_rate COMMENT '客服费率';
                
   ALTER TABLE erp_cs_contract COMMENT '支持合同';
                
   ALTER TABLE erp_cs_catalog_category COMMENT '目录分类';
                
   ALTER TABLE erp_cs_sla_policy COMMENT 'SLA 策略';
                
   ALTER TABLE erp_cs_knowledge_base COMMENT '知识库';
                
   ALTER TABLE erp_cs_ticket_type COMMENT '工单类型';
                
   ALTER TABLE erp_cs_entitlement COMMENT '服务权益';
                
   ALTER TABLE erp_cs_canned_response COMMENT '预设应答模板';
                
   ALTER TABLE erp_cs_service_catalog_item COMMENT '服务目录项';
                
   ALTER TABLE erp_cs_ticket COMMENT '客服工单';
                
   ALTER TABLE erp_cs_catalog_fulfillment COMMENT '目录项履行映射';
                
   ALTER TABLE erp_cs_ticket_action COMMENT '工单操作日志';
                
   ALTER TABLE erp_cs_survey COMMENT '满意度调查';
                
   ALTER TABLE erp_cs_time_entry COMMENT '工单计时条目';
                
