
CREATE TABLE erp_md_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket_type(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  DEFAULT_PRIORITY INTEGER NULL    COMMENT '默认优先级',
  DEFAULT_SLA_POLICY_ID BIGINT NULL    COMMENT '默认 SLA 策略',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_ticket_type primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_auth_user(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_auth_user primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_knowledge_base(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NULL    COMMENT '编码',
  TITLE VARCHAR(200) NOT NULL    COMMENT '标题',
  CONTENT VARCHAR(4000) NULL    COMMENT '正文',
  CATEGORY_ID BIGINT NULL    COMMENT '分类',
  IS_PUBLISHED BOOLEAN default 0  NULL    COMMENT '是否发布',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_knowledge_base primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_team(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TEAM_LEADER_ID BIGINT NULL    COMMENT '团队负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_team primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_sla_policy(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TICKET_TYPE_ID BIGINT NULL    COMMENT '适用工单类型',
  MIN_PRIORITY INTEGER NULL    COMMENT '最低触发优先级',
  TEAM_ID BIGINT NULL    COMMENT '适用团队',
  RESOLVE_HOURS INTEGER NULL    COMMENT '解决时限(小时)',
  RESOLVE_DAYS INTEGER NULL    COMMENT '解决时限(天)',
  IS_WORKING_DAYS BOOLEAN default 1  NULL    COMMENT '仅计算工作日',
  ESCALATION_USER_ID BIGINT NULL    COMMENT '升级通知人',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '说明',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_sla_policy primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SUBJECT VARCHAR(200) NOT NULL    COMMENT '工单主题',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '问题描述',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  CONTACT_ID BIGINT NULL    COMMENT '联系人',
  TICKET_TYPE_ID BIGINT NOT NULL    COMMENT '工单类型',
  PRIORITY INTEGER NOT NULL    COMMENT '优先级',
  SOURCE INTEGER NULL    COMMENT '来源',
  ASSIGNED_TO_ID BIGINT NULL    COMMENT '分配处理人',
  SLA_POLICY_ID BIGINT NULL    COMMENT 'SLA 策略',
  DEADLINE_DATE_TIME DATETIME NULL    COMMENT 'SLA 截止时间',
  IS_SLA_COMPLETED BOOLEAN default 0  NULL    COMMENT 'SLA 是否完成',
  START_DATE_TIME DATETIME NULL    COMMENT '开始处理时间',
  END_DATE_TIME DATETIME NULL    COMMENT '关闭时间',
  DURATION INTEGER NULL    COMMENT '处理时长(分钟)',
  PROGRESS INTEGER default 0  NULL    COMMENT '进度(%)',
  STATUS INTEGER NOT NULL    COMMENT '工单状态',
  DOC_STATUS INTEGER NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS INTEGER NOT NULL    COMMENT '审核状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_ticket primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_cs_ticket_action(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TICKET_ID BIGINT NOT NULL    COMMENT '工单ID',
  ACTION_TYPE INTEGER NOT NULL    COMMENT '操作类型',
  FROM_STATUS INTEGER NULL    COMMENT '起始状态',
  TO_STATUS INTEGER NULL    COMMENT '目标状态',
  OPERATOR_ID BIGINT NULL    COMMENT '操作人',
  CONTENT VARCHAR(4000) NULL    COMMENT '操作内容',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_cs_ticket_action primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_cs_ticket_type COMMENT '工单类型';
                
   ALTER TABLE erp_md_auth_user COMMENT 'NopAuthUser';
                
   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_cs_knowledge_base COMMENT '知识库';
                
   ALTER TABLE erp_cs_team COMMENT '客服团队';
                
   ALTER TABLE erp_cs_sla_policy COMMENT 'SLA 策略';
                
   ALTER TABLE erp_cs_ticket COMMENT '客服工单';
                
   ALTER TABLE erp_cs_ticket_action COMMENT '工单操作日志';
                
