
CREATE TABLE erp_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_operation_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '主工单',
  OPERATION_NAME VARCHAR(200) NOT NULL    COMMENT '工序名称',
  SEQUENCE INTEGER NOT NULL    COMMENT '工序顺序',
  MACHINE_ID BIGINT NOT NULL    COMMENT '工作中心/设备',
  PRIORITY INTEGER default 50  NULL    COMMENT '优先级',
  PLANNED_START_DATE_T DATETIME(3) NULL    COMMENT '计划开工时间',
  PLANNED_END_DATE_T DATETIME(3) NULL    COMMENT '计划完工时间',
  REAL_START_DATE_T DATETIME(3) NULL    COMMENT '实际开工时间',
  REAL_END_DATE_T DATETIME(3) NULL    COMMENT '实际完工时间',
  SETUP_TIME DECIMAL(10,2) NULL    COMMENT '准备时间(分钟)',
  RUNTIME_PER_UNIT DECIMAL(10,2) NULL    COMMENT '每件加工时间(分钟)',
  QTY DECIMAL(20,4) NOT NULL    COMMENT '加工数量',
  TOTAL_DURATION DECIMAL(10,2) NULL    COMMENT '总耗时(分钟)',
  ASSIGNED_TO_ID VARCHAR(36) NULL    COMMENT '操作工',
  IS_OUTSOURCED BOOLEAN default 0  NULL    COMMENT '是否外协',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  EARLIEST_START_DATE_T DATETIME(3) NULL    COMMENT '最早开工时间',
  LATEST_END_DATE_T DATETIME(3) NULL    COMMENT '最晚完工时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  constraint PK_erp_aps_operation_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_schedule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  NAME VARCHAR(200) NOT NULL    COMMENT '方案名称',
  SCHEDULE_DATE DATE NOT NULL    COMMENT '排产日期',
  SCHEDULING_MODE VARCHAR(20) NOT NULL    COMMENT '排产模式',
  HORIZON_START DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '展望期开始',
  HORIZON_END DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '展望期结束',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  BUSINESS_DATE DATE NOT NULL    COMMENT '业务日期',
  constraint PK_erp_aps_schedule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_constraint(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MACHINE_ID BIGINT NOT NULL    COMMENT '工作中心/设备',
  CONSTRAINT_TYPE VARCHAR(20) NOT NULL    COMMENT '约束类型',
  START_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '开始时间',
  END_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '结束时间',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '约束描述',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_constraint primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_op_routing(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  OPERATION_ID BIGINT NOT NULL    COMMENT '工序',
  MACHINE_ID BIGINT NOT NULL    COMMENT '工作中心',
  PRIORITY INTEGER NOT NULL    COMMENT '优先级',
  SETUP_TIME_DELTA DECIMAL(10,2) NULL    COMMENT '换模时间差(分钟)',
  RUNTIME_PER_UNIT_DELTA DECIMAL(10,2) NULL    COMMENT '单件加工时间差(分钟)',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '默认路由',
  IS_ENABLED BOOLEAN default 1  NULL    COMMENT '启用',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效日期',
  EFFECTIVE_TO DATE NULL    COMMENT '失效日期',
  MIN_BATCH_QTY DECIMAL(20,4) NULL    COMMENT '最小批量',
  MAX_BATCH_QTY DECIMAL(20,4) NULL    COMMENT '最大批量',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_op_routing primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_dispatch_rule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  WORKCENTER_ID BIGINT NOT NULL    COMMENT '工作中心',
  RULE_NAME VARCHAR(200) NOT NULL    COMMENT '规则名称',
  ENABLE_AUTO BOOLEAN default 1  NULL    COMMENT '自动派工启用',
  REQUIRE_MATERIAL BOOLEAN default 1  NULL    COMMENT '物料齐套检查',
  REQUIRE_OPERATOR BOOLEAN default 1  NULL    COMMENT '操作工检查',
  REQUIRE_TOOLING BOOLEAN default 0  NULL    COMMENT '工装检查',
  MAX_LOOKAHEAD_MINUTES INTEGER default 120  NULL    COMMENT '前瞻窗口(分钟)',
  DISPATCH_AHEAD_MINUTES INTEGER default 15  NULL    COMMENT '提前派工(分钟)',
  AUTO_CONFIRM_MATERIAL BOOLEAN default 1  NULL    COMMENT '自动确认物料',
  MAX_CONCURRENT_OPS INTEGER NULL    COMMENT '最大并行工序数',
  PRIORITY_THRESHOLD INTEGER NULL    COMMENT '优先级阈值',
  ENABLED_HOURS VARCHAR(500) NULL    COMMENT '允许时段(JSON)',
  HOLD_UNTIL DATETIME(3) NULL    COMMENT '暂停到',
  HOLD_REASON VARCHAR(500) NULL    COMMENT '暂停原因',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_dispatch_rule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_dispatch_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  OPERATION_ORDER_ID BIGINT NOT NULL    COMMENT '工序工单',
  WORKCENTER_ID BIGINT NULL    COMMENT '工作中心',
  DISPATCH_TYPE VARCHAR(20) NOT NULL    COMMENT '派工类型',
  PREVIOUS_STATUS VARCHAR(50) NULL    COMMENT '派工前状态',
  NEW_STATUS VARCHAR(50) NULL    COMMENT '派工后状态',
  CONDITION_CHECK_RESULT VARCHAR(2000) NULL    COMMENT '条件检查结果(JSON)',
  DISPATCHED_BY VARCHAR(50) NULL    COMMENT '派工人',
  DISPATCHED_AT DATETIME(3) NULL    COMMENT '派工时间',
  MATERIAL_AVAILABLE BOOLEAN NULL    COMMENT '物料齐套',
  OPERATOR_AVAILABLE BOOLEAN NULL    COMMENT '操作工可用',
  TOOLING_AVAILABLE BOOLEAN NULL    COMMENT '工装可用',
  NOTE VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_dispatch_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_aps_operation_order COMMENT '工序工单';
                
   ALTER TABLE erp_aps_schedule COMMENT '排产方案';
                
   ALTER TABLE erp_aps_constraint COMMENT '排产约束';
                
   ALTER TABLE erp_aps_op_routing COMMENT '替代工艺路线';
                
   ALTER TABLE erp_aps_dispatch_rule COMMENT '自动派工规则';
                
   ALTER TABLE erp_aps_dispatch_log COMMENT '派工日志';
                
