
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_operation_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  WORK_ORDER_ID BIGINT NOT NULL    COMMENT '主工单',
  OPERATION_NAME VARCHAR(200) NOT NULL    COMMENT '工序名称',
  SEQUENCE INTEGER NOT NULL    COMMENT '工序顺序',
  MACHINE_ID BIGINT NOT NULL    COMMENT '工作中心/设备',
  PRIORITY INTEGER default 50  NULL    COMMENT '优先级',
  PLANNED_START_DATE_T DATETIME NULL    COMMENT '计划开工时间',
  PLANNED_END_DATE_T DATETIME NULL    COMMENT '计划完工时间',
  REAL_START_DATE_T DATETIME NULL    COMMENT '实际开工时间',
  REAL_END_DATE_T DATETIME NULL    COMMENT '实际完工时间',
  SETUP_TIME DECIMAL(10,2) NULL    COMMENT '准备时间(分钟)',
  RUNTIME_PER_UNIT DECIMAL(10,2) NULL    COMMENT '每件加工时间(分钟)',
  QTY DECIMAL(20,4) NOT NULL    COMMENT '加工数量',
  TOTAL_DURATION DECIMAL(10,2) NULL    COMMENT '总耗时(分钟)',
  ASSIGNED_TO_ID BIGINT NULL    COMMENT '操作工',
  IS_OUTSOURCED BOOLEAN default 0  NULL    COMMENT '是否外协',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_operation_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_schedule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  NAME VARCHAR(200) NOT NULL    COMMENT '方案名称',
  SCHEDULE_DATE DATE NOT NULL    COMMENT '排产日期',
  SCHEDULING_MODE INTEGER NOT NULL    COMMENT '排产模式',
  HORIZON_START DATETIME NOT NULL    COMMENT '展望期开始',
  HORIZON_END DATETIME NOT NULL    COMMENT '展望期结束',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_schedule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_aps_constraint(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MACHINE_ID BIGINT NOT NULL    COMMENT '工作中心/设备',
  CONSTRAINT_TYPE INTEGER NOT NULL    COMMENT '约束类型',
  START_TIME DATETIME NOT NULL    COMMENT '开始时间',
  END_TIME DATETIME NOT NULL    COMMENT '结束时间',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '约束描述',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_aps_constraint primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_aps_operation_order COMMENT '工序工单';
                
   ALTER TABLE erp_aps_schedule COMMENT '排产方案';
                
   ALTER TABLE erp_aps_constraint COMMENT '排产约束';
                
