
CREATE TABLE erp_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_carrier(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CARRIER_NAME VARCHAR(200) NOT NULL    COMMENT '承运商名称',
  CARRIER_TYPE VARCHAR(20) NOT NULL    COMMENT '承运商类型',
  GATEWAY_ID VARCHAR(50) NOT NULL    COMMENT '网关标识',
  PARTNER_ID BIGINT NULL    COMMENT '承运商往来单位ID',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  TRACKING_URL_TEMPLATE VARCHAR(500) NULL    COMMENT '追踪URL模板',
  MAX_PARCEL_WEIGHT DECIMAL(12,3) NULL    COMMENT '最大包裹重量(kg)',
  SUPPORTED_SERVICE_TYPES LONGTEXT NULL    COMMENT '支持服务类型',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_carrier primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_delivery_window(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_ID BIGINT NOT NULL    COMMENT '客户',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  WEEKDAY INTEGER NOT NULL    COMMENT '星期',
  START_TIME VARCHAR(8) NOT NULL    COMMENT '开始时间',
  END_TIME VARCHAR(8) NOT NULL    COMMENT '结束时间',
  MAX_CAPACITY INTEGER default 10  NOT NULL    COMMENT '最大预约数',
  CURRENT_BOOKED INTEGER default 0  NOT NULL    COMMENT '当前已预约',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效日期',
  EFFECTIVE_TO DATE NULL    COMMENT '失效日期',
  ALLOWED_SHIPMENT_TYPES VARCHAR(200) NULL    COMMENT '允许发运类型',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_delivery_window primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_carrier_config(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CARRIER_ID BIGINT NOT NULL    COMMENT '承运商ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONFIG_CODE VARCHAR(50) NOT NULL    COMMENT '配置编码',
  SERVICE_TYPE VARCHAR(50) NULL    COMMENT '服务类型',
  API_ENDPOINT VARCHAR(500) NULL    COMMENT '接口地址',
  API_KEY VARCHAR(500) NULL    COMMENT 'API密钥',
  API_SECRET VARCHAR(500) NULL    COMMENT 'API密钥',
  CREDENTIALS LONGTEXT NULL    COMMENT '完整凭证',
  TRACKING_URL_TEMPLATE VARCHAR(500) NULL    COMMENT '追踪URL模板',
  PRINT_FORMAT VARCHAR(50) NULL    COMMENT '面单打印格式',
  ADDITIONAL_PROPERTIES LONGTEXT NULL    COMMENT '扩展参数',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_carrier_config primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_shipment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CARRIER_ID BIGINT NOT NULL    COMMENT '承运商ID',
  CARRIER_CONFIG_ID BIGINT NULL    COMMENT '承运商配置ID',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  SHIPMENT_DATE DATE NULL    COMMENT '发运日期',
  TRACKING_NO VARCHAR(100) NULL    COMMENT '运单号',
  LABEL_URL VARCHAR(500) NULL    COMMENT '面单URL',
  FREIGHT_AMOUNT DECIMAL(20,4) NULL    COMMENT '运费',
  FREIGHT_CURRENCY_ID BIGINT NULL    COMMENT '运费币种',
  FREIGHT_TERMS VARCHAR(20) NULL    COMMENT '运费条款',
  FREIGHT_SETTLEMENT_STATUS VARCHAR(20) NULL    COMMENT '运费结算状态',
  TOTAL_WEIGHT DECIMAL(12,3) NULL    COMMENT '总重量(kg)',
  TOTAL_VOLUME DECIMAL(12,6) NULL    COMMENT '总体积(m³)',
  TOTAL_PARCELS INTEGER default 1  NULL    COMMENT '总包裹数',
  RECEIVER_NAME VARCHAR(100) NULL    COMMENT '收货人',
  RECEIVER_PHONE VARCHAR(30) NULL    COMMENT '收货人电话',
  RECEIVER_ADDRESS VARCHAR(500) NULL    COMMENT '收货地址',
  RECEIVER_COUNTRY VARCHAR(100) NULL    COMMENT '国家',
  RECEIVER_PROVINCE VARCHAR(100) NULL    COMMENT '省份',
  RECEIVER_CITY VARCHAR(100) NULL    COMMENT '城市',
  RECEIVER_DISTRICT VARCHAR(100) NULL    COMMENT '区县',
  SENDER_NAME VARCHAR(100) NULL    COMMENT '发货人',
  SENDER_PHONE VARCHAR(30) NULL    COMMENT '发货人电话',
  SENDER_ADDRESS VARCHAR(500) NULL    COMMENT '发货地址',
  ESTIMATED_DELIVERY_DATE DATE NULL    COMMENT '预计送达日期',
  ACTUAL_DELIVERY_DATE DATE NULL    COMMENT '实际送达日期',
  SIGNED_BY VARCHAR(100) NULL    COMMENT '签收人',
  SHIPPER_ID BIGINT NULL    COMMENT '发货员(职员)',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_shipment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_shipment_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SHIPMENT_ID BIGINT NOT NULL    COMMENT '发运单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '数量',
  UNIT VARCHAR(50) NULL    COMMENT '单位',
  PACKAGE_DESCRIPTION VARCHAR(500) NULL    COMMENT '包装说明',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_shipment_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_shipment_parcel(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SHIPMENT_ID BIGINT NOT NULL    COMMENT '发运单ID',
  PARCEL_NO VARCHAR(50) NOT NULL    COMMENT '包裹编号',
  TRACKING_NO VARCHAR(100) NULL    COMMENT '运单号',
  LABEL_URL VARCHAR(500) NULL    COMMENT '面单URL',
  WEIGHT DECIMAL(12,3) NULL    COMMENT '重量(kg)',
  LENGTH DECIMAL(12,2) NULL    COMMENT '长(cm)',
  WIDTH DECIMAL(12,2) NULL    COMMENT '宽(cm)',
  HEIGHT DECIMAL(12,2) NULL    COMMENT '高(cm)',
  DECLARED_VALUE DECIMAL(20,4) NULL    COMMENT '申报价值',
  IS_ACTIVE INTEGER default 1  NOT NULL    COMMENT '是否有效',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_shipment_parcel primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_log_shipment_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SHIPMENT_ID BIGINT NOT NULL    COMMENT '发运单ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  GATEWAY_ID VARCHAR(50) NOT NULL    COMMENT '网关标识',
  ACTION_TYPE VARCHAR(20) NOT NULL    COMMENT '操作类型',
  REQUEST_BODY LONGTEXT NULL    COMMENT '请求报文',
  RESPONSE_BODY LONGTEXT NULL    COMMENT '响应报文',
  HTTP_STATUS INTEGER NULL    COMMENT 'HTTP状态码',
  ERROR_CODE VARCHAR(100) NULL    COMMENT '错误码',
  ERROR_MESSAGE VARCHAR(2000) NULL    COMMENT '错误信息',
  IS_SUCCESS BOOLEAN default 1  NULL    COMMENT '是否成功',
  EXECUTED_AT DATETIME NOT NULL    COMMENT '执行时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_log_shipment_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_employee COMMENT 'ErpMdEmployee';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_material COMMENT 'ErpMdMaterial';
                
   ALTER TABLE erp_log_carrier COMMENT '承运商';
                
   ALTER TABLE erp_log_delivery_window COMMENT '配送时间窗口';
                
   ALTER TABLE erp_log_carrier_config COMMENT '承运商配置';
                
   ALTER TABLE erp_log_shipment COMMENT '发运单';
                
   ALTER TABLE erp_log_shipment_line COMMENT '发运明细';
                
   ALTER TABLE erp_log_shipment_parcel COMMENT '包裹';
                
   ALTER TABLE erp_log_shipment_log COMMENT '网关交互日志';
                
