
CREATE TABLE erp_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  CONTRACT_TYPE VARCHAR(20) NOT NULL    COMMENT '适用合同类型',
  CONTENT_TEMPLATE VARCHAR(4000) NULL    COMMENT '模板内容',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_approval_matrix(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  MIN_AMOUNT DECIMAL(18,2) NULL    COMMENT '最小金额',
  MAX_AMOUNT DECIMAL(18,2) NULL    COMMENT '最大金额',
  APPROVER_ROLE VARCHAR(50) NOT NULL    COMMENT '审批角色',
  APPROVAL_ORDER INTEGER NOT NULL    COMMENT '审批顺序',
  CONTRACT_TYPE VARCHAR(50) NULL    COMMENT '适用合同类型',
  ALLOW_SKIP BOOLEAN default 0  NULL    COMMENT '可跳过',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_approval_matrix primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '合同编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONTRACT_NAME VARCHAR(200) NOT NULL    COMMENT '合同名称',
  CONTRACT_TYPE VARCHAR(20) NOT NULL    COMMENT '合同类型',
  CONTRACT_DIRECTION VARCHAR(20) NOT NULL    COMMENT '合同方向',
  PARTNER_ID BIGINT NOT NULL    COMMENT '合作方',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  TOTAL_AMOUNT DECIMAL(20,4) NULL    COMMENT '合同总额',
  START_DATE DATE NOT NULL    COMMENT '生效日期',
  END_DATE DATE NOT NULL    COMMENT '到期日期',
  SIGN_DATE DATE NULL    COMMENT '签署日期',
  STATUS VARCHAR(20) NOT NULL    COMMENT '合同状态',
  TEMPLATE_ID BIGINT NULL    COMMENT '合同模板',
  PARENT_CONTRACT_ID BIGINT NULL    COMMENT '父合同',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '合同附件',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_ID BIGINT NOT NULL    COMMENT '合同ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '行描述',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract_version(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_ID BIGINT NOT NULL    COMMENT '合同ID',
  VERSION_NO INTEGER NOT NULL    COMMENT '版本号',
  VERSION_DATE DATE NOT NULL    COMMENT '版本日期',
  CONTENT VARCHAR(4000) NULL    COMMENT '版本内容',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '版本附件',
  IS_CURRENT BOOLEAN default 0  NULL    COMMENT '是否当前版本',
  STATUS VARCHAR(20) NOT NULL    COMMENT '版本状态',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '批准人',
  APPROVED_AT DATETIME NULL    COMMENT '批准时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract_version primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_approval_record(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_ID BIGINT NOT NULL    COMMENT '合同',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  APPROVAL_MATRIX_ID BIGINT NULL    COMMENT '审批矩阵',
  APPROVAL_ORDER INTEGER NULL    COMMENT '顺序号',
  APPROVER_ID VARCHAR(36) NULL    COMMENT '审批人',
  APPROVAL_STATUS VARCHAR(20) NOT NULL    COMMENT '审批状态',
  COMMENT VARCHAR(1000) NULL    COMMENT '审批意见',
  APPROVED_AT DATETIME NULL    COMMENT '通过时间',
  REJECTED_AT DATETIME NULL    COMMENT '驳回时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_approval_record primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_rebate_agreement(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '协议编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONTRACT_ID BIGINT NULL    COMMENT '关联合同',
  PARTNER_ID BIGINT NOT NULL    COMMENT '对方伙伴',
  REBATE_TYPE VARCHAR(20) NOT NULL    COMMENT '返利类型',
  AGREEMENT_DATE DATE NULL    COMMENT '签订日期',
  START_DATE DATE NOT NULL    COMMENT '有效期开始',
  END_DATE DATE NOT NULL    COMMENT '有效期结束',
  ACCRUAL_METHOD VARCHAR(20) NOT NULL    COMMENT '计提方法',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  TOTAL_ACCUMULATED_AMOUNT DECIMAL(18,2) NULL    COMMENT '当前累计金额',
  ESTIMATED_REBATE_AMOUNT DECIMAL(18,2) NULL    COMMENT '预估返利金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_rebate_agreement primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_document(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONTRACT_ID BIGINT NULL    COMMENT '关联合同',
  CODE VARCHAR(50) NOT NULL    COMMENT '文档编码',
  DOC_NAME VARCHAR(200) NOT NULL    COMMENT '文档名称',
  DOC_TYPE VARCHAR(50) NOT NULL    COMMENT '文档类型',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '附件',
  FILE_SIZE BIGINT NULL    COMMENT '文件大小(字节)',
  FILE_HASH VARCHAR(100) NULL    COMMENT '文件哈希',
  MIME_TYPE VARCHAR(100) NULL    COMMENT 'MIME类型',
  OCR_TEXT VARCHAR(4000) NULL    COMMENT 'OCR文本',
  OCR_STATUS VARCHAR(50) NULL    COMMENT 'OCR状态',
  FULL_TEXT_SEARCH VARCHAR(4000) NULL    COMMENT '全文检索',
  METADATA_TAGS VARCHAR(2000) NULL    COMMENT '元数据标签(JSON)',
  RETENTION_DATE DATE NULL    COMMENT '保留截止日期',
  ARCHIVE_DATE DATE NULL    COMMENT '归档日期',
  PURGE_DATE DATE NULL    COMMENT '销毁日期',
  IS_ARCHIVED BOOLEAN default 0  NULL    COMMENT '已归档',
  VERSION_NO INTEGER default 1  NULL    COMMENT '文档版本',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_document primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_invoice_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_LINE_ID BIGINT NOT NULL    COMMENT '合同行ID',
  PLAN_DATE DATE NULL    COMMENT '计划开票日期',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '开票金额',
  IS_INVOICED BOOLEAN default 0  NULL    COMMENT '是否已开票',
  INVOICE_BILL_CODE VARCHAR(50) NULL    COMMENT '关联发票号',
  INVOICE_DATE DATE NULL    COMMENT '实际开票日期',
  INVOICE_TERM VARCHAR(20) NOT NULL    COMMENT '开票条款',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_invoice_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_consumption_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_LINE_ID BIGINT NOT NULL    COMMENT '合同行ID',
  CONSUMPTION_DATE DATE NOT NULL    COMMENT '消耗日期',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '消耗数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_consumption_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_volume_discount(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_LINE_ID BIGINT NOT NULL    COMMENT '合同行',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FROM_QTY DECIMAL(20,4) NOT NULL    COMMENT '起始数量',
  TO_QTY DECIMAL(20,4) NULL    COMMENT '截止数量',
  DISCOUNT_PERCENT DECIMAL(10,2) NOT NULL    COMMENT '折扣百分比',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '覆盖单价',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_volume_discount primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_signature_request(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONTRACT_VERSION_ID BIGINT NOT NULL    COMMENT '合同版本',
  PROVIDER VARCHAR(50) NOT NULL    COMMENT '签名提供商',
  PROVIDER_REQUEST_ID VARCHAR(200) NULL    COMMENT '提供商请求ID',
  STATUS VARCHAR(50) NOT NULL    COMMENT '签章状态',
  SIGNERS VARCHAR(2000) NULL    COMMENT '签署人(JSON)',
  SIGNING_DEADLINE DATE NULL    COMMENT '签署截止日期',
  COMPLETED_AT DATETIME NULL    COMMENT '签署完成时间',
  CERTIFICATE_URL VARCHAR(1000) NULL    COMMENT '完成证书URL',
  EVIDENCE_NO VARCHAR(200) NULL    COMMENT '存证编号',
  ATTACHMENT_FILE_ID VARCHAR(200) NULL    COMMENT '已签署文件',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误信息',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_signature_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_rebate_tier(
  ID BIGINT NOT NULL    COMMENT 'ID',
  REBATE_AGREEMENT_ID BIGINT NOT NULL    COMMENT '返利协议',
  FROM_AMOUNT DECIMAL(18,2) NOT NULL    COMMENT '起始金额',
  TO_AMOUNT DECIMAL(18,2) NULL    COMMENT '截止金额',
  REBATE_PERCENT DECIMAL(10,2) NULL    COMMENT '返利比例',
  REBATE_AMOUNT DECIMAL(18,2) NULL    COMMENT '固定返利金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_rebate_tier primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_rebate_accrual(
  ID BIGINT NOT NULL    COMMENT 'ID',
  REBATE_AGREEMENT_ID BIGINT NOT NULL    COMMENT '返利协议',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  BILL_AMOUNT_SOURCE DECIMAL(18,2) NULL    COMMENT '单据金额(源币种)',
  ACCRUED_REBATE DECIMAL(18,2) NULL    COMMENT '计提返利金额',
  ACCRUAL_DATE DATE NULL    COMMENT '计提日期',
  IS_SETTLED BOOLEAN default 0  NULL    COMMENT '已结算',
  SETTLED_DATE DATE NULL    COMMENT '结算日期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_rebate_accrual primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_rebate_settlement(
  ID BIGINT NOT NULL    COMMENT 'ID',
  REBATE_AGREEMENT_ID BIGINT NOT NULL    COMMENT '返利协议',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SETTLEMENT_DATE DATE NOT NULL    COMMENT '结算日期',
  TOTAL_REBATE_AMOUNT DECIMAL(18,2) NULL    COMMENT '结算返利总额',
  CREDIT_MEMO_BILL_TYPE VARCHAR(50) NULL    COMMENT '信用单类型',
  CREDIT_MEMO_BILL_CODE VARCHAR(50) NULL    COMMENT '信用单号',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(50) NULL    COMMENT '过账人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_rebate_settlement primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_ct_template COMMENT '合同模板';
                
   ALTER TABLE erp_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_ct_approval_matrix COMMENT '审批矩阵';
                
   ALTER TABLE erp_ct_contract COMMENT '合同';
                
   ALTER TABLE erp_ct_contract_line COMMENT '合同行';
                
   ALTER TABLE erp_ct_contract_version COMMENT '合同版本';
                
   ALTER TABLE erp_ct_approval_record COMMENT '审批记录';
                
   ALTER TABLE erp_ct_rebate_agreement COMMENT '返利协议';
                
   ALTER TABLE erp_ct_document COMMENT '合同文档';
                
   ALTER TABLE erp_ct_invoice_plan COMMENT '开票计划';
                
   ALTER TABLE erp_ct_consumption_line COMMENT '消耗计费行';
                
   ALTER TABLE erp_ct_volume_discount COMMENT '批量折扣';
                
   ALTER TABLE erp_ct_signature_request COMMENT '签章请求';
                
   ALTER TABLE erp_ct_rebate_tier COMMENT '返利阶梯';
                
   ALTER TABLE erp_ct_rebate_accrual COMMENT '返利计提明细';
                
   ALTER TABLE erp_ct_rebate_settlement COMMENT '返利结算单';
                
