
CREATE TABLE erp_md_md_partner(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  CONTRACT_TYPE INTEGER NOT NULL    COMMENT '适用合同类型',
  CONTENT_TEMPLATE VARCHAR(4000) NULL    COMMENT '模板内容',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '合同编号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONTRACT_NAME VARCHAR(200) NOT NULL    COMMENT '合同名称',
  CONTRACT_TYPE INTEGER NOT NULL    COMMENT '合同类型',
  CONTRACT_DIRECTION INTEGER NOT NULL    COMMENT '合同方向',
  PARTNER_ID BIGINT NOT NULL    COMMENT '合作方',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  TOTAL_AMOUNT DECIMAL(20,4) NULL    COMMENT '合同总额',
  START_DATE DATE NOT NULL    COMMENT '生效日期',
  END_DATE DATE NOT NULL    COMMENT '到期日期',
  SIGN_DATE DATE NULL    COMMENT '签署日期',
  STATUS INTEGER NOT NULL    COMMENT '合同状态',
  TEMPLATE_ID BIGINT NULL    COMMENT '合同模板',
  PARENT_CONTRACT_ID BIGINT NULL    COMMENT '父合同',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  ATTACHMENT_ID BIGINT NULL    COMMENT '合同附件',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_ID BIGINT NOT NULL    COMMENT '合同ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NULL    COMMENT '物料',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '行描述',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_contract_version(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_ID BIGINT NOT NULL    COMMENT '合同ID',
  VERSION_NO INTEGER NOT NULL    COMMENT '版本号',
  VERSION_DATE DATE NOT NULL    COMMENT '版本日期',
  CONTENT VARCHAR(4000) NULL    COMMENT '版本内容',
  ATTACHMENT_ID BIGINT NULL    COMMENT '版本附件',
  IS_CURRENT BOOLEAN default 0  NULL    COMMENT '是否当前版本',
  STATUS INTEGER NOT NULL    COMMENT '版本状态',
  APPROVED_BY BIGINT NULL    COMMENT '批准人',
  APPROVED_AT DATETIME NULL    COMMENT '批准时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_contract_version primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_invoice_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_LINE_ID BIGINT NOT NULL    COMMENT '合同行ID',
  PLAN_DATE DATE NULL    COMMENT '计划开票日期',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '开票金额',
  IS_INVOICED BOOLEAN default 0  NULL    COMMENT '是否已开票',
  INVOICE_BILL_CODE VARCHAR(50) NULL    COMMENT '关联发票号',
  INVOICE_DATE DATE NULL    COMMENT '实际开票日期',
  INVOICE_TERM INTEGER NOT NULL    COMMENT '开票条款',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_invoice_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ct_consumption_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONTRACT_LINE_ID BIGINT NOT NULL    COMMENT '合同行ID',
  CONSUMPTION_DATE DATE NOT NULL    COMMENT '消耗日期',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '消耗数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额',
  SOURCE_BILL_TYPE VARCHAR(50) NULL    COMMENT '来源单据类型',
  SOURCE_BILL_CODE VARCHAR(50) NULL    COMMENT '来源单据号',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_ct_consumption_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_partner COMMENT 'ErpMdPartner';
                
   ALTER TABLE erp_ct_template COMMENT '合同模板';
                
   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_ct_contract COMMENT '合同';
                
   ALTER TABLE erp_ct_contract_line COMMENT '合同行';
                
   ALTER TABLE erp_ct_contract_version COMMENT '合同版本';
                
   ALTER TABLE erp_ct_invoice_plan COMMENT '开票计划';
                
   ALTER TABLE erp_ct_consumption_line COMMENT '消耗计费行';
                
