
CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_location(
  ID BIGINT NULL    COMMENT 'null',
  WAREHOUSE_ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_location primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SYMBOL VARCHAR(50) NULL    COMMENT 'null',
  DECIMAL_PLACES INTEGER NULL    COMMENT 'null',
  IS_FUNCTIONAL BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_subject(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  SUBJECT_CLASS INTEGER NULL    COMMENT 'null',
  DIRECTION INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_subject primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_category(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  constraint PK_erp_md_material_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_asset_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '类别编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '类别名称',
  DEPRECIATION_METHOD VARCHAR(20) NULL    COMMENT '默认折旧方法',
  USEFUL_LIFE_MONTHS INTEGER NULL    COMMENT '默认使用年限(月)',
  SUBJECT_ID BIGINT NULL    COMMENT '资产科目',
  DEPRECIATION_SUBJECT_ID BIGINT NULL    COMMENT '累计折旧科目',
  EXPENSE_SUBJECT_ID BIGINT NULL    COMMENT '折旧费用科目',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DISPOSAL_GAIN_LOSS_SUBJECT_ID BIGINT NULL    COMMENT '清理损益科目',
  CIP_SUBJECT_ID BIGINT NULL    COMMENT '在建工程科目',
  constraint PK_erp_ast_asset_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_asset(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '资产编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '资产名称',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  CATEGORY_ID BIGINT NULL    COMMENT '资产类别',
  ACQUISITION_DATE DATE NOT NULL    COMMENT '取得日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  ORIGINAL_VALUE DECIMAL(20,4) NOT NULL    COMMENT '原值',
  CURRENT_VALUE DECIMAL(20,4) NULL    COMMENT '当前价值',
  RESIDUAL_VALUE DECIMAL(20,4) default 0  NULL    COMMENT '残值',
  DEPRECIATION_METHOD VARCHAR(20) NULL    COMMENT '折旧方法',
  DEPRECIATION_RATE DECIMAL(10,6) NULL    COMMENT '折旧率',
  USEFUL_LIFE_MONTHS INTEGER NULL    COMMENT '使用年限(月)',
  DEPARTMENT_ID BIGINT NULL    COMMENT '使用部门',
  LOCATION_ID BIGINT NULL    COMMENT '使用地点',
  EMPLOYEE_ID BIGINT NULL    COMMENT '使用人(职员)',
  STAFF_ID BIGINT NULL    COMMENT '使用人(往来单位,旧字段保留)',
  BRAND_MODEL VARCHAR(200) NULL    COMMENT '品牌型号',
  STATUS VARCHAR(20) NOT NULL    COMMENT '资产状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  ACCUMULATED_DEPRECIATION DECIMAL(20,4) default 0  NULL    COMMENT '累计折旧',
  NET_BOOK_VALUE DECIMAL(20,4) default 0  NULL    COMMENT '净值',
  constraint PK_erp_ast_asset primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_asset_capitalization(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ASSET_CODE VARCHAR(50) NULL    COMMENT '资产编码',
  ASSET_NAME VARCHAR(200) NULL    COMMENT '资产名称',
  CATEGORY_ID BIGINT NULL    COMMENT '资产类别',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  CAPITALIZATION_DATE DATE NOT NULL    COMMENT '资本化日期',
  ORIGINAL_VALUE DECIMAL(20,4) NOT NULL    COMMENT '原值',
  SOURCE_TYPE VARCHAR(20) NOT NULL    COMMENT '来源类型',
  SOURCE_CODE VARCHAR(50) NULL    COMMENT '来源单号',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  BUSINESS_DATE DATE NULL    COMMENT '业务日期',
  EXCHANGE_RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_asset_capitalization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_depreciation_schedule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ASSET_ID BIGINT NOT NULL    COMMENT '资产ID',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  PERIOD VARCHAR(20) NOT NULL    COMMENT '折旧期间',
  PLANNED_AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '计划折旧额',
  ACTUAL_AMOUNT DECIMAL(20,4) NULL    COMMENT '实际折旧额',
  ACCUMULATED_DEPRECIATION DECIMAL(20,4) default 0  NULL    COMMENT '累计折旧',
  NET_BOOK_VALUE DECIMAL(20,4) NULL    COMMENT '净值',
  STATUS VARCHAR(20) NOT NULL    COMMENT '执行状态',
  EXECUTED_AT DATETIME NULL    COMMENT '执行时间',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  VOUCHER_ID BIGINT NULL    COMMENT '凭证ID',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  BUSINESS_DATE DATE NULL    COMMENT '业务日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_depreciation_schedule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_movement(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ASSET_ID BIGINT NOT NULL    COMMENT '资产ID',
  BUSINESS_DATE DATE NOT NULL    COMMENT '移动日期',
  FROM_DATE DATE NOT NULL    COMMENT '开始日期',
  THRU_DATE DATE NULL    COMMENT '截止日期',
  FROM_DEPARTMENT_ID BIGINT NULL    COMMENT '原使用部门',
  TO_DEPARTMENT_ID BIGINT NULL    COMMENT '新使用部门',
  FROM_STAFF_ID BIGINT NULL    COMMENT '原使用人',
  TO_STAFF_ID BIGINT NULL    COMMENT '新使用人',
  FROM_LOCATION_ID BIGINT NULL    COMMENT '原使用地点',
  TO_LOCATION_ID BIGINT NULL    COMMENT '新使用地点',
  HANDLER_ID BIGINT NULL    COMMENT '经办人',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  DOC_VERSION VARCHAR(20) default '1'  NOT NULL    COMMENT '单据版本',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_movement primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_value_adjustment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ASSET_ID BIGINT NOT NULL    COMMENT '资产ID',
  BUSINESS_DATE DATE NOT NULL    COMMENT '调整日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  ADJUSTMENT_TYPE VARCHAR(20) NOT NULL    COMMENT '调整类型',
  ADJUSTMENT_AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '调整金额',
  REASON VARCHAR(500) NULL    COMMENT '调整原因',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_value_adjustment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_disposal(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ASSET_ID BIGINT NOT NULL    COMMENT '资产ID',
  DISPOSAL_TYPE VARCHAR(20) NOT NULL    COMMENT '处置类型',
  DISPOSAL_AMOUNT DECIMAL(20,4) NULL    COMMENT '处置金额',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  BUSINESS_DATE DATE NOT NULL    COMMENT '处置日期',
  GAIN_LOSS DECIMAL(20,4) NULL    COMMENT '损益',
  REASON VARCHAR(20) NULL    COMMENT '处置原因',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_disposal primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_cip(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工程编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '工程名称',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  CATEGORY_ID BIGINT NULL    COMMENT '预定资产类别(完工后转入)',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  BUSINESS_DATE DATE NOT NULL    COMMENT '开工日期',
  ESTIMATED_COMPLETION_DATE DATE NULL    COMMENT '预计完工日期',
  ACCUMULATED_COST DECIMAL(20,4) default 0  NULL    COMMENT '累计归集成本',
  IS_COMPLETED BOOLEAN default 0  NULL    COMMENT '是否已转固',
  COMPLETED_ASSET_ID BIGINT NULL    COMMENT '完工转出资产',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  POSTED BOOLEAN default 0  NULL    COMMENT '是否已过账',
  POSTED_AT DATETIME(3) NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(50) NULL    COMMENT '过账人',
  EXCHANGE_RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_cip primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_split(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SOURCE_ASSET_ID BIGINT NOT NULL    COMMENT '被拆分资产',
  BUSINESS_DATE DATE NOT NULL    COMMENT '拆分日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  SPLIT_REASON VARCHAR(500) NULL    COMMENT '拆分原因',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  EXCHANGE_RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_split primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_ast_merge(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TARGET_ASSET_ID BIGINT NOT NULL    COMMENT '合并目标资产',
  BUSINESS_DATE DATE NOT NULL    COMMENT '合并日期',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  MERGE_REASON VARCHAR(500) NULL    COMMENT '合并原因',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  EXCHANGE_RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '源币种金额',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '本位币金额',
  constraint PK_erp_ast_merge primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_location COMMENT '库位';
                
   ALTER TABLE erp_md_employee COMMENT '职员';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_subject COMMENT '会计科目';
                
   ALTER TABLE erp_md_material_category COMMENT '物料分类';
                
   ALTER TABLE erp_ast_asset_category COMMENT '资产类别';
                
   ALTER TABLE erp_ast_asset COMMENT '固定资产';
                
   ALTER TABLE erp_ast_asset_capitalization COMMENT '资产资本化';
                
   ALTER TABLE erp_ast_depreciation_schedule COMMENT '折旧计划';
                
   ALTER TABLE erp_ast_movement COMMENT '资产移动';
                
   ALTER TABLE erp_ast_value_adjustment COMMENT '资产价值调整';
                
   ALTER TABLE erp_ast_disposal COMMENT '资产处置';
                
   ALTER TABLE erp_ast_cip COMMENT '在建工程';
                
   ALTER TABLE erp_ast_split COMMENT '资产拆分单';
                
   ALTER TABLE erp_ast_merge COMMENT '资产合并单';
                
