import { execFile } from 'child_process';
import { promisify } from 'util';
import { readFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const execFileAsync = promisify(execFile);

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const rootDir = path.join(__dirname, '..');

const ignoredPathParts = [
  'dist/',
  'node_modules/',
  'coverage/',
  'test-results/',
  '.opencode/',
];
const rootPrefixes = ['src/', 'lib/', 'tools/', 'tests/', 'packages/', 'apps/', 'docs/', 'module-'];

const CODE_EXT = {
  '.ts': 'TypeScript',
  '.tsx': 'TypeScript (React)',
  '.js': 'JavaScript',
  '.jsx': 'JavaScript (React)',
  '.mjs': 'JavaScript (ESM)',
  '.java': 'Java',
  '.xml': 'XML',
  '.yaml': 'YAML',
  '.yml': 'YAML',
  '.css': 'CSS',
  '.scss': 'SCSS',
  '.json': 'JSON',
  '.md': 'Markdown',
  '.html': 'HTML',
  '.svg': 'SVG',
  '.sh': 'Shell',
  '.py': 'Python',
};

const CODE_ONLY_EXT = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.java', '.xml', '.yaml', '.yml', '.css', '.scss']);

const CONFIG_EXTS = new Set(['.xml', '.yaml', '.yml']);

function isAutoGenerated(filePath) {
  const parts = filePath.replace(/\\/g, '/').split('/');
  if (parts.some(p => p === '_gen')) return true;
  // _ prefix rule: applies to Java, XML, YAML (Nop platform convention)
  const ext = path.extname(filePath);
  if (['.java', '.xml', '.yaml', '.yml'].includes(ext) && path.basename(filePath).startsWith('_')) return true;
  return false;
}

function isTracked(filePath) {
  if (!rootPrefixes.some((p) => filePath.startsWith(p))) return false;
  if (ignoredPathParts.some((p) => filePath.includes(p))) return false;
  return true;
}

async function getFiles() {
  const { stdout } = await execFileAsync('git', ['ls-files'], {
    cwd: rootDir,
    maxBuffer: 20 * 1024 * 1024,
  });
  return stdout.split('\n').filter(Boolean).filter(isTracked);
}

function countLines(content) {
  const lines = content.split('\n');
  const total = lines.length;
  let blank = 0;
  let comment = 0;
  let inBlock = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === '') {
      blank++;
      continue;
    }
    if (inBlock) {
      comment++;
      if (trimmed.includes('*/')) inBlock = false;
      continue;
    }
    if (trimmed.startsWith('//') || trimmed.startsWith('*') || trimmed.startsWith('/*')) {
      comment++;
      if (trimmed.startsWith('/*') && !trimmed.includes('*/')) {
        inBlock = true;
      }
      continue;
    }
    if (trimmed.startsWith('#') || trimmed.startsWith('<!--')) {
      comment++;
      continue;
    }
  }

  return { total, blank, comment, code: total - blank - comment };
}

function getPackage(filePath) {
  const match = filePath.match(/^(apps|packages)\/([^/]+)/);
  if (match) return `${match[1]}/${match[2]}`;
  const modMatch = filePath.match(/^(module-[^/]+)/);
  if (modMatch) return modMatch[1];
  return filePath.split('/')[0];
}

function isTestFile(filePath) {
  if (filePath.includes('.test.') || filePath.includes('.spec.') || filePath.includes('__tests__')) return true;
  if (filePath.endsWith('Test.java') || filePath.endsWith('Tests.java')) return true;
  if (filePath.includes('/src/test/java/')) return true;
  return false;
}

function analyzeTsComplexity(content, filePath) {
  const isTsx = filePath.endsWith('.tsx') || filePath.endsWith('.jsx');
  const patterns = [
    { re: /\bfunction\s+\w+/g, kind: 'function' },
    { re: /\bconst\s+\w+\s*=\s*(\([^)]*\)|[a-zA-Z_]\w*)\s*=>/g, kind: 'arrow' },
    { re: /\bconst\s+\w+\s*=\s*function/g, kind: 'function-expr' },
  ];

  if (isTsx) {
    patterns.push(
      { re: /\bexport\s+default\s+function\s+\w+/g, kind: 'component' },
      {
        re: /\bfunction\s+\w+\s*\([^)]*\)\s*(?::\s*[^{]+)?\{[^]*?return\s*[(<]/g,
        kind: 'component',
      },
    );
  }

  let functionCount = 0;
  for (const { re } of patterns) {
    const matches = content.match(re);
    if (matches) functionCount += matches.length;
  }

  const lines = content.split('\n');
  let codeLineCount = 0;
  for (const line of lines) {
    const t = line.trim();
    if (t && !t.startsWith('//') && !t.startsWith('*') && !t.startsWith('/*')) codeLineCount++;
  }

  const branches =
    (content.match(/\bif\s*\(/g) || []).length +
    (content.match(/\belse\s+if\b/g) || []).length +
    (content.match(/\bswitch\s*\(/g) || []).length +
    (content.match(/\bcase\s+/g) || []).length +
    (content.match(/\?\s*.+\s*:/g) || []).length;

  const imports = (content.match(/^import\s/gm) || []).length;
  const exports = (content.match(/^export\s/gm) || []).length;

  return { functionCount, codeLines: codeLineCount, branches, imports, exports };
}

function formatNumber(n) {
  return n.toLocaleString('en-US');
}

function bar(value, max, width = 30) {
  const filled = max > 0 ? Math.round((value / max) * width) : 0;
  return '\u2588'.repeat(filled) + '\u2591'.repeat(width - filled);
}

function printSection(title) {
  console.log(`\n${'='.repeat(70)}`);
  console.log(`  ${title}`);
  console.log('='.repeat(70));
}

async function main() {
  const files = await getFiles();
  const projectName = path.basename(rootDir);
  console.log(`\n  ${projectName} Code Statistics`);
  console.log(`  Generated: ${new Date().toISOString().slice(0, 10)}`);
  console.log(`  Tracked files analyzed: ${formatNumber(files.length)}`);

  const packageData = new Map();
  const langData = new Map();
  let totalLoc = 0,
    totalBlank = 0,
    totalComment = 0,
    totalCode = 0;
  let srcFiles = 0,
    testFiles = 0,
    otherFiles = 0;
  let srcCode = 0,
    testCode = 0,
    srcLoc = 0,
    testLoc = 0;
  const docsCategories = new Map();
  let docsTotalFiles = 0,
    docsTotalLoc = 0;
  const complexityAcc = {
    functionCount: 0,
    codeLines: 0,
    branches: 0,
    imports: 0,
    exports: 0,
  };
  const packageComplexity = new Map();
  // Per-language auto-gen tracking (all languages)
  const langGenMap = new Map();

  // Java-specific domain tracking
  let javaGenFiles = 0, javaGenLoc = 0, javaGenCode = 0, javaGenBlank = 0, javaGenComment = 0;
  let javaHandFiles = 0, javaHandLoc = 0, javaHandCode = 0, javaHandBlank = 0, javaHandComment = 0;
  const javaDomainGen = new Map();
  const javaDomainHand = new Map();

  // Config files (XML/YAML) domain tracking
  let cfgGenFiles = 0, cfgGenLoc = 0, cfgGenCode = 0, cfgGenBlank = 0, cfgGenComment = 0;
  let cfgHandFiles = 0, cfgHandLoc = 0, cfgHandCode = 0, cfgHandBlank = 0, cfgHandComment = 0;
  const cfgDomainGen = new Map();
  const cfgDomainHand = new Map();

  const fileSizes = [];

  for (const filePath of files) {
    const ext = path.extname(filePath);
    const lang = CODE_EXT[ext];
    if (!lang) continue;

    let content;
    try {
      content = await readFile(path.join(rootDir, filePath), 'utf-8');
    } catch {
      continue;
    }

    const lc = countLines(content);
    const pkg = getPackage(filePath);
    const isTest = isTestFile(filePath);

    if (!packageData.has(pkg)) {
      packageData.set(pkg, {
        files: 0,
        loc: 0,
        blank: 0,
        comment: 0,
        code: 0,
        srcFiles: 0,
        testFiles: 0,
        otherFiles: 0,
        langs: new Map(),
      });
    }
    const pd = packageData.get(pkg);
    pd.files++;
    pd.loc += lc.total;
    pd.blank += lc.blank;
    pd.comment += lc.comment;
    pd.code += lc.code;
    if (isTest) pd.testFiles++;
    else if (CODE_ONLY_EXT.has(ext)) pd.srcFiles++;
    else pd.otherFiles++;

    const langKey = lang;
    if (!pd.langs.has(langKey)) pd.langs.set(langKey, { files: 0, code: 0 });
    pd.langs.get(langKey).files++;
    pd.langs.get(langKey).code += lc.code;

    if (!langData.has(langKey))
      langData.set(langKey, { files: 0, loc: 0, blank: 0, comment: 0, code: 0 });
    const ld = langData.get(langKey);
    ld.files++;
    ld.loc += lc.total;
    ld.blank += lc.blank;
    ld.comment += lc.comment;
    ld.code += lc.code;

    totalLoc += lc.total;
    totalBlank += lc.blank;
    totalComment += lc.comment;
    totalCode += lc.code;

    if (isTest) testFiles++;
    else if (CODE_ONLY_EXT.has(ext)) srcFiles++;
    else otherFiles++;

    if (isTest) {
      testCode += lc.code;
      testLoc += lc.total;
    } else if (CODE_ONLY_EXT.has(ext)) {
      srcCode += lc.code;
      srcLoc += lc.total;
    }

    // Auto-gen classification for every file
    const autoGen = isAutoGenerated(filePath) ||
      ((ext === '.java' || CONFIG_EXTS.has(ext)) && content.includes('__XGEN_FORCE_OVERRIDE__'));

    // Per-language gen/hand tracking
    if (!langGenMap.has(langKey)) {
      langGenMap.set(langKey, { genFiles: 0, genLoc: 0, genCode: 0, genBlank: 0, genComment: 0, handFiles: 0, handLoc: 0, handCode: 0, handBlank: 0, handComment: 0 });
    }
    const lg = langGenMap.get(langKey);
    if (autoGen) {
      lg.genFiles++; lg.genLoc += lc.total; lg.genCode += lc.code;
      lg.genBlank += lc.blank; lg.genComment += lc.comment;
    } else {
      lg.handFiles++; lg.handLoc += lc.total; lg.handCode += lc.code;
      lg.handBlank += lc.blank; lg.handComment += lc.comment;
    }

    // Java-specific: domain breakdown (in addition to per-language gen/hand above)
    if (ext === '.java') {
      if (autoGen) {
        javaGenFiles++; javaGenLoc += lc.total; javaGenCode += lc.code;
        javaGenBlank += lc.blank; javaGenComment += lc.comment;
      } else {
        javaHandFiles++; javaHandLoc += lc.total; javaHandCode += lc.code;
        javaHandBlank += lc.blank; javaHandComment += lc.comment;
      }
      const modMatch = filePath.match(/^module-([^/]+)/);
      const domain = modMatch ? modMatch[1] : 'other';
      const map = autoGen ? javaDomainGen : javaDomainHand;
      if (!map.has(domain)) map.set(domain, { files: 0, loc: 0, code: 0 });
      const dd = map.get(domain);
      dd.files++; dd.loc += lc.total; dd.code += lc.code;
    }

    // Config files (XML/YAML): domain breakdown
    if (CONFIG_EXTS.has(ext)) {
      if (autoGen) {
        cfgGenFiles++; cfgGenLoc += lc.total; cfgGenCode += lc.code;
        cfgGenBlank += lc.blank; cfgGenComment += lc.comment;
      } else {
        cfgHandFiles++; cfgHandLoc += lc.total; cfgHandCode += lc.code;
        cfgHandBlank += lc.blank; cfgHandComment += lc.comment;
      }
      const modMatch = filePath.match(/^module-([^/]+)/);
      const domain = modMatch ? modMatch[1] : 'other';
      const map = autoGen ? cfgDomainGen : cfgDomainHand;
      if (!map.has(domain)) map.set(domain, { files: 0, loc: 0, code: 0 });
      const dd = map.get(domain);
      dd.files++; dd.loc += lc.total; dd.code += lc.code;
    }

    // TS/JS complexity
    if (ext === '.ts' || ext === '.tsx' || ext === '.js' || ext === '.jsx' || ext === '.mjs') {
      const cx = analyzeTsComplexity(content, filePath);
      complexityAcc.functionCount += cx.functionCount;
      complexityAcc.codeLines += cx.codeLines;
      complexityAcc.branches += cx.branches;
      complexityAcc.imports += cx.imports;
      complexityAcc.exports += cx.exports;

      if (!packageComplexity.has(pkg)) {
        packageComplexity.set(pkg, {
          functionCount: 0,
          codeLines: 0,
          branches: 0,
          imports: 0,
          exports: 0,
          files: 0,
        });
      }
      const pc = packageComplexity.get(pkg);
      pc.functionCount += cx.functionCount;
      pc.codeLines += cx.codeLines;
      pc.branches += cx.branches;
      pc.imports += cx.imports;
      pc.exports += cx.exports;
      pc.files++;
    }

    if (filePath.startsWith('docs/') && ext === '.md') {
      const parts = filePath.split('/');
      const category = parts.length > 2 ? parts[1] : 'root';
      if (!docsCategories.has(category)) {
        docsCategories.set(category, { files: 0, loc: 0, code: 0 });
      }
      const dc = docsCategories.get(category);
      dc.files++;
      dc.loc += lc.total;
      dc.code += lc.code;
      docsTotalFiles++;
      docsTotalLoc += lc.total;
    }

    fileSizes.push({ path: filePath, loc: lc.total, code: lc.code, ext, autoGen });
  }

  // ── Overall Summary ──
  printSection('Overall Summary');
  console.log(`
  Total files        : ${formatNumber(files.length)}
  Source files (code) : ${formatNumber(srcFiles)}
  Test files          : ${formatNumber(testFiles)}
  Other files         : ${formatNumber(otherFiles)}

  Total lines         : ${formatNumber(totalLoc)}
  Code lines          : ${formatNumber(totalCode)} (${totalLoc > 0 ? ((totalCode / totalLoc) * 100).toFixed(1) : '0'}%)
  Comment lines       : ${formatNumber(totalComment)} (${totalLoc > 0 ? ((totalComment / totalLoc) * 100).toFixed(1) : '0'}%)
  Blank lines         : ${formatNumber(totalBlank)} (${totalLoc > 0 ? ((totalBlank / totalLoc) * 100).toFixed(1) : '0'}%)

  Test-to-source ratio: ${srcFiles > 0 ? (testFiles / srcFiles).toFixed(2) : 'N/A'}
  Avg LOC per file    : ${files.length > 0 ? (totalLoc / files.length).toFixed(1) : '0'}
  Avg code per file   : ${files.length > 0 ? (totalCode / files.length).toFixed(1) : '0'}

  ── Source vs Test ───────────────────────────────────────
                    Files       LOC      Code
  Source files     : ${formatNumber(srcFiles).padStart(5)}  ${formatNumber(srcLoc).padStart(9)}  ${formatNumber(srcCode).padStart(9)}
  Test files       : ${formatNumber(testFiles).padStart(5)}  ${formatNumber(testLoc).padStart(9)}  ${formatNumber(testCode).padStart(9)}
  Test/Source(code): ${srcCode > 0 ? (testCode / srcCode).toFixed(2) : 'N/A'}`);

  // ── Java Auto-Generated vs Hand-Written ──
  if (javaHandFiles + javaGenFiles > 0) {
    printSection('Java: Auto-Generated vs Hand-Written');
    const javaTotalFiles = javaGenFiles + javaHandFiles;
    const javaTotalLoc = javaGenLoc + javaHandLoc;
    console.log(`
  Classification rules:
    • _gen/ directory          → auto-generated
    • _ prefix (e.g. _Foo.java) → auto-generated
    • __XGEN_FORCE_OVERRIDE__   → auto-generated (codegen force-overwrite)

                        Files         LOC        Code     Comment     Blank  Distribution
  ${'─'.repeat(95)}
  Auto-generated   : ${formatNumber(javaGenFiles).padStart(6)} ${formatNumber(javaGenLoc).padStart(10)} ${formatNumber(javaGenCode).padStart(10)} ${formatNumber(javaGenComment).padStart(10)} ${formatNumber(javaGenBlank).padStart(8)}  ${bar(javaGenCode, javaTotalLoc > 0 ? javaTotalLoc : 1, 20)}
  Hand-written     : ${formatNumber(javaHandFiles).padStart(6)} ${formatNumber(javaHandLoc).padStart(10)} ${formatNumber(javaHandCode).padStart(10)} ${formatNumber(javaHandComment).padStart(10)} ${formatNumber(javaHandBlank).padStart(8)}  ${bar(javaHandCode, javaTotalLoc > 0 ? javaTotalLoc : 1, 20)}
  ${'─'.repeat(95)}
  Total            : ${formatNumber(javaTotalFiles).padStart(6)} ${formatNumber(javaTotalLoc).padStart(10)} ${formatNumber(javaGenCode + javaHandCode).padStart(10)} ${formatNumber(javaGenComment + javaHandComment).padStart(10)} ${formatNumber(javaGenBlank + javaHandBlank).padStart(8)}

  Auto-gen ratio   : ${(javaGenFiles / javaTotalFiles * 100).toFixed(1)}% files, ${(javaGenLoc / javaTotalLoc * 100).toFixed(1)}% LOC
  Hand-write ratio : ${(javaHandFiles / javaTotalFiles * 100).toFixed(1)}% files, ${(javaHandLoc / javaTotalLoc * 100).toFixed(1)}% LOC

  ── Java by Domain ─────────────────────────────────────────────────

  ${'Domain'.padEnd(20)} ${'Total LOC'.padStart(10)} ${'Auto-gen'.padStart(10)} ${'Hand-wr'.padStart(10)} ${'Auto%'.padStart(7)}  ${'Files'.padStart(7)}
  ${'─'.repeat(68)}`);

    const allDomains = [...new Set([...javaDomainGen.keys(), ...javaDomainHand.keys()])].sort();
    const maxDomainLoc = Math.max(1, ...allDomains.map(d => {
      const g = javaDomainGen.get(d) || { loc: 0 };
      const h = javaDomainHand.get(d) || { loc: 0 };
      return g.loc + h.loc;
    }));
    for (const d of allDomains) {
      const g = javaDomainGen.get(d) || { files: 0, loc: 0, code: 0 };
      const h = javaDomainHand.get(d) || { files: 0, loc: 0, code: 0 };
      const total = g.loc + h.loc;
      const files = g.files + h.files;
      const pct = total > 0 ? (g.loc / total * 100).toFixed(1) : '0.0';
      console.log(`  ${d.padEnd(20)} ${formatNumber(total).padStart(10)} ${formatNumber(g.loc).padStart(10)} ${formatNumber(h.loc).padStart(10)} ${pct.padStart(6)}% ${formatNumber(files).padStart(7)} ${bar(total, maxDomainLoc, 10)}`);
    }

    // Largest handwritten Java files
    const handSizes = fileSizes.filter(f => f.ext === '.java' && !f.autoGen).sort((a, b) => b.code - a.code).slice(0, 15);
    if (handSizes.length > 0) {
      console.log(`\n  ── Largest Hand-written Java Files (top 15) ─────────────────`);
      for (const f of handSizes) {
        console.log(`  ${formatNumber(f.code).padStart(7)}  ${f.path}`);
      }
    }

    // Largest auto-gen Java files
    const genSizes = fileSizes.filter(f => f.ext === '.java' && f.autoGen).sort((a, b) => b.code - a.code).slice(0, 15);
    if (genSizes.length > 0) {
      console.log(`\n  ── Largest Auto-generated Java Files (top 15) ──────────────`);
      for (const f of genSizes) {
        console.log(`  ${formatNumber(f.code).padStart(7)}  ${f.path}`);
      }
    }
  }

  // ── Config Files (XML/YAML): Auto-Generated vs Hand-Written ──
  if (cfgHandFiles + cfgGenFiles > 0) {
    printSection('Config Files (XML/YAML): Auto-Generated vs Hand-Written');
    const cfgTotalFiles = cfgGenFiles + cfgHandFiles;
    const cfgTotalLoc = cfgGenLoc + cfgHandLoc;
    console.log(`
  Classification rules: same as Java ( _gen/ , _ prefix , __XGEN_FORCE_OVERRIDE__ )

                        Files         LOC        Code     Comment     Blank  Distribution
  ${'─'.repeat(95)}
  Auto-generated   : ${formatNumber(cfgGenFiles).padStart(6)} ${formatNumber(cfgGenLoc).padStart(10)} ${formatNumber(cfgGenCode).padStart(10)} ${formatNumber(cfgGenComment).padStart(10)} ${formatNumber(cfgGenBlank).padStart(8)}  ${bar(cfgGenCode, cfgTotalLoc > 0 ? cfgTotalLoc : 1, 20)}
  Hand-written     : ${formatNumber(cfgHandFiles).padStart(6)} ${formatNumber(cfgHandLoc).padStart(10)} ${formatNumber(cfgHandCode).padStart(10)} ${formatNumber(cfgHandComment).padStart(10)} ${formatNumber(cfgHandBlank).padStart(8)}  ${bar(cfgHandCode, cfgTotalLoc > 0 ? cfgTotalLoc : 1, 20)}
  ${'─'.repeat(95)}
  Total            : ${formatNumber(cfgTotalFiles).padStart(6)} ${formatNumber(cfgTotalLoc).padStart(10)} ${formatNumber(cfgGenCode + cfgHandCode).padStart(10)} ${formatNumber(cfgGenComment + cfgHandComment).padStart(10)} ${formatNumber(cfgGenBlank + cfgHandBlank).padStart(8)}

  Auto-gen ratio   : ${(cfgGenFiles / cfgTotalFiles * 100).toFixed(1)}% files, ${(cfgGenLoc / cfgTotalLoc * 100).toFixed(1)}% LOC
  Hand-write ratio : ${(cfgHandFiles / cfgTotalFiles * 100).toFixed(1)}% files, ${(cfgHandLoc / cfgTotalLoc * 100).toFixed(1)}% LOC

  ── Config by Domain ───────────────────────────────────────────────

  ${'Domain'.padEnd(20)} ${'Total LOC'.padStart(10)} ${'Auto-gen'.padStart(10)} ${'Hand-wr'.padStart(10)} ${'Auto%'.padStart(7)}  ${'Files'.padStart(7)}
  ${'─'.repeat(68)}`);

    const allCfgDomains = [...new Set([...cfgDomainGen.keys(), ...cfgDomainHand.keys()])].sort();
    const maxCfgDomainLoc = Math.max(1, ...allCfgDomains.map(d => {
      const g = cfgDomainGen.get(d) || { loc: 0 };
      const h = cfgDomainHand.get(d) || { loc: 0 };
      return g.loc + h.loc;
    }));
    for (const d of allCfgDomains) {
      const g = cfgDomainGen.get(d) || { files: 0, loc: 0, code: 0 };
      const h = cfgDomainHand.get(d) || { files: 0, loc: 0, code: 0 };
      const total = g.loc + h.loc;
      const files = g.files + h.files;
      const pct = total > 0 ? (g.loc / total * 100).toFixed(1) : '0.0';
      console.log(`  ${d.padEnd(20)} ${formatNumber(total).padStart(10)} ${formatNumber(g.loc).padStart(10)} ${formatNumber(h.loc).padStart(10)} ${pct.padStart(6)}% ${formatNumber(files).padStart(7)} ${bar(total, maxCfgDomainLoc, 10)}`);
    }

    // Config type breakdown (XML vs YAML)
    const cfgXmlFiles = fileSizes.filter(f => f.ext === '.xml' && !isTestFile(f.path)).length;
    const cfgYamlFiles = fileSizes.filter(f => (f.ext === '.yaml' || f.ext === '.yml') && !isTestFile(f.path)).length;
    const cfgXmlLoc = fileSizes.filter(f => f.ext === '.xml' && !isTestFile(f.path)).reduce((s, f) => s + f.loc, 0);
    const cfgYamlLoc = fileSizes.filter(f => (f.ext === '.yaml' || f.ext === '.yml') && !isTestFile(f.path)).reduce((s, f) => s + f.loc, 0);
    console.log(`
  ── Config by Type ─────────────────────────────────────────────────
  ${'Type'.padEnd(20)} ${'Files'.padStart(7)} ${'LOC'.padStart(10)}
  ${'─'.repeat(40)}
  XML                : ${formatNumber(cfgXmlFiles).padStart(7)} ${formatNumber(cfgXmlLoc).padStart(10)}
  YAML               : ${formatNumber(cfgYamlFiles).padStart(7)} ${formatNumber(cfgYamlLoc).padStart(10)}`);

    // Largest config files
    const cfgSizes = fileSizes.filter(f => CONFIG_EXTS.has(f.ext) && !isTestFile(f.path)).sort((a, b) => b.code - a.code).slice(0, 15);
    if (cfgSizes.length > 0) {
      console.log(`\n  ── Largest Config Files (top 15) ───────────────────────────`);
      for (const f of cfgSizes) {
        const mark = f.autoGen ? ' [auto]' : '';
        console.log(`  ${formatNumber(f.code).padStart(7)}${mark}  ${f.path}`);
      }
    }
  }

  // ── Documentation ──
  printSection('Documentation');
  console.log(`
  ${'Category'.padEnd(18)} ${'Files'.padStart(6)} ${'LOC'.padStart(8)} ${'Size (est.)'.padStart(12)}
  ${'─'.repeat(48)}
${[...docsCategories.entries()]
  .sort((a, b) => b[1].loc - a[1].loc)
  .map(([cat, d]) => {
    const kb = Math.round((d.loc * 45) / 1024);
    const sizeStr = kb >= 1024 ? `${(kb / 1024).toFixed(1)} MB` : `${formatNumber(kb)} KB`;
    return `  ${cat.padEnd(18)} ${formatNumber(d.files).padStart(6)} ${formatNumber(d.loc).padStart(8)} ${sizeStr.padStart(12)}`;
  })
  .join('\n')}
  ${'─'.repeat(48)}
  ${'TOTAL'.padEnd(18)} ${formatNumber(docsTotalFiles).padStart(6)} ${formatNumber(docsTotalLoc).padStart(8)} ${formatNumber(Math.round((docsTotalLoc * 45) / 1024)).padStart(10)} KB
  Docs/Source (LOC)  : ${srcLoc > 0 ? (docsTotalLoc / srcLoc).toFixed(2) : 'N/A'}`);

  // ── By Language ──
  printSection('By Language');
  const langRows = [...langData.entries()]
    .sort((a, b) => b[1].code - a[1].code)
    .map(([lang, d]) => {
      const lg = langGenMap.get(lang) || { genFiles: 0, genLoc: 0, genCode: 0, handFiles: 0, handLoc: 0, handCode: 0 };
      return { lang, ...d, ...lg };
    });
  const maxLangCode = Math.max(1, ...langRows.map((r) => r.code));

  console.log(`
  ${'Language'.padEnd(16)} ${'Files'.padStart(6)} ${'Code'.padStart(9)} ${'Auto-gen'.padStart(9)} ${'Hand-wr'.padStart(9)} ${'Auto%'.padStart(6)}  Distribution`);
  console.log('  ' + '-'.repeat(85));
  for (const r of langRows) {
    const totalCode = r.genCode + r.handCode;
    const pct = totalCode > 0 ? (r.genCode / totalCode * 100).toFixed(1) : '0.0';
    console.log(
      `  ${r.lang.padEnd(16)} ${formatNumber(r.files).padStart(6)} ${formatNumber(r.code).padStart(9)} ${formatNumber(r.genCode).padStart(9)} ${formatNumber(r.handCode).padStart(9)} ${pct.padStart(5)}%  ${bar(r.code, maxLangCode, 20)}`,
    );
  }

  // ── By Package ──
  printSection('By Package (sorted by code lines)');
  const pkgRows = [...packageData.entries()].sort((a, b) => b[1].code - a[1].code);
  const maxPkgCode = Math.max(1, ...pkgRows.map(([, d]) => d.code));

  console.log(`
  ${'Package'.padEnd(42)} ${'Files'.padStart(5)} ${'Code'.padStart(8)} ${'Cmt'.padStart(6)} ${'Test'.padStart(5)} ${'Src'.padStart(5)} ${'Oth'.padStart(5)}  Distribution`);
  console.log('  ' + '-'.repeat(100));
  for (const [pkg, d] of pkgRows) {
    console.log(
      `  ${pkg.padEnd(42)} ${formatNumber(d.files).padStart(5)} ${formatNumber(d.code).padStart(8)} ${formatNumber(d.comment).padStart(6)} ${formatNumber(d.testFiles).padStart(5)} ${formatNumber(d.srcFiles).padStart(5)} ${formatNumber(d.otherFiles).padStart(5)}  ${bar(d.code, maxPkgCode, 15)}`,
    );
  }

  // ── Complexity (TS/JS) ──
  if (complexityAcc.codeLines > 0) {
    printSection('Complexity (TS/JS files only)');
    const avgFuncLen =
      complexityAcc.functionCount > 0
        ? (complexityAcc.codeLines / complexityAcc.functionCount).toFixed(1)
        : 'N/A';
    const branchDensity =
      complexityAcc.codeLines > 0
        ? ((complexityAcc.branches / complexityAcc.codeLines) * 1000).toFixed(1)
        : '0';

    console.log(`
  Functions/methods   : ${formatNumber(complexityAcc.functionCount)}
  Total code lines    : ${formatNumber(complexityAcc.codeLines)}
  Avg function length : ${avgFuncLen} lines
  Branch statements   : ${formatNumber(complexityAcc.branches)}
  Branch density      : ${branchDensity} per 1000 LOC
  Import statements   : ${formatNumber(complexityAcc.imports)}
  Export statements   : ${formatNumber(complexityAcc.exports)}
  Import/Export ratio : ${complexityAcc.exports > 0 ? (complexityAcc.imports / complexityAcc.exports).toFixed(2) : 'N/A'}`);
  }

  // ── Largest Files ──
  printSection('Largest Files (by code lines, top 20)');
  const topFiles = fileSizes
    .filter((f) => !isTestFile(f.path))
    .sort((a, b) => b.code - a.code)
    .slice(0, 20);

  console.log(`\n  ${'File'.padEnd(65)} ${'LOC'.padStart(6)} ${'Code'.padStart(6)}`);
  console.log('  ' + '-'.repeat(80));
  for (const f of topFiles) {
    console.log(
      `  ${f.path.padEnd(65)} ${formatNumber(f.loc).padStart(6)} ${formatNumber(f.code).padStart(6)}`,
    );
  }

  console.log('\n');
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
