-- app-erp-inventory indexes generated from model/app-erp-inventory.orm.xml
-- Dialect: postgresql.
-- This file is maintained separately from _create_erp-inventory.sql because the
-- platform _create.sql.xgen template (ddl.xlib CreateTables) does not emit CREATE INDEX.
-- Runtime: ddl.xlib AddIndex also applies these at app startup from the ORM model.
-- Run AFTER _create_erp-inventory.sql during manual production deployment.
-- Source of truth: model <indexes> definitions (91 indexes).
-- Regenerate: node scripts/add-orm-indexes.js
CREATE INDEX IDX_INV_STOCK_MOVE_ORG_DOC_STATUS ON erp_inv_stock_move (org_id, doc_status);
CREATE INDEX IDX_INV_STOCK_MOVE_ORG_BUSINESS_DATE ON erp_inv_stock_move (org_id, business_date);
CREATE INDEX IDX_INV_STOCK_MOVE_SOURCE_WAREHOUSE_ID ON erp_inv_stock_move (source_warehouse_id);
CREATE INDEX IDX_INV_STOCK_MOVE_SOURCE_LOCATION_ID ON erp_inv_stock_move (source_location_id);
CREATE INDEX IDX_INV_STOCK_MOVE_DEST_WAREHOUSE_ID ON erp_inv_stock_move (dest_warehouse_id);
CREATE INDEX IDX_INV_STOCK_MOVE_DEST_LOCATION_ID ON erp_inv_stock_move (dest_location_id);
CREATE INDEX IDX_INV_STOCK_MOVE_ORIGIN_MOVE_ID ON erp_inv_stock_move (origin_move_id);
CREATE INDEX IDX_INV_STOCK_MOVE_ORIGIN_RETURNED_MOVE_ID ON erp_inv_stock_move (origin_returned_move_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_MOVE_ID ON erp_inv_stock_move_line (move_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_MATERIAL_ID ON erp_inv_stock_move_line (material_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_SKU_ID ON erp_inv_stock_move_line (sku_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_UO_M_ID ON erp_inv_stock_move_line (uo_m_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_CURRENCY_ID ON erp_inv_stock_move_line (currency_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_SOURCE_LOCATION_ID ON erp_inv_stock_move_line (source_location_id);
CREATE INDEX IDX_INV_STOCK_MOVE_LINE_DEST_LOCATION_ID ON erp_inv_stock_move_line (dest_location_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_ORG_BUSINESS_DATE ON erp_inv_stock_ledger (org_id, business_date);
CREATE INDEX IDX_INV_STOCK_LEDGER_MOVE_ID ON erp_inv_stock_ledger (move_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_MOVE_LINE_ID ON erp_inv_stock_ledger (move_line_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_MATERIAL_ID ON erp_inv_stock_ledger (material_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_SKU_ID ON erp_inv_stock_ledger (sku_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_WAREHOUSE_ID ON erp_inv_stock_ledger (warehouse_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_LOCATION_ID ON erp_inv_stock_ledger (location_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_ACCT_SCHEMA_ID ON erp_inv_stock_ledger (acct_schema_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_CURRENCY_ID ON erp_inv_stock_ledger (currency_id);
CREATE INDEX IDX_INV_STOCK_LEDGER_OWNER_ID ON erp_inv_stock_ledger (owner_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_MATERIAL_ID ON erp_inv_stock_balance (material_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_SKU_ID ON erp_inv_stock_balance (sku_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_WAREHOUSE_ID ON erp_inv_stock_balance (warehouse_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_LOCATION_ID ON erp_inv_stock_balance (location_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_CURRENCY_ID ON erp_inv_stock_balance (currency_id);
CREATE INDEX IDX_INV_STOCK_BALANCE_OWNER_ID ON erp_inv_stock_balance (owner_id);
CREATE INDEX IDX_INV_RESERVATION_ORG_STATUS ON erp_inv_reservation (org_id, status);
CREATE INDEX IDX_INV_RESERVATION_ORG_BUSINESS_DATE ON erp_inv_reservation (org_id, business_date);
CREATE INDEX IDX_INV_RESERVATION_RESERVED_FOR_PARTNER_ID ON erp_inv_reservation (reserved_for_partner_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_RESERVATION_ID ON erp_inv_reservation_line (reservation_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_MATERIAL_ID ON erp_inv_reservation_line (material_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_SKU_ID ON erp_inv_reservation_line (sku_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_WAREHOUSE_ID ON erp_inv_reservation_line (warehouse_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_LOCATION_ID ON erp_inv_reservation_line (location_id);
CREATE INDEX IDX_INV_RESERVATION_LINE_UOM_ID ON erp_inv_reservation_line (uom_id);
CREATE INDEX IDX_INV_COST_LAYER_MATERIAL_ID ON erp_inv_cost_layer (material_id);
CREATE INDEX IDX_INV_COST_LAYER_SKU_ID ON erp_inv_cost_layer (sku_id);
CREATE INDEX IDX_INV_COST_LAYER_WAREHOUSE_ID ON erp_inv_cost_layer (warehouse_id);
CREATE INDEX IDX_INV_COST_LAYER_CURRENCY_ID ON erp_inv_cost_layer (currency_id);
CREATE INDEX IDX_INV_COST_LAYER_INCOMING_MOVE_ID ON erp_inv_cost_layer (incoming_move_id);
CREATE INDEX IDX_INV_COST_LAYER_ACCT_SCHEMA_ID ON erp_inv_cost_layer (acct_schema_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_ORG_DOC_STATUS ON erp_inv_transfer_order (org_id, doc_status);
CREATE INDEX IDX_INV_TRANSFER_ORDER_ORG_BUSINESS_DATE ON erp_inv_transfer_order (org_id, business_date);
CREATE INDEX IDX_INV_TRANSFER_ORDER_FROM_WAREHOUSE_ID ON erp_inv_transfer_order (from_warehouse_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_TO_WAREHOUSE_ID ON erp_inv_transfer_order (to_warehouse_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_IN_TRANSIT_WAREHOUSE_ID ON erp_inv_transfer_order (in_transit_warehouse_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_LINE_TRANSFER_ID ON erp_inv_transfer_order_line (transfer_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_LINE_MATERIAL_ID ON erp_inv_transfer_order_line (material_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_LINE_SKU_ID ON erp_inv_transfer_order_line (sku_id);
CREATE INDEX IDX_INV_TRANSFER_ORDER_LINE_UO_M_ID ON erp_inv_transfer_order_line (uo_m_id);
CREATE INDEX IDX_INV_STOCK_TAKE_ORG_DOC_STATUS ON erp_inv_stock_take (org_id, doc_status);
CREATE INDEX IDX_INV_STOCK_TAKE_ORG_BUSINESS_DATE ON erp_inv_stock_take (org_id, business_date);
CREATE INDEX IDX_INV_STOCK_TAKE_WAREHOUSE_ID ON erp_inv_stock_take (warehouse_id);
CREATE INDEX IDX_INV_STOCK_TAKE_LINE_TAKE_ID ON erp_inv_stock_take_line (take_id);
CREATE INDEX IDX_INV_STOCK_TAKE_LINE_MATERIAL_ID ON erp_inv_stock_take_line (material_id);
CREATE INDEX IDX_INV_STOCK_TAKE_LINE_SKU_ID ON erp_inv_stock_take_line (sku_id);
CREATE INDEX IDX_INV_STOCK_TAKE_LINE_UO_M_ID ON erp_inv_stock_take_line (uo_m_id);
CREATE INDEX IDX_INV_STOCK_TAKE_LINE_LOCATION_ID ON erp_inv_stock_take_line (location_id);
CREATE INDEX IDX_INV_PICKING_ORDER_ORG_DOC_STATUS ON erp_inv_picking_order (org_id, doc_status);
CREATE INDEX IDX_INV_PICKING_ORDER_ORG_BUSINESS_DATE ON erp_inv_picking_order (org_id, business_date);
CREATE INDEX IDX_INV_PICKING_ORDER_WAREHOUSE_ID ON erp_inv_picking_order (warehouse_id);
CREATE INDEX IDX_INV_PICKING_ORDER_PICKER_ID ON erp_inv_picking_order (picker_id);
CREATE INDEX IDX_INV_PICKING_ORDER_LINE_PICKING_ID ON erp_inv_picking_order_line (picking_id);
CREATE INDEX IDX_INV_PICKING_ORDER_LINE_MATERIAL_ID ON erp_inv_picking_order_line (material_id);
CREATE INDEX IDX_INV_PICKING_ORDER_LINE_SKU_ID ON erp_inv_picking_order_line (sku_id);
CREATE INDEX IDX_INV_PICKING_ORDER_LINE_UO_M_ID ON erp_inv_picking_order_line (uo_m_id);
CREATE INDEX IDX_INV_PICKING_ORDER_LINE_SOURCE_LOCATION_ID ON erp_inv_picking_order_line (source_location_id);
CREATE INDEX IDX_INV_BATCH_ORG_STATUS ON erp_inv_batch (org_id, status);
CREATE INDEX IDX_INV_BATCH_MATERIAL_ID ON erp_inv_batch (material_id);
CREATE INDEX IDX_INV_BATCH_SKU_ID ON erp_inv_batch (sku_id);
CREATE INDEX IDX_INV_BATCH_WAREHOUSE_ID ON erp_inv_batch (warehouse_id);
CREATE INDEX IDX_INV_SERIAL_NUMBER_ORG_STATUS ON erp_inv_serial_number (org_id, status);
CREATE INDEX IDX_INV_SERIAL_NUMBER_MATERIAL_ID ON erp_inv_serial_number (material_id);
CREATE INDEX IDX_INV_SERIAL_NUMBER_SKU_ID ON erp_inv_serial_number (sku_id);
CREATE INDEX IDX_INV_SERIAL_NUMBER_WAREHOUSE_ID ON erp_inv_serial_number (warehouse_id);
CREATE INDEX IDX_INV_SERIAL_NUMBER_LOCATION_ID ON erp_inv_serial_number (location_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_ORG_DOC_STATUS ON erp_inv_ownership_transfer (org_id, doc_status);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_ORG_BUSINESS_DATE ON erp_inv_ownership_transfer (org_id, business_date);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_PARTNER_ID ON erp_inv_ownership_transfer (partner_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_WAREHOUSE_ID ON erp_inv_ownership_transfer (warehouse_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_SOURCE_LOC_ID ON erp_inv_ownership_transfer (source_loc_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_DEST_LOC_ID ON erp_inv_ownership_transfer (dest_loc_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_CURRENCY_ID ON erp_inv_ownership_transfer (currency_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_LINE_TRANSFER_ID ON erp_inv_ownership_transfer_line (transfer_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_LINE_MATERIAL_ID ON erp_inv_ownership_transfer_line (material_id);
CREATE INDEX IDX_INV_OWNERSHIP_TRANSFER_LINE_SKU_ID ON erp_inv_ownership_transfer_line (sku_id);
