
CREATE TABLE erp_md_md_organization(
  ID BIGINT NOT NULL    COMMENT 'null',
  constraint PK_erp_md_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_drp_plan(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编号',
  PLAN_NAME VARCHAR(200) NOT NULL    COMMENT '计划名称',
  PERIOD_FROM DATE NOT NULL    COMMENT '期间开始',
  PERIOD_TO DATE NOT NULL    COMMENT '期间结束',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  TOTAL_REPLENISHMENT_QTY DECIMAL(20,4) NULL    COMMENT '总补货数量',
  RUN_AT DATETIME NULL    COMMENT '运行时间',
  RUN_BY VARCHAR(50) NULL    COMMENT '运行人',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_drp_plan primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_drp_parameter(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SAFETY_STOCK DECIMAL(20,4) NULL    COMMENT '安全库存',
  REPLENISHMENT_LEAD_TIME INTEGER NULL    COMMENT '补货提前期(天)',
  ORDER_MULTIPLE DECIMAL(20,4) NULL    COMMENT '订货倍数',
  PREFERRED_SOURCE_WAREHOUSE_ID BIGINT NULL    COMMENT '首选调出仓库',
  PREFERRED_SUPPLIER_ID BIGINT NULL    COMMENT '首选供应商',
  REPLENISHMENT_METHOD INTEGER NOT NULL    COMMENT '补货方法',
  MIN_STOCK_LEVEL DECIMAL(20,4) NULL    COMMENT '最低库存',
  MAX_STOCK_LEVEL DECIMAL(20,4) NULL    COMMENT '最高库存',
  REVIEW_PERIOD_DAYS INTEGER NULL    COMMENT '审视周期(天)',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_drp_parameter primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_drp_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PLAN_ID BIGINT NOT NULL    COMMENT '计划ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '目标仓库',
  SOURCE_WAREHOUSE_ID BIGINT NULL    COMMENT '来源仓库',
  REPLENISHMENT_TYPE INTEGER NOT NULL    COMMENT '补货类型',
  CURRENT_STOCK DECIMAL(20,4) NULL    COMMENT '当前库存',
  ALLOCATED_QTY DECIMAL(20,4) NULL    COMMENT '已分配量',
  ON_ORDER_QTY DECIMAL(20,4) NULL    COMMENT '在单量',
  FORECAST_DEMAND DECIMAL(20,4) NULL    COMMENT '预测需求量',
  SAFETY_STOCK DECIMAL(20,4) NULL    COMMENT '安全库存',
  NET_REQUIREMENT DECIMAL(20,4) NULL    COMMENT '净需求',
  SUGGESTED_QTY DECIMAL(20,4) NULL    COMMENT '建议补货量',
  APPROVED_QTY DECIMAL(20,4) NULL    COMMENT '批准补货量',
  ORDER_BILL_TYPE VARCHAR(50) NULL    COMMENT '生成单据类型',
  ORDER_BILL_CODE VARCHAR(50) NULL    COMMENT '生成单据号',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_drp_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_md_organization COMMENT 'ErpMdOrganization';
                
   ALTER TABLE erp_drp_plan COMMENT 'DRP计划';
                
   ALTER TABLE erp_drp_parameter COMMENT '仓库补货参数';
                
   ALTER TABLE erp_drp_line COMMENT 'DRP明细';
                
