
CREATE TABLE erp_md_material_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARENT_ID BIGINT NULL    COMMENT '父级ID',
  SORT_NUM INTEGER NULL    COMMENT '排序',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_material_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(20) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  UOM_GROUP VARCHAR(50) NULL    COMMENT '单位组',
  IS_BASE BOOLEAN default 0  NULL    COMMENT '是否基本单位',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_uom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_tax_rate(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '税率编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '税率名称',
  TAX_TYPE INTEGER NOT NULL    COMMENT '税种',
  RATE DECIMAL(10,6) NOT NULL    COMMENT '税率(%)',
  IS_ZERO_RATED BOOLEAN default 0  NULL    COMMENT '是否零税率',
  IS_EXEMPT BOOLEAN default 0  NULL    COMMENT '是否免税',
  VALID_FROM DATE NULL    COMMENT '生效日期',
  VALID_TO DATE NULL    COMMENT '失效日期',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_tax_rate primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARTNER_TYPE INTEGER NOT NULL    COMMENT '类型',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  CONTACT_PERSON VARCHAR(100) NULL    COMMENT '联系人',
  PHONE VARCHAR(50) NULL    COMMENT '电话',
  EMAIL VARCHAR(200) NULL    COMMENT '邮箱',
  ADDRESS VARCHAR(500) NULL    COMMENT '地址',
  TAX_NO VARCHAR(50) NULL    COMMENT '税号',
  CREDIT_LIMIT DECIMAL(20,4) NULL    COMMENT '信用额度',
  CREDIT_PERIOD_DAYS INTEGER NULL    COMMENT '信用期(天)',
  RECEIVABLE_BALANCE DECIMAL(20,4) default 0  NULL    COMMENT '应收余额',
  PAYABLE_BALANCE DECIMAL(20,4) default 0  NULL    COMMENT '应付余额',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(10) NOT NULL    COMMENT '币种代码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SYMBOL VARCHAR(10) NULL    COMMENT '符号',
  DECIMAL_PLACES INTEGER default 2  NULL    COMMENT '小数位数',
  IS_FUNCTIONAL BOOLEAN default 0  NULL    COMMENT '是否本位币',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_settlement_method(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SETTLEMENT_TYPE INTEGER NOT NULL    COMMENT '结算类型',
  DEFAULT_FUND_ACCOUNT_ID BIGINT NULL    COMMENT '默认资金账户',
  DEFAULT_DAYS INTEGER NULL    COMMENT '默认账期(天)',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_settlement_method primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner_address(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_ID BIGINT NOT NULL    COMMENT '往来单位',
  ADDRESS_TYPE INTEGER NOT NULL    COMMENT '地址类型',
  CONTACT_PERSON VARCHAR(100) NULL    COMMENT '联系人',
  PHONE VARCHAR(50) NULL    COMMENT '电话',
  ADDRESS VARCHAR(500) NOT NULL    COMMENT '详细地址',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_partner_address primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner_contact(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_ID BIGINT NOT NULL    COMMENT '往来单位',
  CONTACT_PERSON VARCHAR(100) NOT NULL    COMMENT '联系人姓名',
  POSITION VARCHAR(100) NULL    COMMENT '职务',
  PHONE VARCHAR(50) NULL    COMMENT '电话',
  EMAIL VARCHAR(200) NULL    COMMENT '邮箱',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认联系人',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_md_partner_contact primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_bank_account(
  ID BIGINT NOT NULL    COMMENT 'ID',
  PARTNER_ID BIGINT NOT NULL    COMMENT '往来单位',
  BANK_NAME VARCHAR(200) NOT NULL    COMMENT '开户银行',
  BANK_BRANCH VARCHAR(200) NULL    COMMENT '支行',
  BANK_ACCOUNT VARCHAR(50) NOT NULL    COMMENT '银行账号',
  ACCOUNT_TYPE INTEGER NULL    COMMENT '账户类型',
  ACCOUNT_HOLDER VARCHAR(200) NULL    COMMENT '户名',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_bank_account primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_exchange_rate(
  ID BIGINT NOT NULL    COMMENT 'ID',
  FROM_CURRENCY_ID BIGINT NOT NULL    COMMENT '源币种',
  TO_CURRENCY_ID BIGINT NOT NULL    COMMENT '目标币种',
  RATE_TYPE VARCHAR(30) default 'SPOT'  NULL    COMMENT '汇率类型',
  RATE DECIMAL(20,8) NOT NULL    COMMENT '汇率',
  VALID_FROM DATE NOT NULL    COMMENT '生效日期',
  VALID_TO DATE NULL    COMMENT '失效日期',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_exchange_rate primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_subject(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '科目编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '科目名称',
  PARENT_ID BIGINT NULL    COMMENT '父级科目',
  SUBJECT_CLASS INTEGER NOT NULL    COMMENT '科目类别',
  DIRECTION INTEGER NOT NULL    COMMENT '余额方向',
  BALANCE_TYPE INTEGER NULL    COMMENT '余额类型',
  CURRENCY_ID BIGINT NULL    COMMENT '核算币种',
  IS_AUXILIARY_PARTNER BOOLEAN default 0  NULL    COMMENT '辅助-往来单位',
  IS_AUXILIARY_DEPARTMENT BOOLEAN default 0  NULL    COMMENT '辅助-部门',
  IS_AUXILIARY_PROJECT BOOLEAN default 0  NULL    COMMENT '辅助-项目',
  IS_AUXILIARY_WAREHOUSE BOOLEAN default 0  NULL    COMMENT '辅助-仓库',
  IS_AUXILIARY_PRODUCT BOOLEAN default 0  NULL    COMMENT '辅助-物料',
  IS_LEAF BOOLEAN default 1  NULL    COMMENT '是否明细科目',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_md_subject primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARENT_ID BIGINT NULL    COMMENT '父级组织',
  ORG_TYPE INTEGER NOT NULL    COMMENT '组织类型',
  FUNCTIONAL_CURRENCY_ID BIGINT NULL    COMMENT '本位币',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_employee(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '工号',
  NAME VARCHAR(200) NOT NULL    COMMENT '姓名',
  ORG_ID BIGINT NULL    COMMENT '所属组织/部门',
  POSITION VARCHAR(100) NULL    COMMENT '职务',
  PHONE VARCHAR(50) NULL    COMMENT '电话',
  EMAIL VARCHAR(200) NULL    COMMENT '邮箱',
  PARTNER_ID BIGINT NULL    COMMENT '对应内部往来单位',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_employee primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_acct_schema(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '账套编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '账套名称',
  ORG_ID BIGINT NOT NULL    COMMENT '核算组织',
  NATURE INTEGER NOT NULL    COMMENT '账套性质',
  FUNCTIONAL_CURRENCY_ID BIGINT NOT NULL    COMMENT '本位币',
  COSTING_METHOD INTEGER NULL    COMMENT '默认成本方法',
  IS_ADJUST_CURRENCY BOOLEAN default 1  NULL    COMMENT '是否调整汇率差异',
  IS_PROPAGATE BOOLEAN default 0  NULL    COMMENT '是否自动复制分录到其它账套',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_acct_schema primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_warehouse(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT '仓库类型',
  ORG_ID BIGINT NULL    COMMENT '所属组织',
  ADDRESS VARCHAR(500) NULL    COMMENT '地址',
  MANAGER_ID BIGINT NULL    COMMENT '负责人(职员)',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_acct_schema_coa(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ACCT_SCHEMA_ID BIGINT NOT NULL    COMMENT '账套',
  NAME VARCHAR(200) NOT NULL    COMMENT '科目表名称',
  IS_PRIMARY BOOLEAN default 0  NULL    COMMENT '是否主科目表',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_acct_schema_coa primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '物料编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '物料名称',
  MATERIAL_TYPE INTEGER NOT NULL    COMMENT '物料类型',
  CATEGORY_ID BIGINT NULL    COMMENT '分类ID',
  UOM_ID BIGINT NOT NULL    COMMENT '主计量单位',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  COST_METHOD INTEGER NULL    COMMENT '存货计价方法',
  IS_BATCH_MANAGED BOOLEAN default 0  NULL    COMMENT '是否批次管理',
  IS_SERIAL_MANAGED BOOLEAN default 0  NULL    COMMENT '是否序列号管理',
  DEFAULT_WAREHOUSE_ID BIGINT NULL    COMMENT '默认仓库',
  MIN_STOCK DECIMAL(20,4) NULL    COMMENT '最低库存',
  MAX_STOCK DECIMAL(20,4) NULL    COMMENT '最高库存',
  SAFETY_STOCK DECIMAL(20,4) NULL    COMMENT '安全库存',
  LEAD_TIME_DAYS INTEGER NULL    COMMENT '采购提前期(天)',
  WEIGHT DECIMAL(12,4) NULL    COMMENT '重量(kg)',
  VOLUME DECIMAL(12,6) NULL    COMMENT '体积(m3)',
  DEFAULT_TAX_RATE_ID BIGINT NULL    COMMENT '默认税率',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_location(
  ID BIGINT NOT NULL    COMMENT 'ID',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '仓库ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  PARENT_ID BIGINT NULL    COMMENT '父级库位',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_location primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_sku(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料ID',
  SKU_CODE VARCHAR(50) NOT NULL    COMMENT 'SKU编码',
  BARCODE VARCHAR(50) NULL    COMMENT '条码',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  CONVERSION_RATE DECIMAL(12,4) default 1  NULL    COMMENT '换算系数',
  PURCHASE_PRICE DECIMAL(20,4) NULL    COMMENT '采购价(不含税)',
  SALE_PRICE DECIMAL(20,4) NULL    COMMENT '销售价(不含税)',
  WHOLESALE_PRICE DECIMAL(20,4) NULL    COMMENT '批发价(不含税)',
  RETAIL_PRICE DECIMAL(20,4) NULL    COMMENT '零售价(不含税)',
  TAX_RATE_ID BIGINT NULL    COMMENT '默认税率',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认SKU',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_material_sku primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom_conversion(
  ID BIGINT NOT NULL    COMMENT 'ID',
  MATERIAL_ID BIGINT NULL    COMMENT '物料(空表示通用)',
  FROM_UOM_ID BIGINT NOT NULL    COMMENT '源单位',
  TO_UOM_ID BIGINT NOT NULL    COMMENT '目标单位',
  CONVERSION_RATE DECIMAL(20,8) NOT NULL    COMMENT '换算系数',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_md_uom_conversion primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_material_category COMMENT '物料分类';
                
   ALTER TABLE erp_md_uom COMMENT '计量单位';
                
   ALTER TABLE erp_md_tax_rate COMMENT '税率';
                
   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_settlement_method COMMENT '结算方式';
                
   ALTER TABLE erp_md_partner_address COMMENT '往来单位地址';
                
   ALTER TABLE erp_md_partner_contact COMMENT '往来单位联系人';
                
   ALTER TABLE erp_md_bank_account COMMENT '银行账户';
                
   ALTER TABLE erp_md_exchange_rate COMMENT '汇率';
                
   ALTER TABLE erp_md_subject COMMENT '会计科目';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_employee COMMENT '职员';
                
   ALTER TABLE erp_md_acct_schema COMMENT '会计核算表(账套)';
                
   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_md_acct_schema_coa COMMENT '账套科目表';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_location COMMENT '库位';
                
   ALTER TABLE erp_md_material_sku COMMENT '物料SKU';
                
   ALTER TABLE erp_md_uom_conversion COMMENT '单位换算';
                
