
CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SYMBOL VARCHAR(50) NULL    COMMENT 'null',
  DECIMAL_PLACES INTEGER NULL    COMMENT 'null',
  IS_FUNCTIONAL BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  MATERIAL_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_uom(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  UOM_GROUP VARCHAR(50) NULL    COMMENT 'null',
  IS_BASE BOOLEAN NULL    COMMENT 'null',
  constraint PK_erp_md_uom primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_warehouse(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  WAREHOUSE_TYPE INTEGER NULL    COMMENT 'null',
  ORG_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_warehouse primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_settlement_method(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  SETTLEMENT_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_settlement_method primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material_sku(
  ID BIGINT NULL    COMMENT 'null',
  MATERIAL_ID BIGINT NULL    COMMENT 'null',
  SKU_CODE VARCHAR(50) NULL    COMMENT 'null',
  BARCODE VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_material_sku primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_tax_rate(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  TAX_TYPE INTEGER NULL    COMMENT 'null',
  RATE VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_tax_rate primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_prj_project(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_prj_project primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_bank_account(
  ID BIGINT NULL    COMMENT 'null',
  PARTNER_ID BIGINT NULL    COMMENT 'null',
  BANK_NAME VARCHAR(50) NULL    COMMENT 'null',
  BANK_ACCOUNT VARCHAR(50) NULL    COMMENT 'null',
  ACCOUNT_TYPE INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_bank_account primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_quotation(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  BUSINESS_DATE DATE NOT NULL    COMMENT '报价日期',
  VALID_FROM DATE NULL    COMMENT '生效日期',
  VALID_TO DATE NULL    COMMENT '失效日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(含税)',
  IS_ACCEPTED BOOLEAN default 0  NULL    COMMENT '是否已转订单',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  constraint PK_erp_sal_quotation primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_contract(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '合同号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  CONTRACT_NAME VARCHAR(200) NOT NULL    COMMENT '合同名称',
  BUSINESS_DATE DATE NOT NULL    COMMENT '签订日期',
  VALID_FROM DATE NULL    COMMENT '生效日期',
  VALID_TO DATE NULL    COMMENT '失效日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合同金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合同金额(含税)',
  SIGNED_BY BIGINT NULL    COMMENT '签约人(职员)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  constraint PK_erp_sal_contract primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_invoice(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  INVOICE_NO VARCHAR(50) NULL    COMMENT '发票号码',
  INVOICE_TYPE VARCHAR(20) NULL    COMMENT '发票类型',
  BUSINESS_DATE DATE NOT NULL    COMMENT '发票日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(源币)',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(本位币)',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(含税)',
  RECEIVED_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '已收金额',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  RECEIVED_STATUS VARCHAR(20) NULL    COMMENT '收款进度',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_invoice primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_receipt(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  BUSINESS_DATE DATE NOT NULL    COMMENT '收款日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) NOT NULL    COMMENT '合计金额(源币)',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) NOT NULL    COMMENT '合计金额(本位币)',
  TOTAL_AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '合计金额',
  SETTLEMENT_METHOD_ID BIGINT NULL    COMMENT '结算方式',
  RECEIPT_METHOD VARCHAR(50) NULL    COMMENT '收款方式',
  BANK_ACCOUNT_ID BIGINT NULL    COMMENT '收款账户(资金账户)',
  PARTNER_BANK_ACCOUNT_ID BIGINT NULL    COMMENT '客户付款账户(银行账户主数据)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  WRITTEN_OFF_STATUS VARCHAR(20) NULL    COMMENT '核销状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_receipt primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_quotation_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  QUOTATION_ID BIGINT NOT NULL    COMMENT '报价单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NOT NULL    COMMENT '报价单价(不含税)',
  TAX_RATE DECIMAL(10,4) NULL    COMMENT '税率(%)',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '税额',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额(不含税)',
  AMOUNT_WITH_TAX DECIMAL(20,4) NULL    COMMENT '金额(含税)',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_quotation_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_order(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  QUOTATION_ID BIGINT NULL    COMMENT '报价单',
  CONTRACT_ID BIGINT NULL    COMMENT '销售合同',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  WAREHOUSE_ID BIGINT NULL    COMMENT '发货仓库',
  BUSINESS_DATE DATE NOT NULL    COMMENT '订单日期',
  DELIVERY_DATE DATE NULL    COMMENT '交货日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(源币不含税)',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(本位币不含税)',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(含税)',
  DISCOUNT_RATE DECIMAL(10,4) NULL    COMMENT '整单折扣率(%)',
  DISCOUNT_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '折扣金额',
  RECEIVED_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '已收金额',
  SETTLEMENT_METHOD_ID BIGINT NULL    COMMENT '结算方式',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  RECEIVED_STATUS VARCHAR(20) NULL    COMMENT '收款进度',
  DELIVERY_STATUS VARCHAR(20) NULL    COMMENT '发货进度',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_order primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_receipt_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  RECEIPT_ID BIGINT NOT NULL    COMMENT '收款单ID',
  INVOICE_ID BIGINT NOT NULL    COMMENT '发票ID',
  AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '核销金额',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_receipt_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_order_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORDER_ID BIGINT NOT NULL    COMMENT '订单ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NOT NULL    COMMENT '单价(不含税)',
  TAX_RATE DECIMAL(10,4) NULL    COMMENT '税率(%)',
  TAX_RATE_ID BIGINT NULL    COMMENT '税率主数据',
  TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '税额',
  AMOUNT DECIMAL(20,4) NOT NULL    COMMENT '金额(不含税)',
  AMOUNT_WITH_TAX DECIMAL(20,4) NULL    COMMENT '金额(含税)',
  DELIVERED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '已出库数量',
  INVOICED_QUANTITY DECIMAL(20,4) default 0  NULL    COMMENT '已开票数量',
  WAREHOUSE_ID BIGINT NULL    COMMENT '发货仓库',
  PROJECT_ID BIGINT NULL    COMMENT '项目',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_order_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_delivery(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ORDER_ID BIGINT NULL    COMMENT '销售订单',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '出库仓库',
  BUSINESS_DATE DATE NOT NULL    COMMENT '出库日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(源币)',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(本位币)',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(含税)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_delivery primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_delivery_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  DELIVERY_ID BIGINT NOT NULL    COMMENT '出库单ID',
  ORDER_LINE_ID BIGINT NULL    COMMENT '订单行ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '实发数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价(不含税)',
  TAX_RATE DECIMAL(10,4) NULL    COMMENT '税率(%)',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '税额',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额(不含税)',
  WAREHOUSE_ID BIGINT NULL    COMMENT '出库库位',
  BATCH_NO VARCHAR(50) NULL    COMMENT '批号',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_delivery_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_return(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '单号',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  DELIVERY_ID BIGINT NULL    COMMENT '出库单',
  CUSTOMER_ID BIGINT NOT NULL    COMMENT '客户',
  WAREHOUSE_ID BIGINT NOT NULL    COMMENT '入库仓库',
  BUSINESS_DATE DATE NOT NULL    COMMENT '退货日期',
  CURRENCY_ID BIGINT NOT NULL    COMMENT '币种',
  EXCHANGE_RATE DECIMAL(20,8) default 1  NULL    COMMENT '汇率',
  AMOUNT_SOURCE DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(源币)',
  AMOUNT_FUNCTIONAL DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(本位币)',
  TOTAL_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(不含税)',
  TOTAL_TAX_AMOUNT DECIMAL(20,4) default 0  NULL    COMMENT '合计税额',
  TOTAL_AMOUNT_WITH_TAX DECIMAL(20,4) default 0  NULL    COMMENT '合计金额(含税)',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  APPROVE_STATUS VARCHAR(20) NOT NULL    COMMENT '审核状态',
  POSTED BOOLEAN default 0  NULL    COMMENT '已过账',
  POSTED_AT DATETIME NULL    COMMENT '过账时间',
  POSTED_BY VARCHAR(36) NULL    COMMENT '过账人',
  APPROVED_BY VARCHAR(36) NULL    COMMENT '审核人',
  APPROVED_AT DATETIME NULL    COMMENT '审核时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_return primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_invoice_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  INVOICE_ID BIGINT NOT NULL    COMMENT '发票ID',
  DELIVERY_LINE_ID BIGINT NULL    COMMENT '出库行ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价(不含税)',
  TAX_RATE DECIMAL(10,4) NULL    COMMENT '税率(%)',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '税额',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额(不含税)',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_invoice_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sal_return_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  RETURN_ID BIGINT NOT NULL    COMMENT '退货单ID',
  DELIVERY_LINE_ID BIGINT NULL    COMMENT '出库行ID',
  LINE_NO INTEGER NOT NULL    COMMENT '行号',
  MATERIAL_ID BIGINT NOT NULL    COMMENT '物料',
  SKU_ID BIGINT NULL    COMMENT 'SKU',
  UOM_ID BIGINT NOT NULL    COMMENT '计量单位',
  QUANTITY DECIMAL(20,4) NOT NULL    COMMENT '退货数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价(不含税)',
  TAX_RATE DECIMAL(10,4) NULL    COMMENT '税率(%)',
  TAX_AMOUNT DECIMAL(20,4) NULL    COMMENT '税额',
  AMOUNT DECIMAL(20,4) NULL    COMMENT '金额(不含税)',
  REASON VARCHAR(500) NULL    COMMENT '退货原因',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  constraint PK_erp_sal_return_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_md_uom COMMENT '计量单位';
                
   ALTER TABLE erp_md_warehouse COMMENT '仓库';
                
   ALTER TABLE erp_md_settlement_method COMMENT '结算方式';
                
   ALTER TABLE erp_md_material_sku COMMENT '物料SKU';
                
   ALTER TABLE erp_md_tax_rate COMMENT '税率';
                
   ALTER TABLE erp_prj_project COMMENT '项目';
                
   ALTER TABLE erp_md_bank_account COMMENT '银行账户';
                
   ALTER TABLE erp_sal_quotation COMMENT '销售报价单';
                
   ALTER TABLE erp_sal_contract COMMENT '销售合同';
                
   ALTER TABLE erp_sal_invoice COMMENT '销售发票';
                
   ALTER TABLE erp_sal_receipt COMMENT '收款单';
                
   ALTER TABLE erp_sal_quotation_line COMMENT '销售报价单行';
                
   ALTER TABLE erp_sal_order COMMENT '销售订单';
                
   ALTER TABLE erp_sal_receipt_line COMMENT '收款核销行';
                
   ALTER TABLE erp_sal_order_line COMMENT '销售订单行';
                
   ALTER TABLE erp_sal_delivery COMMENT '销售出库单';
                
   ALTER TABLE erp_sal_delivery_line COMMENT '销售出库单行';
                
   ALTER TABLE erp_sal_return COMMENT '销售退货单';
                
   ALTER TABLE erp_sal_invoice_line COMMENT '销售发票行';
                
   ALTER TABLE erp_sal_return_line COMMENT '销售退货单行';
                
