
CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_source(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_source primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_status(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_status primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lost_reason(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lost_reason primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_event_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  COLOR VARCHAR(20) NULL    COMMENT '日历颜色',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_event_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_partner_contact(
  ID BIGINT NULL    COMMENT 'null',
  CONTACT_NAME VARCHAR(100) NULL    COMMENT 'null',
  PHONE VARCHAR(50) NULL    COMMENT 'null',
  EMAIL VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_partner_contact primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_quote_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TEMPLATE_CONTENT VARCHAR(4000) NULL    COMMENT '模板内容',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_quote_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_currency(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_currency primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_material(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  constraint PK_erp_md_material primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_team(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TEAM_LEADER_ID VARCHAR(36) NULL    COMMENT '团队负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_team primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_campaign(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CAMPAIGN_NAME VARCHAR(200) NOT NULL    COMMENT '活动名称',
  MEDIUM VARCHAR(100) NULL    COMMENT 'UTM Medium',
  SOURCE VARCHAR(100) NULL    COMMENT 'UTM Source',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  BUDGET_AMOUNT DECIMAL(20,4) NULL    COMMENT '预算金额',
  ACTUAL_COST DECIMAL(20,4) NULL    COMMENT '实际成本',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_campaign primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_score_config(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONFIG_NAME VARCHAR(200) NOT NULL    COMMENT '规则集名称',
  IS_ACTIVE BOOLEAN default 0  NULL    COMMENT '是否生效',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效开始日期',
  EFFECTIVE_TO DATE NULL    COMMENT '生效结束日期',
  AUTO_QUALIFY_THRESHOLD INTEGER NULL    COMMENT '自动转商机阈值',
  MIN_SCORE_FOR_FOLLOW_UP INTEGER default 0  NULL    COMMENT '最低跟进分数',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_score_config primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_forecast_period(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PERIOD_TYPE VARCHAR(20) NOT NULL    COMMENT '期间类型',
  PERIOD_START DATE NOT NULL    COMMENT '期间开始日期',
  PERIOD_END DATE NOT NULL    COMMENT '期间结束日期',
  LABEL VARCHAR(100) NULL    COMMENT '期间标签',
  STATUS VARCHAR(20) NOT NULL    COMMENT '期间状态',
  IS_CURRENT BOOLEAN default 0  NULL    COMMENT '是否当前期间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_forecast_period primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_territory(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PARENT_ID BIGINT NULL    COMMENT '父区域',
  TERRITORY_TYPE VARCHAR(20) NOT NULL    COMMENT '区域类型',
  MANAGER_ID BIGINT NULL    COMMENT '区域负责人',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '区域描述',
  FULL_PATH VARCHAR(500) NULL    COMMENT '路径冗余',
  LEVEL INTEGER default 0  NULL    COMMENT '层级深度',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  IS_LEAF BOOLEAN default 0  NULL    COMMENT '是否叶子节点',
  SORT_ORDER INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_territory primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_product_configurator(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PRODUCT_TYPE VARCHAR(100) NULL    COMMENT '适用产品品类',
  CONFIG_NAME VARCHAR(200) NULL    COMMENT '配置器名称',
  WIZARD_LAYOUT VARCHAR(4000) NULL    COMMENT '向导步骤布局(JSON)',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效开始日期',
  EFFECTIVE_TO DATE NULL    COMMENT '生效结束日期',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_product_configurator primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_bundle_pricing(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  BUNDLE_NAME VARCHAR(200) NOT NULL    COMMENT '捆绑包名称',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  DISCOUNT_TYPE VARCHAR(20) NULL    COMMENT '折扣类型',
  DISCOUNT_VALUE DECIMAL(20,4) NULL    COMMENT '折扣值',
  BUNDLE_AMOUNT DECIMAL(20,4) NULL    COMMENT '捆绑包总价',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效开始日期',
  EFFECTIVE_TO DATE NULL    COMMENT '生效结束日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_bundle_pricing primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_sequence(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TEMPLATE_TYPE VARCHAR(30) NOT NULL    COMMENT '序列模板类型',
  DESCRIPTION VARCHAR(500) NULL    COMMENT '描述',
  EXPECTED_DURATION INTEGER NULL    COMMENT '预期完成天数',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认序列',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_sequence primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_price_rule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  RULE_TYPE VARCHAR(30) NOT NULL    COMMENT '规则类型',
  PRIORITY INTEGER default 0  NULL    COMMENT '优先级',
  PRODUCT_ID BIGINT NULL    COMMENT '适用产品',
  PRODUCT_CATEGORY VARCHAR(100) NULL    COMMENT '适用产品品类',
  CUSTOMER_ID BIGINT NULL    COMMENT '适用客户',
  CUSTOMER_CATEGORY VARCHAR(100) NULL    COMMENT '适用客户类别',
  MIN_QUANTITY DECIMAL(20,4) NULL    COMMENT '最小数量',
  MAX_QUANTITY DECIMAL(20,4) NULL    COMMENT '最大数量',
  PRICE_OVERRIDE DECIMAL(20,4) NULL    COMMENT '覆盖单价',
  DISCOUNT_PERCENT DECIMAL(10,2) NULL    COMMENT '折扣百分比',
  DISCOUNT_AMOUNT DECIMAL(20,4) NULL    COMMENT '折扣固定金额',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  EFFECTIVE_FROM DATE NULL    COMMENT '生效开始日期',
  EFFECTIVE_TO DATE NULL    COMMENT '生效结束日期',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_price_rule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_stage(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  STAGE_NAME VARCHAR(200) NOT NULL    COMMENT '阶段名称',
  SEQUENCE INTEGER default 0  NOT NULL    COMMENT '排序',
  TEAM_ID BIGINT NULL    COMMENT '团队作用域',
  DEFAULT_PROBABILITY INTEGER NULL    COMMENT '默认成交概率%',
  IS_WON_STAGE BOOLEAN default 0  NULL    COMMENT '是否赢单阶段',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_stage primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_score_config_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONFIG_ID BIGINT NOT NULL    COMMENT '评分规则配置',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CRITERION_CODE VARCHAR(50) NOT NULL    COMMENT '准则编码',
  CRITERION_NAME VARCHAR(200) NULL    COMMENT '准则名称',
  WEIGHT INTEGER default 0  NULL    COMMENT '权重系数',
  SCORING_METHOD VARCHAR(20) NOT NULL    COMMENT '评分方法',
  LOOKUP_TABLE VARCHAR(4000) NULL    COMMENT '值表(JSON)',
  FORMULA VARCHAR(500) NULL    COMMENT '公式表达式',
  MAX_SCORE INTEGER default 0  NULL    COMMENT '最高分',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_score_config_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_forecast(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PERIOD_ID BIGINT NOT NULL    COMMENT '预测期间',
  TERRITORY_ID BIGINT NULL    COMMENT '销售区域',
  TEAM_ID BIGINT NULL    COMMENT '销售团队',
  OWNER_ID VARCHAR(36) NULL    COMMENT '销售员',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  COMMIT_AMOUNT DECIMAL(20,4) NULL    COMMENT '承诺金额',
  UPSIDE_AMOUNT DECIMAL(20,4) NULL    COMMENT '乐观金额',
  WEIGHTED_AMOUNT DECIMAL(20,4) NULL    COMMENT '加权金额',
  BEST_CASE_AMOUNT DECIMAL(20,4) NULL    COMMENT '最佳金额',
  OPPORTUNITY_COUNT INTEGER default 0  NULL    COMMENT '商机总数',
  COMMIT_OPPORTUNITY_COUNT INTEGER default 0  NULL    COMMENT '承诺商机数',
  EXPECTED_CLOSED_REVENUE DECIMAL(20,4) NULL    COMMENT '实际已关闭收入',
  LAST_CALCULATED_AT DATETIME NULL    COMMENT '最近计算时间',
  NOTES VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_forecast primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_territory_assignment_rule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  RULE_NAME VARCHAR(200) NOT NULL    COMMENT '规则名称',
  PRIORITY INTEGER default 0  NULL    COMMENT '优先级',
  TERRITORY_ID BIGINT NOT NULL    COMMENT '目标区域',
  CONDITION_TYPE VARCHAR(30) NOT NULL    COMMENT '条件类型',
  CONDITION_VALUE VARCHAR(4000) NULL    COMMENT '条件值(JSON)',
  ASSIGNMENT_METHOD VARCHAR(20) NOT NULL    COMMENT '分配方法',
  GROUP_ID BIGINT NULL    COMMENT '目标团队',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认规则',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_territory_assignment_rule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_quota(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TERRITORY_ID BIGINT NULL    COMMENT '区域',
  TEAM_ID BIGINT NULL    COMMENT '团队',
  OWNER_ID VARCHAR(36) NULL    COMMENT '销售员',
  PERIOD_TYPE VARCHAR(20) NOT NULL    COMMENT '配额期间类型',
  FISCAL_YEAR INTEGER NULL    COMMENT '财年',
  PERIOD_LABEL VARCHAR(100) NULL    COMMENT '期间标签',
  QUOTA_AMOUNT DECIMAL(20,4) NULL    COMMENT '配额金额',
  CURRENCY_ID BIGINT NULL    COMMENT '币种',
  IS_FINALIZED BOOLEAN default 0  NULL    COMMENT '是否已定稿',
  NOTES VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_quota primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_funnel(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FUNNEL_NAME VARCHAR(200) NOT NULL    COMMENT '漏斗名称',
  PERIOD_START DATE NOT NULL    COMMENT '分析期间开始',
  PERIOD_END DATE NOT NULL    COMMENT '分析期间结束',
  TERRITORY_ID BIGINT NULL    COMMENT '区域维度',
  TEAM_ID BIGINT NULL    COMMENT '团队维度',
  SOURCE_ID BIGINT NULL    COMMENT '来源维度',
  TOTAL_LEADS_AT_TOP INTEGER default 0  NULL    COMMENT '漏斗顶部线索量',
  TOTAL_OPPORTUNITIES INTEGER default 0  NULL    COMMENT '商机总量',
  TOTAL_WON INTEGER default 0  NULL    COMMENT '赢单总量',
  TOTAL_LOST INTEGER default 0  NULL    COMMENT '丢单总量',
  TOTAL_REVENUE DECIMAL(20,4) NULL    COMMENT '赢单总收入',
  LOST_REVENUE DECIMAL(20,4) NULL    COMMENT '丢失金额合计',
  WEIGHTED_REVENUE DECIMAL(20,4) NULL    COMMENT '加权收入合计',
  AVG_DEAL_SIZE DECIMAL(20,4) NULL    COMMENT '平均赢单金额',
  AVG_SALES_CYCLE_DAYS DECIMAL(10,2) NULL    COMMENT '平均销售周期天数',
  CALCULATED_AT DATETIME NULL    COMMENT '聚合计算时间',
  CALCULATED_BY VARCHAR(50) NULL    COMMENT '聚合计算人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_funnel primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_config_rule(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CONFIGURATOR_ID BIGINT NOT NULL    COMMENT '所属配置器',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  RULE_TYPE VARCHAR(20) NOT NULL    COMMENT '规则类型',
  SOURCE_FEATURE_CODE VARCHAR(100) NULL    COMMENT '条件特征编码',
  SOURCE_FEATURE_VALUE VARCHAR(200) NULL    COMMENT '条件特征值',
  TARGET_FEATURE_CODE VARCHAR(100) NULL    COMMENT '目标特征编码',
  TARGET_FEATURE_VALUE VARCHAR(200) NULL    COMMENT '目标特征值',
  CONDITION_EXPRESSION VARCHAR(500) NULL    COMMENT '复杂条件表达式',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_config_rule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_bundle_pricing_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  BUNDLE_ID BIGINT NOT NULL    COMMENT '所属捆绑包',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PRODUCT_ID BIGINT NULL    COMMENT '产品',
  QUANTITY DECIMAL(20,4) NULL    COMMENT '数量',
  UNIT_PRICE DECIMAL(20,4) NULL    COMMENT '单价',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_bundle_pricing_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_sequence_step(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SEQUENCE_ID BIGINT NOT NULL    COMMENT '所属序列',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  STEP_NAME VARCHAR(200) NOT NULL    COMMENT '步骤名称',
  STEP_ORDER INTEGER default 0  NOT NULL    COMMENT '步骤序号',
  DUE_DAYS INTEGER default 0  NULL    COMMENT '距上一步间隔天数',
  ACTIVITY_TYPE VARCHAR(20) NOT NULL    COMMENT '步骤活动类型',
  STEP_DESCRIPTION VARCHAR(1000) NULL    COMMENT '步骤说明',
  COMPLETION_CONDITION VARCHAR(30) NOT NULL    COMMENT '完成条件',
  IS_MANDATORY BOOLEAN default 1  NULL    COMMENT '是否必须完成',
  AUTO_CREATE_EVENT BOOLEAN default 1  NULL    COMMENT '是否自动创建事件',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_sequence_step primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_sequence_assignment(
  ID BIGINT NOT NULL    COMMENT 'ID',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  SEQUENCE_ID BIGINT NOT NULL    COMMENT '目标序列',
  PRIORITY INTEGER default 0  NULL    COMMENT '优先级',
  CONDITION_TYPE VARCHAR(30) NOT NULL    COMMENT '条件类型',
  CONDITION_VALUE VARCHAR(4000) NULL    COMMENT '条件值(JSON)',
  IS_ACTIVE BOOLEAN default 1  NULL    COMMENT '是否启用',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认规则',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_sequence_assignment primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  LEAD_TYPE VARCHAR(20) NOT NULL    COMMENT '线索/商机类型',
  PARTNER_ID BIGINT NULL    COMMENT '客户',
  CONTACT_NAME VARCHAR(100) NULL    COMMENT '联系人姓名',
  CONTACT_PHONE VARCHAR(50) NULL    COMMENT '联系电话',
  CONTACT_EMAIL VARCHAR(200) NULL    COMMENT '联系邮箱',
  COMPANY_NAME VARCHAR(200) NULL    COMMENT '公司名称',
  JOB_TITLE VARCHAR(100) NULL    COMMENT '职位',
  DEPARTMENT VARCHAR(100) NULL    COMMENT '部门',
  SOURCE_ID BIGINT NULL    COMMENT '线索来源',
  LEAD_STATUS_ID BIGINT NULL    COMMENT '线索状态',
  STAGE_ID BIGINT NULL    COMMENT '漏斗阶段',
  EXPECTED_REVENUE DECIMAL(20,4) NULL    COMMENT '预期收入',
  BEST_CASE_AMOUNT DECIMAL(20,4) NULL    COMMENT '乐观预期',
  WORST_CASE_AMOUNT DECIMAL(20,4) NULL    COMMENT '悲观预期',
  RECURRING_REVENUE DECIMAL(20,4) NULL    COMMENT '周期性收入',
  RECURRING_PLAN VARCHAR(50) NULL    COMMENT '周期性计划',
  EXPECTED_CLOSE_DATE DATE NULL    COMMENT '预期签单日',
  PROBABILITY INTEGER NULL    COMMENT '成交概率',
  CAMPAIGN_ID BIGINT NULL    COMMENT '营销活动',
  UTM_MEDIUM VARCHAR(100) NULL    COMMENT 'UTM Medium',
  UTM_SOURCE VARCHAR(100) NULL    COMMENT 'UTM Source',
  OWNER_ID VARCHAR(36) NULL    COMMENT '负责人',
  TEAM_ID BIGINT NULL    COMMENT '销售团队',
  LOST_REASON_ID BIGINT NULL    COMMENT '丢单原因',
  LOST_REASON_DESC VARCHAR(500) NULL    COMMENT '丢单描述',
  LAST_CONTACT_DATE DATETIME NULL    COMMENT '最后联系日期',
  NEXT_ACTIVITY_DATE DATETIME NULL    COMMENT '下次活动日期',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '转化结果单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '转化结果单据号',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_forecast_accuracy(
  ID BIGINT NOT NULL    COMMENT 'ID',
  FORECAST_ID BIGINT NULL    COMMENT '预测数据',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  PERIOD_ID BIGINT NOT NULL    COMMENT '预测期间',
  OWNER_ID VARCHAR(36) NULL    COMMENT '销售员',
  TEAM_ID BIGINT NULL    COMMENT '销售团队',
  TERRITORY_ID BIGINT NULL    COMMENT '销售区域',
  COMMIT_AMOUNT DECIMAL(20,4) NULL    COMMENT '承诺金额',
  UPSIDE_AMOUNT DECIMAL(20,4) NULL    COMMENT '乐观金额',
  ACTUAL_CLOSED_REVENUE DECIMAL(20,4) NULL    COMMENT '实际关闭收入',
  COMMIT_ACCURACY DECIMAL(10,4) NULL    COMMENT '承诺准确率',
  UPSIDE_ACCURACY DECIMAL(10,4) NULL    COMMENT '乐观准确率',
  DEVIATION_AMOUNT DECIMAL(20,4) NULL    COMMENT '偏差绝对值',
  CALCULATED_BY VARCHAR(50) NULL    COMMENT '计算人',
  CALCULATED_AT DATETIME NULL    COMMENT '计算时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_forecast_accuracy primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_funnel_stage_metrics(
  ID BIGINT NOT NULL    COMMENT 'ID',
  FUNNEL_ID BIGINT NOT NULL    COMMENT '所属漏斗',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  STAGE_ID BIGINT NOT NULL    COMMENT '阶段',
  STAGE_ORDER INTEGER default 0  NULL    COMMENT '阶段排序',
  STAGE_NAME VARCHAR(200) NULL    COMMENT '阶段名称(快照)',
  LEAD_COUNT_IN INTEGER default 0  NULL    COMMENT '进入本阶段线索数',
  LEAD_COUNT_OUT INTEGER default 0  NULL    COMMENT '流出本阶段线索数',
  LEAD_COUNT_REMAINING INTEGER default 0  NULL    COMMENT '期末仍在本阶段数',
  CONVERSION_RATE DECIMAL(10,4) NULL    COMMENT '转化率',
  DROP_OFF_RATE DECIMAL(10,4) NULL    COMMENT '流失率',
  AVG_DAYS_IN_STAGE DECIMAL(10,2) NULL    COMMENT '平均停留天数',
  LOST_COUNT INTEGER default 0  NULL    COMMENT '本阶段丢失数',
  LOST_AMOUNT DECIMAL(20,4) NULL    COMMENT '本阶段丢失金额',
  LOST_REASON_TOP VARCHAR(4000) NULL    COMMENT 'TOP丢失原因(JSON)',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_funnel_stage_metrics primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_event(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  EVENT_TYPE VARCHAR(20) NOT NULL    COMMENT '事件类型',
  EVENT_CATEGORY_ID BIGINT NULL    COMMENT '活动类别',
  SUBJECT VARCHAR(200) NOT NULL    COMMENT '主题',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  START_DATE_TIME DATETIME NOT NULL    COMMENT '开始时间',
  END_DATE_TIME DATETIME NULL    COMMENT '结束时间',
  DURATION INTEGER NULL    COMMENT '时长(分钟)',
  RELATED_LEAD_ID BIGINT NULL    COMMENT '关联线索/商机',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  PARTNER_ID BIGINT NULL    COMMENT '关联客户',
  CONTACT_ID BIGINT NULL    COMMENT '联系人',
  OWNER_ID VARCHAR(36) NULL    COMMENT '负责人',
  STATUS VARCHAR(20) NOT NULL    COMMENT '活动状态',
  PRIORITY VARCHAR(20) NOT NULL    COMMENT '优先级',
  IS_RECURRENT BOOLEAN default 0  NULL    COMMENT '是否重复事件',
  PARENT_EVENT_ID BIGINT NULL    COMMENT '父事件',
  REMINDER_MINUTES_BEFORE INTEGER NULL    COMMENT '提醒提前分钟数',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_event primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_activity(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '关联线索/商机',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ACTIVITY_TYPE VARCHAR(20) NOT NULL    COMMENT '活动类型',
  ACTIVITY_DATE DATETIME NOT NULL    COMMENT '活动日期',
  SUMMARY VARCHAR(500) NULL    COMMENT '内容摘要',
  OWNER_ID VARCHAR(36) NULL    COMMENT '负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_activity primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_conv_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '线索/商机',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FROM_STAGE_ID BIGINT NULL    COMMENT '前阶段',
  TO_STAGE_ID BIGINT NULL    COMMENT '后阶段',
  CHANGED_AT DATETIME NOT NULL    COMMENT '变更时间',
  CHANGED_BY VARCHAR(36) NULL    COMMENT '变更人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_conv_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_score(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '线索/商机',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONFIG_ID BIGINT NULL    COMMENT '评分规则版本',
  TOTAL_SCORE INTEGER default 0  NULL    COMMENT '总分',
  SCORE_BREAKDOWN VARCHAR(4000) NULL    COMMENT '评分快照(JSON)',
  AUTO_QUALIFIED BOOLEAN default 0  NULL    COMMENT '是否自动转商机',
  TRIGGERED_ACTION VARCHAR(20) NULL    COMMENT '触发动作',
  CALCULATED_AT DATETIME NULL    COMMENT '计算时间',
  TRIGGER_EVENT VARCHAR(20) NULL    COMMENT '触发计算事件',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_score primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_forecast_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  FORECAST_ID BIGINT NOT NULL    COMMENT '预测数据',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  LEAD_ID BIGINT NOT NULL    COMMENT '商机',
  PROBABILITY INTEGER NULL    COMMENT '概率快照',
  EXPECTED_REVENUE DECIMAL(20,4) NULL    COMMENT '预期收入快照',
  WEIGHTED_REVENUE DECIMAL(20,4) NULL    COMMENT '加权收入',
  FORECAST_CATEGORY VARCHAR(20) NOT NULL    COMMENT '预测分类',
  INCLUDED_IN_COMMIT BOOLEAN default 0  NULL    COMMENT '是否计入承诺',
  STAGE_NAME VARCHAR(200) NULL    COMMENT '阶段名快照',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_forecast_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_seq_progress(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '线索/商机',
  SEQUENCE_ID BIGINT NOT NULL    COMMENT '应用序列',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CURRENT_STEP_INDEX INTEGER default 0  NULL    COMMENT '当前步骤序号',
  STATUS VARCHAR(20) NOT NULL    COMMENT '状态',
  STARTED_AT DATETIME NULL    COMMENT '开始时间',
  COMPLETED_AT DATETIME NULL    COMMENT '完成时间',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_seq_progress primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_score_line(
  ID BIGINT NOT NULL    COMMENT 'ID',
  SCORE_ID BIGINT NOT NULL    COMMENT '评分记录',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CONFIG_LINE_ID BIGINT NULL    COMMENT '对应准则行',
  CRITERION_CODE VARCHAR(50) NULL    COMMENT '准则编码(快照)',
  CRITERION_NAME VARCHAR(200) NULL    COMMENT '准则名称(快照)',
  RAW_VALUE VARCHAR(500) NULL    COMMENT '原始值',
  LOOKUP_VALUE VARCHAR(200) NULL    COMMENT '匹配档次',
  RAW_SCORE INTEGER default 0  NULL    COMMENT '原始得分',
  WEIGHTED_SCORE INTEGER default 0  NULL    COMMENT '加权得分',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_score_line primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_crm_source COMMENT '线索来源';
                
   ALTER TABLE erp_crm_lead_status COMMENT '线索状态';
                
   ALTER TABLE erp_crm_lost_reason COMMENT '丢单原因';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_crm_event_category COMMENT '活动类别';
                
   ALTER TABLE erp_md_partner_contact COMMENT '往来单位联系人';
                
   ALTER TABLE erp_crm_quote_template COMMENT '报价模板';
                
   ALTER TABLE erp_md_currency COMMENT '币种';
                
   ALTER TABLE erp_md_material COMMENT '物料';
                
   ALTER TABLE erp_crm_team COMMENT '销售团队';
                
   ALTER TABLE erp_crm_campaign COMMENT '营销活动';
                
   ALTER TABLE erp_crm_lead_score_config COMMENT '评分规则配置';
                
   ALTER TABLE erp_crm_forecast_period COMMENT '预测期间';
                
   ALTER TABLE erp_crm_territory COMMENT '销售区域';
                
   ALTER TABLE erp_crm_product_configurator COMMENT '产品配置器';
                
   ALTER TABLE erp_crm_bundle_pricing COMMENT '捆绑定价';
                
   ALTER TABLE erp_crm_sequence COMMENT '销售序列';
                
   ALTER TABLE erp_crm_price_rule COMMENT '价格规则';
                
   ALTER TABLE erp_crm_stage COMMENT '漏斗阶段';
                
   ALTER TABLE erp_crm_lead_score_config_line COMMENT '评分准则明细';
                
   ALTER TABLE erp_crm_forecast COMMENT '预测数据';
                
   ALTER TABLE erp_crm_territory_assignment_rule COMMENT '区域分配规则';
                
   ALTER TABLE erp_crm_quota COMMENT '销售配额';
                
   ALTER TABLE erp_crm_lead_funnel COMMENT '线索漏斗';
                
   ALTER TABLE erp_crm_config_rule COMMENT '配置规则';
                
   ALTER TABLE erp_crm_bundle_pricing_line COMMENT '捆绑包明细';
                
   ALTER TABLE erp_crm_sequence_step COMMENT '序列步骤';
                
   ALTER TABLE erp_crm_sequence_assignment COMMENT '序列分配规则';
                
   ALTER TABLE erp_crm_lead COMMENT '线索/商机';
                
   ALTER TABLE erp_crm_forecast_accuracy COMMENT '预测准确率';
                
   ALTER TABLE erp_crm_funnel_stage_metrics COMMENT '漏斗阶段度量';
                
   ALTER TABLE erp_crm_event COMMENT '活动/事件';
                
   ALTER TABLE erp_crm_activity COMMENT '活动记录';
                
   ALTER TABLE erp_crm_lead_conv_log COMMENT '阶段流转日志';
                
   ALTER TABLE erp_crm_lead_score COMMENT '线索评分记录';
                
   ALTER TABLE erp_crm_forecast_line COMMENT '预测明细';
                
   ALTER TABLE erp_crm_lead_seq_progress COMMENT '线索序列进度';
                
   ALTER TABLE erp_crm_lead_score_line COMMENT '评分记录明细';
                
