
CREATE TABLE erp_md_partner(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  PARTNER_TYPE INTEGER NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  CREDIT_LIMIT VARCHAR(50) NULL    COMMENT 'null',
  constraint PK_erp_md_partner primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_source(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_source primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_status(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_status primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lost_reason(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  SEQUENCE INTEGER default 0  NULL    COMMENT '排序',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lost_reason primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_md_organization(
  ID BIGINT NULL    COMMENT 'null',
  CODE VARCHAR(50) NULL    COMMENT 'null',
  NAME VARCHAR(200) NULL    COMMENT 'null',
  ORG_TYPE INTEGER NULL    COMMENT 'null',
  PARENT_ID BIGINT NULL    COMMENT 'null',
  STATUS INTEGER NULL    COMMENT 'null',
  constraint PK_erp_md_organization primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_event_category(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  COLOR VARCHAR(20) NULL    COMMENT '日历颜色',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_event_category primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_quote_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  TEMPLATE_CONTENT VARCHAR(4000) NULL    COMMENT '模板内容',
  IS_DEFAULT BOOLEAN default 0  NULL    COMMENT '是否默认',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_quote_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_team(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  TEAM_LEADER_ID BIGINT NULL    COMMENT '团队负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_team primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_campaign(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  NAME VARCHAR(200) NOT NULL    COMMENT '名称',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  CAMPAIGN_NAME VARCHAR(200) NOT NULL    COMMENT '活动名称',
  MEDIUM VARCHAR(100) NULL    COMMENT 'UTM Medium',
  SOURCE VARCHAR(100) NULL    COMMENT 'UTM Source',
  START_DATE DATE NULL    COMMENT '开始日期',
  END_DATE DATE NULL    COMMENT '结束日期',
  BUDGET_AMOUNT DECIMAL(20,4) NULL    COMMENT '预算金额',
  ACTUAL_COST DECIMAL(20,4) NULL    COMMENT '实际成本',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_campaign primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_stage(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  STAGE_NAME VARCHAR(200) NOT NULL    COMMENT '阶段名称',
  SEQUENCE INTEGER default 0  NOT NULL    COMMENT '排序',
  TEAM_ID BIGINT NULL    COMMENT '团队作用域',
  DEFAULT_PROBABILITY INTEGER NULL    COMMENT '默认成交概率%',
  IS_WON_STAGE BOOLEAN default 0  NULL    COMMENT '是否赢单阶段',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_stage primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  LEAD_TYPE VARCHAR(20) NOT NULL    COMMENT '线索/商机类型',
  PARTNER_ID BIGINT NULL    COMMENT '客户',
  CONTACT_NAME VARCHAR(100) NULL    COMMENT '联系人姓名',
  CONTACT_PHONE VARCHAR(50) NULL    COMMENT '联系电话',
  CONTACT_EMAIL VARCHAR(200) NULL    COMMENT '联系邮箱',
  COMPANY_NAME VARCHAR(200) NULL    COMMENT '公司名称',
  JOB_TITLE VARCHAR(100) NULL    COMMENT '职位',
  DEPARTMENT VARCHAR(100) NULL    COMMENT '部门',
  SOURCE_ID BIGINT NULL    COMMENT '线索来源',
  LEAD_STATUS_ID BIGINT NULL    COMMENT '线索状态',
  STAGE_ID BIGINT NULL    COMMENT '漏斗阶段',
  EXPECTED_REVENUE DECIMAL(20,4) NULL    COMMENT '预期收入',
  BEST_CASE_AMOUNT DECIMAL(20,4) NULL    COMMENT '乐观预期',
  WORST_CASE_AMOUNT DECIMAL(20,4) NULL    COMMENT '悲观预期',
  RECURRING_REVENUE DECIMAL(20,4) NULL    COMMENT '周期性收入',
  RECURRING_PLAN VARCHAR(50) NULL    COMMENT '周期性计划',
  EXPECTED_CLOSE_DATE DATE NULL    COMMENT '预期签单日',
  PROBABILITY INTEGER NULL    COMMENT '成交概率',
  CAMPAIGN_ID BIGINT NULL    COMMENT '营销活动',
  UTM_MEDIUM VARCHAR(100) NULL    COMMENT 'UTM Medium',
  UTM_SOURCE VARCHAR(100) NULL    COMMENT 'UTM Source',
  OWNER_ID BIGINT NULL    COMMENT '负责人',
  TEAM_ID BIGINT NULL    COMMENT '销售团队',
  LOST_REASON_ID BIGINT NULL    COMMENT '丢单原因',
  LOST_REASON_DESC VARCHAR(500) NULL    COMMENT '丢单描述',
  LAST_CONTACT_DATE DATETIME NULL    COMMENT '最后联系日期',
  NEXT_ACTIVITY_DATE DATETIME NULL    COMMENT '下次活动日期',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '转化结果单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '转化结果单据号',
  DOC_STATUS VARCHAR(20) NOT NULL    COMMENT '单据状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_event(
  ID BIGINT NOT NULL    COMMENT 'ID',
  CODE VARCHAR(50) NOT NULL    COMMENT '编码',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  EVENT_TYPE VARCHAR(20) NOT NULL    COMMENT '事件类型',
  EVENT_CATEGORY_ID BIGINT NULL    COMMENT '活动类别',
  SUBJECT VARCHAR(200) NOT NULL    COMMENT '主题',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  START_DATE_TIME DATETIME NOT NULL    COMMENT '开始时间',
  END_DATE_TIME DATETIME NULL    COMMENT '结束时间',
  DURATION INTEGER NULL    COMMENT '时长(分钟)',
  RELATED_LEAD_ID BIGINT NULL    COMMENT '关联线索/商机',
  RELATED_BILL_TYPE VARCHAR(50) NULL    COMMENT '关联单据类型',
  RELATED_BILL_CODE VARCHAR(50) NULL    COMMENT '关联单据号',
  PARTNER_ID BIGINT NULL    COMMENT '关联客户',
  CONTACT_ID BIGINT NULL    COMMENT '联系人',
  OWNER_ID BIGINT NULL    COMMENT '负责人',
  STATUS VARCHAR(20) NOT NULL    COMMENT '活动状态',
  PRIORITY VARCHAR(20) NOT NULL    COMMENT '优先级',
  IS_RECURRENT BOOLEAN default 0  NULL    COMMENT '是否重复事件',
  PARENT_EVENT_ID BIGINT NULL    COMMENT '父事件',
  REMINDER_MINUTES_BEFORE INTEGER NULL    COMMENT '提醒提前分钟数',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_event primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_activity(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '关联线索/商机',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  ACTIVITY_TYPE VARCHAR(20) NOT NULL    COMMENT '活动类型',
  ACTIVITY_DATE DATETIME NOT NULL    COMMENT '活动日期',
  SUMMARY VARCHAR(500) NULL    COMMENT '内容摘要',
  OWNER_ID BIGINT NULL    COMMENT '负责人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_activity primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_crm_lead_conv_log(
  ID BIGINT NOT NULL    COMMENT 'ID',
  LEAD_ID BIGINT NOT NULL    COMMENT '线索/商机',
  ORG_ID BIGINT NULL    COMMENT '业务组织',
  FROM_STAGE_ID BIGINT NULL    COMMENT '前阶段',
  TO_STAGE_ID BIGINT NULL    COMMENT '后阶段',
  CHANGED_AT DATETIME NOT NULL    COMMENT '变更时间',
  CHANGED_BY BIGINT NULL    COMMENT '变更人',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_crm_lead_conv_log primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_md_partner COMMENT '往来单位';
                
   ALTER TABLE erp_crm_source COMMENT '线索来源';
                
   ALTER TABLE erp_crm_lead_status COMMENT '线索状态';
                
   ALTER TABLE erp_crm_lost_reason COMMENT '丢单原因';
                
   ALTER TABLE erp_md_organization COMMENT '组织';
                
   ALTER TABLE erp_crm_event_category COMMENT '活动类别';
                
   ALTER TABLE erp_crm_quote_template COMMENT '报价模板';
                
   ALTER TABLE erp_crm_team COMMENT '销售团队';
                
   ALTER TABLE erp_crm_campaign COMMENT '营销活动';
                
   ALTER TABLE erp_crm_stage COMMENT '漏斗阶段';
                
   ALTER TABLE erp_crm_lead COMMENT '线索/商机';
                
   ALTER TABLE erp_crm_event COMMENT '活动/事件';
                
   ALTER TABLE erp_crm_activity COMMENT '活动记录';
                
   ALTER TABLE erp_crm_lead_conv_log COMMENT '阶段流转日志';
                
