
CREATE TABLE erp_sys_notification_template(
  ID BIGINT NOT NULL    COMMENT 'ID',
  NOTIFICATION_TYPE VARCHAR(100) NOT NULL    COMMENT '业务事件键',
  NAME VARCHAR(200) NOT NULL    COMMENT '模板名称',
  CHANNEL_SET VARCHAR(100) default 'IN_APP'  NOT NULL    COMMENT '渠道集合',
  SUBJECT_TPL VARCHAR(2000) NULL    COMMENT '标题模板',
  BODY_TPL VARCHAR(4000) NULL    COMMENT '正文模板',
  RECIPIENT_RESOLVER VARCHAR(20) default 'ROLE'  NOT NULL    COMMENT '接收人解析器',
  RECIPIENT_CONFIG VARCHAR(2000) NULL    COMMENT '接收人配置(JSON)',
  MERGE_WINDOW_SECONDS INTEGER default 300  NULL    COMMENT '合并窗口(秒)',
  MERGE_STRATEGY VARCHAR(30) default 'MERGE_BY_USER_TYPE'  NOT NULL    COMMENT '合并策略',
  STATUS VARCHAR(20) default 'DRAFT'  NOT NULL    COMMENT '模板状态',
  REMARK VARCHAR(1000) NULL    COMMENT '备注',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_sys_notification_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sys_notification(
  ID BIGINT NOT NULL    COMMENT 'ID',
  TEMPLATE_ID BIGINT NULL    COMMENT '模板ID',
  NOTIFICATION_TYPE VARCHAR(100) NOT NULL    COMMENT '业务事件键',
  RECIPIENT_USER_ID VARCHAR(36) NULL    COMMENT '接收用户',
  RECIPIENT_PARTNER_ID BIGINT NULL    COMMENT '接收业务伙伴',
  RECIPIENT_DEPT_ID BIGINT NULL    COMMENT '接收部门',
  CHANNEL VARCHAR(20) default 'IN_APP'  NOT NULL    COMMENT '渠道',
  SUBJECT VARCHAR(500) NULL    COMMENT '标题',
  BODY VARCHAR(4000) NULL    COMMENT '正文',
  PAYLOAD_JSON VARCHAR(4000) NULL    COMMENT '负载JSON',
  STATUS VARCHAR(20) default 'PENDING'  NOT NULL    COMMENT '状态',
  MERGE_GROUP_ID VARCHAR(200) NULL    COMMENT '合并组ID',
  MERGE_COUNT INTEGER default 1  NULL    COMMENT '合并次数',
  SENT_AT DATETIME(3) NULL    COMMENT '发送时间',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误信息',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_sys_notification primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE erp_sys_notification_read(
  ID BIGINT NOT NULL    COMMENT 'ID',
  NOTIFICATION_ID BIGINT NOT NULL    COMMENT '通知ID',
  USER_ID VARCHAR(36) NOT NULL    COMMENT '用户',
  READ_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '阅读时间',
  DEL_VERSION BIGINT default 0  NOT NULL    COMMENT '逻辑删除版本',
  VERSION INTEGER default 0  NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_erp_sys_notification_read primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE erp_sys_notification_template COMMENT '通知模板';
                
   ALTER TABLE erp_sys_notification COMMENT '通知实例';
                
   ALTER TABLE erp_sys_notification_read COMMENT '通知已读记录';
                
